Repository kickstarter/android-oss, pull requests merged in 2018-09, with the labels that each got.

#323 [Bug Fix] - Fixed TokenListener crash on devices 8 and higher
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/libs/DeviceRegistrar.java
  app/src/main/java/com/kickstarter/services/firebase/Dispatcher.kt
  app/src/main/java/com/kickstarter/services/firebase/RegisterService.java
  app/src/main/java/com/kickstarter/services/firebase/TokenListenerService.java
  app/src/main/java/com/kickstarter/services/firebase/UnregisterService.java
Labels: bug

#329 [Enhancement] - Completed Change Email screen layout
  app/src/main/AndroidManifest.xml
  app/src/main/assets/json/server-config.json
  app/src/main/java/com/kickstarter/ui/activities/AccountActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ChangeEmailActivity.kt
  app/src/main/res/layout/activity_change_email.xml
  app/src/main/res/layout/change_email_toolbar.xml
  app/src/main/res/values-de/strings_i18n.xml
  app/src/main/res/values-es/strings_i18n.xml
  app/src/main/res/values-fr/strings_i18n.xml
  app/src/main/res/values-ja/strings_i18n.xml
  app/src/main/res/values/strings_i18n.xml
Labels: UI

#334 ENHANCE ❗️Visual Indication when you're not hitting prod
  app/src/main/java/com/kickstarter/ui/toolbars/KSToolbar.java
Labels: enhancement

#335 ENHANCE ✨Smooth scrolling to the top of the disco fragment when reselecting a tab.
  app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.java
  app/src/main/java/com/kickstarter/ui/adapters/DiscoveryPagerAdapter.java
  app/src/main/java/com/kickstarter/ui/fragments/DiscoveryFragment.java
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
Labels: enhancement

#341 [Enhancement] - User can successfully change Email
  app/src/main/assets/json/server-config.json
  app/src/main/java/com/kickstarter/extensions/SnackbarExt.kt
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/ui/activities/ChangeEmailActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/ChangeEmailViewModel.kt
  app/src/main/res/drawable-hdpi/ic_action_check.png
  app/src/main/res/drawable-mdpi/ic_action_check.png
  app/src/main/res/drawable-xhdpi/ic_action_check.png
  app/src/main/res/drawable-xxhdpi/ic_action_check.png
  app/src/main/res/drawable/change_email_success_bg.xml
  app/src/main/res/layout/activity_change_email.xml
  app/src/main/res/layout/change_email_toolbar.xml
  app/src/main/res/values-de/strings_i18n.xml
  app/src/main/res/values-es/strings_i18n.xml
  app/src/main/res/values-fr/strings_i18n.xml
  app/src/main/res/values-ja/strings_i18n.xml
  app/src/main/res/values/strings_i18n.xml
  app/src/test/java/com/kickstarter/viewmodels/ChangeEmailViewModelTest.kt
Labels: enhancement
