Repository kickstarter/android-oss, pull requests merged in 2018-10, with the labels that each got.

#347 [bug] Fixing the drawer getting cut off and reformatting.
  app/src/main/res/layout/discovery_drawer_logged_in_view.xml
  app/src/main/res/layout/discovery_layout.xml
Labels: bug

#348 [bug] Fixing the drawer getting cut off and reformatting pt 2
  app/src/main/res/layout/discovery_drawer_logged_out_view.xml
  app/src/main/res/values-v21/dimens.xml
  app/src/main/res/values/dimens.xml
Labels: Investment Day!, bug

#354 [Enhancement] - Currency Preferences on Project Pages
  app/src/main/java/com/kickstarter/libs/KSCurrency.java
  app/src/main/java/com/kickstarter/mock/factories/ProjectFactory.java
  app/src/main/java/com/kickstarter/models/Project.java
  app/src/main/java/com/kickstarter/ui/viewholders/ProjectViewHolder.java
  app/src/main/java/com/kickstarter/ui/viewholders/RewardViewHolder.java
  app/src/main/java/com/kickstarter/viewmodels/ProjectHolderViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/RewardViewModel.java
  app/src/test/java/com/kickstarter/KSCurrencyTest.java
  app/src/test/java/com/kickstarter/viewmodels/ProjectHolderViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/RewardViewModelTest.java
Labels: enhancement
