Repository kickstarter/android-oss, pull requests merged in 2018-12, with the labels that each got.

#399 [Enhancement] - Add Music Newsletter to our Settings
  app/src/main/java/com/kickstarter/models/User.java
  app/src/main/java/com/kickstarter/services/ApiClient.java
  app/src/main/java/com/kickstarter/services/apirequests/SettingsBody.java
  app/src/main/java/com/kickstarter/ui/activities/NewsletterActivity.kt
  app/src/main/java/com/kickstarter/ui/data/Newsletter.java
  app/src/main/java/com/kickstarter/viewmodels/NewsletterViewModel.kt
  app/src/main/res/layout/activity_newsletter.xml
  app/src/test/java/com/kickstarter/viewmodels/NewsletterViewModelTest.kt
  fastlane/report.xml
Labels: enhancement

#398 [🚮] MixPanel removal
  Makefile
  NOTICE
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/ApplicationGraph.java
  app/src/main/java/com/kickstarter/ApplicationModule.java
  app/src/main/java/com/kickstarter/libs/Koala.java
  app/src/main/java/com/kickstarter/libs/KoalaTrackingClient.java
  app/src/main/java/com/kickstarter/libs/TrackingClientType.java
  app/src/main/java/com/kickstarter/libs/qualifiers/KoalaEndpoint.kt
  app/src/main/java/com/kickstarter/libs/qualifiers/KoalaRetrofit.kt
  app/src/main/java/com/kickstarter/libs/utils/BooleanUtils.java
  app/src/main/java/com/kickstarter/libs/utils/KoalaUtils.java
  app/src/main/java/com/kickstarter/libs/utils/ProjectUtils.java
  app/src/main/java/com/kickstarter/services/KoalaBackgroundService.kt
  app/src/main/java/com/kickstarter/services/KoalaService.kt
  app/src/main/java/com/kickstarter/services/firebase/Dispatcher.kt
  app/src/main/java/com/kickstarter/ui/IntentKey.java
  app/src/test/java/com/kickstarter/KSRobolectricTestCase.java
  app/src/test/java/com/kickstarter/libs/KoalaTest.kt
  app/src/test/java/com/kickstarter/libs/MockTrackingClient.java
  app/src/test/java/com/kickstarter/libs/utils/BooleanUtilsTest.java
  config/koala_endpoint.xml.example
Labels: Investment Day!

#405 [UI-Fix] - Settings bottom padding missing
  app/src/main/res/layout/settings_layout.xml
Labels: UI

#416 Fixing button height in 2FA screen.
  app/src/main/res/layout/two_factor_form_view.xml
Labels: Investment Day!
