Repository kickstarter/android-oss, pull requests merged in 2019-06, with the labels that each got.

#528 KSCurrency refactor
  app/src/main/java/com/kickstarter/libs/KSCurrency.java
  app/src/main/java/com/kickstarter/libs/models/Country.kt
  app/src/main/java/com/kickstarter/mock/factories/ConfigFactory.java
  app/src/main/java/com/kickstarter/mock/factories/ProjectFactory.java
  app/src/main/java/com/kickstarter/models/Backing.java
  app/src/main/java/com/kickstarter/models/Project.java
  app/src/main/java/com/kickstarter/ui/activities/CheckoutActivity.java
  app/src/main/java/com/kickstarter/ui/activities/MessagesActivity.java
  app/src/main/java/com/kickstarter/ui/viewholders/CreatorDashboardHeaderViewHolder.java
  app/src/main/java/com/kickstarter/ui/viewholders/CreatorDashboardReferrerBreakdownViewHolder.java
  app/src/main/java/com/kickstarter/ui/viewholders/CreatorDashboardReferrerStatsRowViewHolder.java
  app/src/main/java/com/kickstarter/ui/viewholders/CreatorDashboardRewardStatsRowViewHolder.java
  app/src/main/java/com/kickstarter/ui/viewholders/ProjectStateChangedPositiveViewHolder.java
  app/src/main/java/com/kickstarter/ui/viewholders/RewardViewHolder.java
  app/src/main/java/com/kickstarter/viewmodels/BackingViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/DashboardRewardStatsRowHolderViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/HorizontalRewardViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectHolderViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/RewardViewModel.java
  app/src/main/res/layout/reward_view.xml
  app/src/test/java/com/kickstarter/KSCurrencyTest.java
  app/src/test/java/com/kickstarter/libs/KoalaTest.kt
  app/src/test/java/com/kickstarter/viewmodels/HorizontalRewardViewHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardViewModelTest.java
Labels: refactor 🛠

#517 User can view shipping countries from pledge screen
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/extensions/ActivityExt.kt
  app/src/main/java/com/kickstarter/libs/KSCurrency.java
  app/src/main/java/com/kickstarter/mock/factories/ShippingRuleFactory.kt
  app/src/main/java/com/kickstarter/mock/factories/ShippingRulesEnvelopeFactory.kt
  app/src/main/java/com/kickstarter/mock/services/MockApiClient.java
  app/src/main/java/com/kickstarter/models/Reward.java
  app/src/main/java/com/kickstarter/models/ShippingRule.kt
  app/src/main/java/com/kickstarter/services/ApiClient.java
  app/src/main/java/com/kickstarter/services/ApiClientType.java
  app/src/main/java/com/kickstarter/services/ApiService.java
  app/src/main/java/com/kickstarter/services/apiresponses/ShippingRulesEnvelope.java
  app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
  app/src/main/java/com/kickstarter/ui/adapters/KSArrayAdapter.kt
  app/src/main/java/com/kickstarter/ui/adapters/ShippingRulesAdapter.kt
  app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
  app/src/main/java/com/kickstarter/ui/viewholders/KSArrayViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ShippingRuleViewHolder.kt
  app/src/main/java/com/kickstarter/ui/views/CenterSpan.kt
  app/src/main/java/com/kickstarter/viewmodels/HorizontalRewardViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectHolderViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/ShippingRuleViewHolderViewModel.kt
  app/src/main/res/drawable/pledge_amounts_loading_states.xml
  app/src/main/res/drawable/rect_white_rounded.xml
  app/src/main/res/layout/fragment_pledge.xml
  app/src/main/res/layout/item_reward.xml
  app/src/main/res/layout/item_shipping_rule.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/com/kickstarter/KSCurrencyTest.java
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ResetPasswordViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ShippingRuleViewHolderViewModelTest.kt
Labels: feature ✨

#534 Reward disabled state
  app/src/main/java/com/kickstarter/ui/viewholders/HorizontalRewardViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/HorizontalRewardViewHolderViewModel.kt
  app/src/main/res/drawable/button_reward_pledge.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: feature ✨

#535 [🔢] Currency refactor 2
  app/src/main/java/com/kickstarter/libs/KSCurrency.java
  app/src/main/java/com/kickstarter/libs/utils/StringUtils.java
  app/src/main/java/com/kickstarter/libs/utils/ViewUtils.java
  app/src/main/java/com/kickstarter/mock/factories/ShippingRuleFactory.kt
  app/src/main/java/com/kickstarter/ui/viewholders/CreatorDashboardHeaderViewHolder.java
  app/src/main/java/com/kickstarter/ui/viewholders/CreatorDashboardReferrerBreakdownViewHolder.java
  app/src/main/java/com/kickstarter/ui/viewholders/CreatorDashboardReferrerStatsRowViewHolder.java
  app/src/main/java/com/kickstarter/ui/viewholders/CreatorDashboardRewardStatsRowViewHolder.java
  app/src/main/java/com/kickstarter/ui/viewholders/ProjectStateChangedPositiveViewHolder.java
  app/src/main/java/com/kickstarter/viewmodels/BackingViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/HorizontalRewardViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectHolderViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/ShippingRuleViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/KSCurrencyTest.java
  app/src/test/java/com/kickstarter/libs/rx/operators/ApiErrorOperatorTest.java
  app/src/test/java/com/kickstarter/libs/utils/StringUtilsTest.java
  app/src/test/java/com/kickstarter/viewmodels/HorizontalRewardViewHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/ShippingRuleViewHolderViewModelTest.kt
Labels: refactor 🛠

#536 View Pledge [UI]
  app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Labels: UI 🎨
