Repository kickstarter/android-oss, pull requests merged in 2019-04, with the labels that each got.

#507 Fixing bug with android pay button
  app/src/main/res/layout/checkout_layout.xml
Labels: bug 🐛

#510 [🐞] Default drawer params bug
  app/src/main/java/com/kickstarter/services/DiscoveryParams.java
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java
  app/src/test/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.java
Labels: bug 🐛

#511 [Release 1.13.0] - Bumped internal and external
  app/external_version_name.txt
  app/internal_version_name.txt
  app/src/main/assets/json/server-config.json
Labels: release 🚀

#504 Migrate Horizontal rewards into the Project Page
  app/src/main/java/com/kickstarter/libs/utils/RewardDecoration.kt
  app/src/main/java/com/kickstarter/libs/utils/RewardUtils.java
  app/src/main/java/com/kickstarter/mock/factories/RewardFactory.java
  app/src/main/java/com/kickstarter/models/Reward.java
  app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
  app/src/main/java/com/kickstarter/ui/adapters/HorizontalRewardsAdapter.kt
  app/src/main/java/com/kickstarter/ui/adapters/ProjectAdapter.java
  app/src/main/java/com/kickstarter/ui/fragments/RewardsFragment.kt
  app/src/main/java/com/kickstarter/ui/viewholders/HorizontalNoRewardViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/HorizontalRewardViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ProjectViewHolder.java
  app/src/main/java/com/kickstarter/ui/viewholders/RewardViewHolder.java
  app/src/main/java/com/kickstarter/viewmodels/HorizontalNoRewardViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/HorizontalRewardViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectHolderViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardViewModel.java
  app/src/main/res/drawable/text_view_light_green_background.xml
  app/src/main/res/layout-land/project_main_layout.xml
  app/src/main/res/layout/fragment_rewards.xml
  app/src/main/res/layout/item_no_reward.xml
  app/src/main/res/layout/item_reward.xml
  app/src/main/res/layout/project_layout.xml
  app/src/main/res/layout/reward_view.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/com/kickstarter/libs/utils/RewardUtilsTest.java
  app/src/test/java/com/kickstarter/viewmodels/HorizontalNoRewardViewHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/HorizontalRewardViewHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardFragmentViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardViewModelTest.java
Labels: feature ✨

#512 [Maintenance]- Updated external version code and Fastlane report
  app/external_version_code.txt
  fastlane/report.xml
Labels: maintenance 🗜

#513 Horizontal Rewards Design Sweep
  app/src/main/assets/json/server-config.json
  app/src/main/java/com/kickstarter/libs/utils/RewardItemDecorator.kt
  app/src/main/java/com/kickstarter/ui/activities/BackingActivity.java
  app/src/main/java/com/kickstarter/ui/adapters/RewardItemsAdapter.java
  app/src/main/java/com/kickstarter/ui/fragments/RewardsFragment.kt
  app/src/main/java/com/kickstarter/ui/viewholders/HorizontalRewardViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/RewardViewHolder.java
  app/src/main/java/com/kickstarter/viewmodels/HorizontalRewardViewHolderViewModel.kt
  app/src/main/res/drawable/divider_grey_300_horizontal.xml
  app/src/main/res/layout/item_no_reward.xml
  app/src/main/res/layout/item_reward.xml
  app/src/main/res/layout/item_reward_placeholder_card.xml
  app/src/main/res/layout/project_layout.xml
  app/src/main/res/layout/rewards_item_view.xml
  app/src/main/res/values-de/strings_i18n.xml
  app/src/main/res/values-es/strings_i18n.xml
  app/src/main/res/values-fr/strings_i18n.xml
  app/src/main/res/values-ja/strings_i18n.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings_i18n.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/com/kickstarter/viewmodels/HorizontalRewardViewHolderViewModelTest.kt
Labels: UI 🎨, feature ✨
