Repository kickstarter/android-oss, pull requests merged in 2019-02, with the labels that each got.

#437 [Enhancement] - Change Settings > Help web views to Chrome Custom Tabs
  app/build.gradle
  app/src/androidTest/kotlin/HelpSettingsActivityTest.kt
  app/src/main/java/com/kickstarter/models/chrome/ChromeTabsHelper.kt
  app/src/main/java/com/kickstarter/models/chrome/ChromeTabsHelperActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/HelpActivity.java
  app/src/main/java/com/kickstarter/ui/activities/HelpSettingsActivity.kt
Labels: enhancement

#457 Removing custom styling on Snackbars
  app/src/main/java/com/kickstarter/extensions/ActivityExt.kt
  app/src/main/java/com/kickstarter/extensions/SnackbarExt.kt
  app/src/main/java/com/kickstarter/libs/BaseActivity.java
  app/src/main/java/com/kickstarter/ui/activities/AccountActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ChangeEmailActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ChangePasswordActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/LoginActivity.kt
Labels: UI 🎨

#460 Staging toolbar part 2
  app/src/main/java/com/kickstarter/ui/toolbars/KSToolbar.java
Labels: UI 🎨

#462 Removing pipeErrorsTo
  app/src/main/java/com/kickstarter/libs/rx/transformers/Transformers.java
  app/src/main/java/com/kickstarter/ui/activities/ProjectNotificationSettingsActivity.java
  app/src/main/java/com/kickstarter/viewmodels/ProjectNotificationSettingsViewModel.java
  app/src/test/java/com/kickstarter/libs/rx/transformers/NeverErrorTransformerTest.java
  app/src/test/java/com/kickstarter/viewmodels/ProjectNotificationSettingsViewModelTest.kt
Labels: maintenance 🗜

#466 Payment methods padding
  app/src/main/java/com/kickstarter/ui/viewholders/PaymentMethodsViewHolder.kt
  app/src/main/res/layout/activity_account.xml
  app/src/main/res/layout/item_payment_method.xml
Labels: UI 🎨

#467 [Bug] fixed the delay in the pledge activity digest spinner
  app/src/main/java/com/kickstarter/ui/activities/NotificationsActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/NotificationsViewModel.kt
Labels: bug 🐛

#469 Logged out drawer header updates
  app/src/main/res/drawable/ic_face.xml
  app/src/main/res/layout/discovery_drawer_logged_out_view.xml
Labels: UI 🎨

#470 Drawer divider and header updates
  app/src/main/java/com/kickstarter/ui/adapters/DiscoveryDrawerAdapter.java
  app/src/main/java/com/kickstarter/ui/viewholders/discoverydrawer/HeaderViewHolder.kt
  app/src/main/res/layout/discovery_drawer_header.xml
  app/src/main/res/layout/discovery_drawer_logged_out_view.xml
  app/src/main/res/layout/horizontal_line_1dp_view.xml
Labels: UI 🎨

#471 Logged in drawer updates
  app/src/main/res/layout/discovery_drawer_logged_in_view.xml
Labels: Investment Day! 💰, UI 🎨

#472 Drawer item updates
  app/src/main/java/com/kickstarter/libs/utils/DiscoveryDrawerUtils.java
  app/src/main/java/com/kickstarter/ui/adapters/DiscoveryDrawerAdapter.java
  app/src/main/java/com/kickstarter/ui/viewholders/discoverydrawer/ChildFilterViewHolder.java
  app/src/main/java/com/kickstarter/ui/viewholders/discoverydrawer/ParentFilterViewHolder.java
  app/src/main/java/com/kickstarter/ui/viewholders/discoverydrawer/TopFilterViewHolder.java
  app/src/main/res/drawable/drawer_selected.xml
  app/src/main/res/layout/discovery_drawer_child_filter_view.xml
  app/src/main/res/layout/discovery_drawer_header.xml
  app/src/main/res/layout/discovery_drawer_logged_in_view.xml
  app/src/main/res/layout/discovery_drawer_logged_out_view.xml
  app/src/main/res/layout/discovery_drawer_parent_filter_view.xml
  app/src/main/res/layout/discovery_drawer_top_filter_view.xml
  app/src/main/res/values/colors.xml
Labels: Investment Day! 💰, UI 🎨

#474 Drawer width
  app/src/main/res/layout/discovery_layout.xml
Labels: UI 🎨

#468 Koala Settings Event Name Update
  app/src/main/java/com/kickstarter/libs/Koala.java
  app/src/main/java/com/kickstarter/viewmodels/NewCardFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/PaymentMethodsViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/NewCardFragmentViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/PaymentMethodsViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/SettingsViewModelTest.kt
Labels: maintenance 🗜

#477 Settings transitions
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/ui/activities/AccountActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ChangeEmailActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ChangePasswordActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/CreatePasswordActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.java
  app/src/main/java/com/kickstarter/ui/activities/EditProfileActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/HelpSettingsActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/NewsletterActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/NotificationsActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/PaymentMethodsSettingsActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/PrivacyActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectNotificationSettingsActivity.java
  app/src/main/java/com/kickstarter/ui/activities/SettingsActivity.kt
  app/src/main/res/values/styles.xml
Labels: UI 🎨

#476 Discovery user refresh bug 🐜
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java
Labels: bug 🐛

#480 [Bug] Add New Card Fragment Bug
  app/src/main/java/com/kickstarter/ui/fragments/NewCardFragment.kt
Labels: bug 🐛

#479 🐛payment method UI bug
  app/src/main/java/com/kickstarter/ui/fragments/NewCardFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/NewCardFragmentViewModel.kt
  app/src/main/res/layout/activity_account.xml
  app/src/main/res/layout/activity_change_email.xml
  app/src/main/res/layout/activity_change_password.xml
  app/src/main/res/layout/activity_create_password.xml
  app/src/main/res/layout/activity_settings_payment_methods.xml
  app/src/main/res/layout/fragment_new_card.xml
  app/src/test/java/com/kickstarter/viewmodels/NewCardFragmentViewModelTest.kt
Labels: UI 🎨, bug 🐛

#478 ✨drawer icons
  app/src/internal/res/layout/internal_tools_button_view.xml
  app/src/main/java/com/kickstarter/ui/viewholders/discoverydrawer/ChildFilterViewHolder.java
  app/src/main/java/com/kickstarter/ui/viewholders/discoverydrawer/LoggedOutViewHolder.java
  app/src/main/java/com/kickstarter/ui/viewholders/discoverydrawer/TopFilterViewHolder.java
  app/src/main/res/drawable/ic_dashboard.xml
  app/src/main/res/drawable/ic_help.xml
  app/src/main/res/drawable/ic_internal_tools.xml
  app/src/main/res/drawable/ic_label.xml
  app/src/main/res/drawable/ic_label_green.xml
  app/src/main/res/drawable/ic_person.xml
  app/src/main/res/drawable/ic_settings.xml
  app/src/main/res/drawable/icon__bolt.xml
  app/src/main/res/layout/discovery_drawer_child_filter_view.xml
  app/src/main/res/layout/discovery_drawer_logged_in_view.xml
  app/src/main/res/layout/discovery_drawer_logged_out_view.xml
  app/src/main/res/values/styles.xml
Labels: UI 🎨

#481 [Release 1.11.0] - Bumped internal and external
  app/external_version_name.txt
  app/internal_version_name.txt
  app/src/main/assets/json/server-config.json
  app/src/main/res/values-es/strings_i18n.xml
Labels: release 🚀

#482 [Maintenance]- Updated external version code and Fastlane report
  app/external_version_code.txt
  fastlane/report.xml
Labels: maintenance 🗜

#483 Change email design updates
  app/src/main/java/com/kickstarter/ui/activities/ChangeEmailActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/ChangeEmailViewModel.kt
  app/src/main/res/color/button_alternate.xml
  app/src/main/res/color/button_alternate_ripple.xml
  app/src/main/res/color/button_alternate_text.xml
  app/src/main/res/layout/activity_change_email.xml
  app/src/main/res/values/styles.xml
Labels: UI 🎨, settings ⚙️

#484 Discovery Toolbar content description
  app/src/main/java/com/kickstarter/ui/toolbars/DiscoveryToolbar.java
  app/src/main/res/drawable/ic_menu.xml
  app/src/main/res/layout/discovery_toolbar.xml
Labels: UI 🎨

#486 [Bug]- Removed Trello Email for Internal Tools
  app/src/internal/java/com/kickstarter/ui/activities/InternalToolsActivity.java
  app/src/internal/res/layout/internal_tools_layout.xml
  app/src/main/java/com/kickstarter/libs/utils/Secrets.java.example
Labels: bug 🐛, maintenance 🗜

#490 Removing parent activity metadata for Android 4.0
  app/src/main/AndroidManifest.xml
Labels: maintenance 🗜

#489 Removing unnecessary UnusedAttribute
  app/src/main/AndroidManifest.xml
  app/src/main/res/layout/discovery_toolbar.xml
  app/src/main/res/layout/empty_activity_feed_view.xml
  app/src/main/res/layout/login_toolbar.xml
  app/src/main/res/layout/message_thread_view.xml
  app/src/main/res/layout/message_threads_toolbar.xml
  app/src/main/res/layout/message_view.xml
  app/src/main/res/layout/messages_layout.xml
  app/src/main/res/layout/messages_toolbar.xml
  app/src/main/res/layout/profile_toolbar.xml
  app/src/main/res/layout/project_metadata_view.xml
  app/src/main/res/layout/project_search_result_view.xml
  app/src/main/res/layout/project_toolbar.xml
Labels: maintenance 🗜

#475 Moving internal tools, settings, creator dashboard and activity into new drawer section.
  app/src/internal/res/layout/internal_tools_button_view.xml
  app/src/main/java/com/kickstarter/ui/activities/CreatorDashboardActivity.java
  app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.java
  app/src/main/java/com/kickstarter/ui/activities/HelpSettingsActivity.kt
  app/src/main/java/com/kickstarter/ui/toolbars/DiscoveryToolbar.java
  app/src/main/java/com/kickstarter/ui/viewholders/discoverydrawer/ChildFilterViewHolder.java
  app/src/main/java/com/kickstarter/ui/viewholders/discoverydrawer/LoggedInViewHolder.java
  app/src/main/java/com/kickstarter/ui/viewholders/discoverydrawer/LoggedOutViewHolder.java
  app/src/main/java/com/kickstarter/ui/viewholders/discoverydrawer/TopFilterViewHolder.java
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java
  app/src/main/res/drawable/ic_dashboard.xml
  app/src/main/res/drawable/ic_help.xml
  app/src/main/res/drawable/ic_internal_tools.xml
  app/src/main/res/drawable/ic_label.xml
  app/src/main/res/drawable/ic_label_green.xml
  app/src/main/res/drawable/ic_person.xml
  app/src/main/res/drawable/ic_settings.xml
  app/src/main/res/drawable/icon__bolt.xml
  app/src/main/res/layout/creator_dashboard_toolbar.xml
  app/src/main/res/layout/dashboard_funding_view.xml
  app/src/main/res/layout/discovery_drawer_child_filter_view.xml
  app/src/main/res/layout/discovery_drawer_logged_in_view.xml
  app/src/main/res/layout/discovery_drawer_logged_out_view.xml
  app/src/main/res/layout/discovery_drawer_parent_filter_view.xml
  app/src/main/res/layout/discovery_drawer_top_filter_view.xml
  app/src/main/res/layout/discovery_toolbar.xml
  app/src/main/res/layout/horizontal_line_1dp_view.xml
  app/src/main/res/layout/internal_tools_button_view.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.java
Labels: UI 🎨, feature ✨

#493 [Release 1.12.0] - Bumped internal and external
  app/external_version_name.txt
  app/internal_version_name.txt
  app/src/main/assets/json/server-config.json
  app/src/main/res/values-ja/strings_i18n.xml
Labels: release 🚀

#494 [Maintenance]- Updated external version code and Fastlane report
  app/external_version_code.txt
  fastlane/report.xml
Labels: maintenance 🗜
