Repository kickstarter/android-oss, pull requests merged in 2019-07, with the labels that each got.

#564 Use new Facebook color and glyph
  app/src/main/res/drawable/ic_social_facebook.xml
  app/src/main/res/drawable/ic_social_facebook_share.xml
  app/src/main/res/layout-land/login_tout_layout.xml
  app/src/main/res/layout/login_tout_layout.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/styles.xml
Labels: UI 🎨

#567 Reward sheet titles
  app/src/main/java/com/kickstarter/libs/utils/ProjectViewUtils.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
  app/src/main/res/layout/activity_project.xml
  app/src/main/res/layout/fragment_pledge.xml
  app/src/main/res/layout/fragment_rewards.xml
  app/src/test/java/com/kickstarter/libs/utils/ProjectViewUtilsTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Labels: UI 🎨

#565 Cancel pledge
  app/src/main/AndroidManifest.xml
  app/src/main/graphql/checkout.graphql
  app/src/main/graphql/schema.json
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/models/Backing.java
  app/src/main/java/com/kickstarter/services/ApolloClientType.kt
  app/src/main/java/com/kickstarter/services/KSApolloClient.kt
  app/src/main/java/com/kickstarter/ui/ArgumentsKey.java
  app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
  app/src/main/java/com/kickstarter/ui/fragments/CancelPledgeFragment.kt
  app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
  app/src/main/java/com/kickstarter/ui/fragments/RewardsFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/CancelPledgeViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
  app/src/main/res/anim/slide_down.xml
  app/src/main/res/anim/slide_up.xml
  app/src/main/res/layout/activity_project.xml
  app/src/main/res/layout/fragment_cancel_pledge.xml
  app/src/main/res/layout/item_reward.xml
  app/src/main/res/layout/project_layout.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/dimens.xml
  app/src/test/java/com/kickstarter/viewmodels/CancelPledgeViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Labels: feature ✨

#566 Dependency sweep
  app/build.gradle
Labels: Investment Day! 💰, maintenance 🗜

#568 🔒Updating mini_magick vulnerability
  Gemfile.lock
Labels: maintenance 🗜

#571 [🐜🕷] Mark as received bug, View pledge bug
  app/src/main/java/com/kickstarter/services/apiresponses/MessageThreadEnvelope.java
  app/src/main/java/com/kickstarter/viewmodels/BackingViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/MessagesViewModel.java
  app/src/main/res/layout/backing_layout.xml
  app/src/test/java/com/kickstarter/viewmodels/BackingViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/MessagesViewModelTest.java
Labels: bug 🐛

#576 Set maximum width on button
  app/src/main/res/layout/messages_backing_info_view.xml
Labels: UI 🎨

#570 [🔢] Pledge input
  app/src/main/AndroidManifest.xml
  app/src/main/assets/json/server-config.json
  app/src/main/java/com/kickstarter/extensions/ActivityExt.kt
  app/src/main/java/com/kickstarter/libs/KSCurrency.java
  app/src/main/java/com/kickstarter/libs/utils/NumberUtils.java
  app/src/main/java/com/kickstarter/libs/utils/ProjectViewUtils.kt
  app/src/main/java/com/kickstarter/libs/utils/RewardViewUtils.kt
  app/src/main/java/com/kickstarter/libs/utils/StringUtils.java
  app/src/main/java/com/kickstarter/libs/utils/ViewUtils.java
  app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
  app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/NativeCheckoutRewardViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/main/res/drawable/background_dialog.xml
  app/src/main/res/drawable/pledge_amounts_loading_states.xml
  app/src/main/res/layout/fragment_new_card.xml
  app/src/main/res/layout/fragment_pledge.xml
  app/src/main/res/layout/fragment_pledge_section_delivery.xml
  app/src/main/res/layout/fragment_pledge_section_payment.xml
  app/src/main/res/layout/fragment_pledge_section_pledge_amount.xml
  app/src/main/res/layout/fragment_pledge_section_shipping.xml
  app/src/main/res/layout/fragment_pledge_section_total.xml
  app/src/main/res/values-de/strings_i18n.xml
  app/src/main/res/values-es/strings_i18n.xml
  app/src/main/res/values-fr/strings_i18n.xml
  app/src/main/res/values-ja/strings_i18n.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings_i18n.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/com/kickstarter/libs/utils/NumberUtilsTest.java
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Labels: feature ✨
