Repository kickstarter/android-oss, pull requests merged in 2019-03, with the labels that each got.

#495 [UI Fix] - Ripple of profile section in logged in drawer layout goes outside of the bounds of the view.
  app/src/main/res/layout/discovery_drawer_logged_in_view.xml
Labels: UI 🎨

#496 [Maintenance] - Update Android currency preferences alert copy
  app/src/main/assets/json/server-config.json
  app/src/main/java/com/kickstarter/ui/activities/AccountActivity.kt
  app/src/main/res/values-de/strings_i18n.xml
  app/src/main/res/values-es/strings_i18n.xml
  app/src/main/res/values-fr/strings_i18n.xml
  app/src/main/res/values-ja/strings_i18n.xml
  app/src/main/res/values/strings_i18n.xml
Labels: UI 🎨, maintenance 🗜

#498 updated the schema from kickstarter master
  app/src/main/graphql/schema.json
Labels: infrastructure 👷‍♀️

#499 🐛change email crash
  app/src/main/java/com/kickstarter/viewmodels/ChangeEmailViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ChangeEmailViewModelTest.kt
Labels: bug 🐛

#500 Allow backers to add a UnionPay card in Account Settings
  app/src/main/java/com/kickstarter/viewmodels/NewCardFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/PaymentMethodsViewHolderViewModel.kt
  app/src/main/res/drawable/union_pay_md.xml
  app/src/test/java/com/kickstarter/viewmodels/NewCardFragmentViewModelTest.kt
Labels: feature ✨

#501 Added Toggle Feature Flag for enabling Horizontal Rewards
  app/src/internal/AndroidManifest.xml
  app/src/internal/java/com/kickstarter/ApplicationComponent.java
  app/src/internal/java/com/kickstarter/ui/activities/FeatureFlagActivity.kt
  app/src/internal/java/com/kickstarter/ui/activities/InternalToolsActivity.java
  app/src/internal/res/layout/activity_feature_flag.xml
  app/src/internal/res/layout/internal_tools_layout.xml
  app/src/main/java/com/kickstarter/ApplicationModule.java
  app/src/main/java/com/kickstarter/libs/Environment.java
  app/src/main/java/com/kickstarter/libs/FeatureKey.java
  app/src/main/java/com/kickstarter/libs/qualifiers/HorizontalRewardsPreference.kt
  app/src/main/res/layout/feature_flag_toolbar.xml
  app/src/main/res/values/strings.xml
Labels: feature ✨
