Repository kickstarter/android-oss, pull requests merged in 2019-01, with the labels that each got.

#435 [Bug Fix] - Android 8 + Samsung orientation theme fix
  app/src/main/AndroidManifest.xml
  app/src/main/res/values/styles.xml
  fastlane/report.xml
Labels: bug

#447 [🚮] Removing deprecated calls to pipeErrorsTo in Log In
  app/src/main/java/com/kickstarter/viewmodels/LoginViewModel.kt
Labels: Investment Day!

#448 [🚮] Removing deprecated calls to pipeErrorsTo in Reset Password
  app/src/main/java/com/kickstarter/viewmodels/ResetPasswordViewModel.kt
Labels: Investment Day!

#449 [🚮] Removing deprecated calls to pipeErrorsTo in Notifications
  app/src/main/java/com/kickstarter/ui/activities/NotificationsActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/NotificationsViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/NotificationsViewModelTest.kt
Labels: Investment Day!

#454 [💳] Only allowing Kickstarter accepted card types to be saved
  app/src/main/assets/json/server-config.json
  app/src/main/java/com/kickstarter/ui/fragments/NewCardFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/NewCardFragmentViewModel.kt
  app/src/main/res/layout/fragment_new_card.xml
  app/src/main/res/values-de/strings_i18n.xml
  app/src/main/res/values-es/strings_i18n.xml
  app/src/main/res/values-fr/strings_i18n.xml
  app/src/main/res/values-ja/strings_i18n.xml
  app/src/main/res/values/strings_i18n.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/com/kickstarter/viewmodels/NewCardFragmentViewModelTest.kt
Labels: Settings

#451 [Enhancement] - Pledge Activity Digest
  app/src/main/assets/json/server-config.json
  app/src/main/java/com/kickstarter/models/User.java
  app/src/main/java/com/kickstarter/services/ApiClient.java
  app/src/main/java/com/kickstarter/services/apirequests/SettingsBody.java
  app/src/main/java/com/kickstarter/ui/activities/NotificationsActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/NotificationsViewModel.kt
  app/src/main/res/layout/activity_notifications.xml
  app/src/main/res/values-de/strings_i18n.xml
  app/src/main/res/values-es/strings_i18n.xml
  app/src/main/res/values-fr/strings_i18n.xml
  app/src/main/res/values-ja/strings_i18n.xml
  app/src/main/res/values/strings_i18n.xml
  app/src/test/java/com/kickstarter/viewmodels/NotificationsViewModelTest.kt
Labels: enhancement
