Repository kickstarter/android-oss, pull requests merged in 2020-11, with the labels that each got.

#1027 NT-1432 && NT-1466: Update gradle plugin && Update apollo library
  app/build.gradle
  app/internal_version_code.txt
  app/internal_version_name.txt
  app/src/main/java/com/kickstarter/libs/graphql/DateAdapter.kt
  app/src/main/java/com/kickstarter/libs/graphql/DateTimeAdapter.kt
  app/src/main/java/com/kickstarter/libs/graphql/EmailAdapter.kt
  app/src/main/java/com/kickstarter/libs/graphql/Iso8601DateTimeAdapter.kt
  app/src/main/java/com/kickstarter/services/KSApolloClient.kt
  app/src/main/java/com/kickstarter/services/firebase/MessageService.java
  app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/CancelPledgeViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardsFragmentViewModel.kt
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: maintenance 🗜

#1029 NT-1634: Persist reward delivered checkbox
  app/src/main/java/com/kickstarter/models/Backing.java
  app/src/main/java/com/kickstarter/services/KSApolloClient.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/BackingFragmentViewModelTest.kt
Labels: bug 🐛

#1028 NT-1643:Firebase Performance monitor
  app/build.gradle
  app/internal_version_code.txt
  app/src/main/AndroidManifest.xml
  build.gradle
Labels: maintenance 🗜

#1030 [NT-1646][NT-1647]:Email verification flow|Skip Link feature flags
  app/src/main/java/com/kickstarter/libs/TrackingClient.kt
  app/src/main/java/com/kickstarter/libs/utils/ConfigUtils.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/ConfigExtension.kt
  app/src/test/java/com/kickstarter/libs/MockTrackingClient.java
  app/src/test/java/com/kickstarter/libs/utils/ConfigUtilsTest.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/ConfigExtensionTest.kt
Labels: feature ✨, maintenance 🗜, refactor 🛠

#1032 NT-1654:Detect user validated flow
  app/src/main/java/com/kickstarter/extensions/EditTextExt.kt
  app/src/main/java/com/kickstarter/libs/BaseActivity.java
  app/src/main/java/com/kickstarter/libs/utils/LoginHelper.kt
  app/src/main/java/com/kickstarter/mock/factories/UserFactory.java
  app/src/main/java/com/kickstarter/models/User.java
  app/src/main/java/com/kickstarter/models/extensions/UserExt.kt
  app/src/main/java/com/kickstarter/ui/activities/AccountActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ChangeEmailActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ChangePasswordActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/CreatePasswordActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/LoginActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/MessageCreatorActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/PaymentMethodsSettingsActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectNotificationSettingsActivity.java
  app/src/main/java/com/kickstarter/ui/activities/ResetPasswordActivity.kt
  app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt
  app/src/main/java/com/kickstarter/ui/extensions/EditTextExt.kt
  app/src/main/java/com/kickstarter/ui/extensions/SnackbarExt.kt
  app/src/main/java/com/kickstarter/ui/extensions/ToastExt.kt
  app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
  app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
  app/src/main/java/com/kickstarter/ui/fragments/CancelPledgeFragment.kt
  app/src/main/java/com/kickstarter/ui/fragments/NewCardFragment.kt
  app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/LoginViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/NewsletterViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/SignupViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/ThanksViewModel.java
  app/src/test/java/com/kickstarter/libs/utils/extensions/UserExtensionTest.kt
  app/src/test/java/com/kickstarter/viewmodels/LoginViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/SignupViewModelTest.java
Labels: feature ✨, refactor 🛠

#1033 NT-1648: Email Verification Interstitial UI
  app/src/internal/java/com/kickstarter/ui/activities/InternalToolsActivity.java
  app/src/internal/res/layout/internal_tools_layout.xml
  app/src/main/java/com/kickstarter/ui/fragments/EmailVerificationInterstitialFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/EmailVerificationInterstitialFragmentViewModel.kt
  app/src/main/res/drawable/ic_email.xml
  app/src/main/res/layout/fragment_email_verification_interstitial.xml
  app/src/main/res/values/strings_i18n.xml
Labels: feature ✨

#1034 [NT-1638]: Override equals operator for: Location, User, AccessTokenEnvelope
  app/src/main/java/com/kickstarter/libs/utils/UserUtils.java
  app/src/main/java/com/kickstarter/models/Location.java
  app/src/main/java/com/kickstarter/models/User.java
  app/src/main/java/com/kickstarter/models/extensions/UserExt.kt
  app/src/main/java/com/kickstarter/services/apiresponses/AccessTokenEnvelope.java
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/NewsletterViewModel.kt
  app/src/test/java/com/kickstarter/libs/utils/UserUtilsTest.java
  app/src/test/java/com/kickstarter/models/AccessTokenEnvelopeTest.kt
  app/src/test/java/com/kickstarter/models/LocationTest.kt
  app/src/test/java/com/kickstarter/models/UserTest.kt
Labels: maintenance 🗜, refactor 🛠

#1036 NT-1652: Connect login flow to interstitial
  app/src/internal/java/com/kickstarter/ui/activities/InternalToolsActivity.java
  app/src/main/java/com/kickstarter/mock/factories/UserFactory.java
  app/src/main/java/com/kickstarter/ui/ArgumentsKey.java
  app/src/main/java/com/kickstarter/ui/activities/LoginActivity.kt
  app/src/main/java/com/kickstarter/ui/fragments/EmailVerificationInterstitialFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/LoginViewModel.kt
  app/src/main/res/layout/login_layout.xml
  app/src/test/java/com/kickstarter/viewmodels/LoginViewModelTest.kt
Labels: feature ✨

#1037 NT-1653: Create account flow
  app/src/main/java/com/kickstarter/libs/utils/LoginHelper.kt
  app/src/main/java/com/kickstarter/ui/activities/LoginActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/SignupActivity.java
  app/src/main/java/com/kickstarter/viewmodels/SignupViewModel.java
  app/src/main/res/layout/signup_layout.xml
  app/src/test/java/com/kickstarter/viewmodels/SignupViewModelTest.java
Labels: feature ✨

#1039 NT-1648: Update copy and fix interstitial screen copy
  app/external_version_code.txt
  app/external_version_name.txt
  app/src/internal/java/com/kickstarter/ui/activities/InternalToolsActivity.java
  app/src/main/java/com/kickstarter/viewmodels/EmailVerificationInterstitialFragmentViewModel.kt
  app/src/main/res/values/strings_i18n.xml
Labels: bug 🐛, copy 📝

#1040 NT-1651: Skip button on Interstitial
  app/src/internal/java/com/kickstarter/ui/activities/InternalToolsActivity.java
  app/src/main/java/com/kickstarter/libs/utils/LoginHelper.kt
  app/src/main/java/com/kickstarter/mock/factories/AccessTokenEnvelopeFactory.kt
  app/src/main/java/com/kickstarter/ui/ArgumentsKey.java
  app/src/main/java/com/kickstarter/ui/activities/LoginActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/SignupActivity.java
  app/src/main/java/com/kickstarter/ui/fragments/Callbacks.kt
  app/src/main/java/com/kickstarter/ui/fragments/EmailVerificationInterstitialFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/EmailVerificationInterstitialFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/LoginViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/SignupViewModel.java
  app/src/main/res/layout/fragment_email_verification_interstitial.xml
  app/src/test/java/com/kickstarter/viewmodels/EmailVerificationInterstitialFragmentViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/LoginViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/SignupViewModelTest.java
Labels: feature ✨

#1041 NT-1595: Creator view adjustments
  app/src/main/graphql/fragments.graphql
  app/src/main/java/com/kickstarter/services/KSApolloClient.kt
  app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
  app/src/main/res/layout/backing_toolbar.xml
  app/src/test/java/com/kickstarter/viewmodels/BackingFragmentViewModelTest.kt
Labels: bug 🐛, refactor 🛠

#1042 NT-1649: The user can resend the email from Interstitial
  app/src/main/java/com/kickstarter/ui/fragments/EmailVerificationInterstitialFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/EmailVerificationInterstitialFragmentViewModel.kt
  app/src/main/res/layout/fragment_email_verification_interstitial.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/kickstarter/viewmodels/EmailVerificationInterstitialFragmentViewModelTest.kt
Labels: UI 🎨, feature ✨

#1043 NT-1673: Deep Linking from Email Verification
  app/src/internal/java/com/kickstarter/ui/activities/InternalToolsActivity.java
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/ApplicationModule.java
  app/src/main/java/com/kickstarter/libs/Environment.java
  app/src/main/java/com/kickstarter/libs/utils/LoginHelper.kt
  app/src/main/java/com/kickstarter/services/KSUri.java
  app/src/main/java/com/kickstarter/ui/ArgumentsKey.java
  app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.java
  app/src/main/java/com/kickstarter/ui/activities/LoginActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/SignupActivity.java
  app/src/main/java/com/kickstarter/ui/fragments/EmailVerificationInterstitialFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/EmailVerificationInterstitialFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/LoginViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/SignupViewModel.java
  app/src/main/res/layout/discovery_layout.xml
  app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/EmailVerificationInterstitialFragmentViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/LoginViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/SignupViewModelTest.java
Labels: feature ✨, refactor 🛠

#1044 NT-1648: Interstitial Screen UI
  app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.java
  app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt
  app/src/main/java/com/kickstarter/ui/extensions/SnackbarExt.kt
  app/src/main/java/com/kickstarter/ui/fragments/EmailVerificationInterstitialFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/EmailVerificationInterstitialFragmentViewModel.kt
  app/src/main/res/values/colors.xml
  app/src/test/java/com/kickstarter/viewmodels/EmailVerificationInterstitialFragmentViewModelTest.kt
Labels: UI 🎨
