Repository kickstarter/android-oss, pull requests merged in 2020-09, with the labels that each got.

#964 NT-1489: Fix Crash when a user views their Account
  app/src/main/java/com/kickstarter/ui/activities/AccountActivity.kt
Labels: bug 🐛

#967 NT-1411: Crash on Creator Pledge Screen
  app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
Labels: bug 🐛

#966 NT-1488:Crash on search
  app/src/main/java/com/kickstarter/viewmodels/SearchViewModel.java
  app/src/test/java/com/kickstarter/viewmodels/SearchViewModelTest.java
Labels: bug 🐛

#968 RC-2.7.2
  app/external_version_code.txt
  app/external_version_name.txt
  app/internal_version_code.txt
  app/internal_version_name.txt
  app/src/main/java/com/kickstarter/ui/activities/AccountActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/SearchViewModel.java
  app/src/test/java/com/kickstarter/viewmodels/SearchViewModelTest.java
Labels: bug 🐛, release 🚀

#986 Android NT-1442: Hide shipping selector on network error
  app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModelTest.kt
Labels: UI 🎨

#997 NT-1442:
  app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
  app/src/main/res/values/strings_i18n.xml
Labels: copy 📝

#1000 NT-1530: Add PLN Currency to the User's Settings Page
  app/src/main/assets/json/server-config.json
  app/src/main/java/com/kickstarter/ui/activities/AccountActivity.kt
  app/src/main/res/values-de/strings_i18n.xml
  app/src/main/res/values-es/strings_i18n.xml
  app/src/main/res/values-fr/strings_i18n.xml
  app/src/main/res/values-ja/strings_i18n.xml
  app/src/main/res/values/strings_i18n.xml
Labels: feature ✨
