Repository kickstarter/android-oss, pull requests merged in 2020-04, with the labels that each got.

#806 [🆕] Replacing FirebaseJobDispatcher with WorkManager
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/ApplicationGraph.java
  app/src/main/java/com/kickstarter/libs/DeviceRegistrar.java
  app/src/main/java/com/kickstarter/libs/DeviceRegistrar.kt
  app/src/main/java/com/kickstarter/libs/KoalaTrackingClient.java
  app/src/main/java/com/kickstarter/libs/LakeTrackingClient.kt
  app/src/main/java/com/kickstarter/libs/TrackingClient.kt
  app/src/main/java/com/kickstarter/libs/TrackingClientType.java
  app/src/main/java/com/kickstarter/libs/utils/WorkUtils.kt
  app/src/main/java/com/kickstarter/mock/services/MockApiClient.java
  app/src/main/java/com/kickstarter/services/ApiClient.java
  app/src/main/java/com/kickstarter/services/ApiClientType.java
  app/src/main/java/com/kickstarter/services/ApiService.java
  app/src/main/java/com/kickstarter/services/KoalaBackgroundService.kt
  app/src/main/java/com/kickstarter/services/KoalaWorker.kt
  app/src/main/java/com/kickstarter/services/LakeBackgroundService.kt
  app/src/main/java/com/kickstarter/services/LakeWorker.kt
  app/src/main/java/com/kickstarter/services/TrackingWorker.kt
  app/src/main/java/com/kickstarter/services/firebase/Dispatcher.kt
  app/src/main/java/com/kickstarter/services/firebase/RegisterService.java
  app/src/main/java/com/kickstarter/services/firebase/RegisterTokenWorker.kt
  app/src/main/java/com/kickstarter/services/firebase/TokenListenerService.java
  app/src/main/java/com/kickstarter/services/firebase/UnregisterService.java
  app/src/main/java/com/kickstarter/services/firebase/UnregisterTokenWorker.kt
  app/src/main/java/com/kickstarter/ui/IntentKey.java
  app/src/test/java/com/kickstarter/KSRobolectricTestCase.java
  app/src/test/java/com/kickstarter/libs/KoalaTest.kt
  app/src/test/java/com/kickstarter/libs/LakeTest.kt
  app/src/test/java/com/kickstarter/libs/MockTrackingClient.java
Labels: maintenance 🗜

#807 [👋🏾] NT-896 Removing webview checkout
  app/src/internal/java/com/kickstarter/ui/activities/FeatureFlagsActivity.kt
  app/src/internal/res/layout/activity_feature_flags.xml
  app/src/internal/res/layout/item_feature_flag_override.xml
  app/src/main/java/com/kickstarter/ApplicationModule.java
  app/src/main/java/com/kickstarter/libs/Environment.java
  app/src/main/java/com/kickstarter/libs/FeatureKey.java
  app/src/main/java/com/kickstarter/libs/qualifiers/NativeCheckoutPreference.kt
  app/src/main/java/com/kickstarter/libs/utils/ProjectViewUtils.kt
  app/src/main/java/com/kickstarter/ui/IntentKey.java
  app/src/main/java/com/kickstarter/ui/SharedPreferenceKey.java
  app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ThanksActivity.java
  app/src/main/java/com/kickstarter/ui/adapters/ProjectAdapter.java
  app/src/main/java/com/kickstarter/ui/adapters/RewardsAdapter.kt
  app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
  app/src/main/java/com/kickstarter/ui/fragments/RewardsFragment.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ProjectViewHolder.java
  app/src/main/java/com/kickstarter/ui/viewholders/RewardViewHolder.java
  app/src/main/java/com/kickstarter/ui/viewholders/RewardViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectHolderViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/ThanksViewModel.java
  app/src/main/res/layout-land/project_main_layout.xml
  app/src/main/res/layout/activity_project.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/kickstarter/libs/utils/ConfigUtilsTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectHolderViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardViewHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/ThanksViewModelTest.java
Labels: maintenance 🗜

#810 [⛔️] NT-1057 Automatically expanding pledge sheet when fixing pledge
  app/src/main/java/com/kickstarter/ui/IntentKey.java
  app/src/main/java/com/kickstarter/ui/activities/ActivityFeedActivity.java
  app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Labels: feature ✨

#813 [⛔️] NT-1080 Pledge screen UI when fixing an errored backing's payment
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Labels: feature ✨

#812 [💳] NT-1079 Enabling reselecting failed payment method
  app/src/main/java/com/kickstarter/viewmodels/RewardCardViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardCardViewHolderViewModelTest.kt
Labels: feature ✨

#811 [💳] NT-1078 Showing failed indicator icon on failed payment method
  app/src/main/java/com/kickstarter/ui/viewholders/RewardCardViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardCardViewHolderViewModel.kt
  app/src/main/res/layout/reward_card_details.xml
  app/src/test/java/com/kickstarter/viewmodels/RewardCardViewHolderViewModelTest.kt
Labels: UI 🎨, feature ✨

#814 [🚮] NT-966 Deleting CheckoutActivity
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/ui/activities/CheckoutActivity.java
  app/src/main/java/com/kickstarter/viewmodels/CheckoutViewModel.java
  app/src/main/res/layout/checkout_layout.xml
  app/src/main/res/layout/checkout_toolbar.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/com/kickstarter/viewmodels/CheckoutViewModelTest.java
Labels: maintenance 🗜

#815 [🚮] NT-1082 Deleting Android Pay references
  app/src/main/java/com/kickstarter/libs/utils/Secrets.java.example
  app/src/main/java/com/kickstarter/services/KSUri.java
Labels: maintenance 🗜

#816 [📄] NT-802 Updating no reward copy in Pledge screen
  app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/main/res/layout/fragment_pledge_section_reward_summary.xml
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Labels: copy 📝

#817 [🦶🏾] NT-1104 Add Pledge screen footer
  app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
  app/src/main/res/layout/fragment_pledge.xml
  app/src/main/res/layout/fragment_pledge_section_footer.xml
  app/src/main/res/layout/fragment_pledge_section_total.xml
Labels: UI 🎨

#819 [⛔️] NT-1116 Errored backings deadline warning copy
  app/src/main/java/com/kickstarter/ui/viewholders/ErroredBackingViewHolder.kt
  app/src/main/res/values-de/strings_i18n.xml
  app/src/main/res/values-es/strings_i18n.xml
  app/src/main/res/values-fr/strings_i18n.xml
  app/src/main/res/values-ja/strings_i18n.xml
  app/src/main/res/values/strings_i18n.xml
Labels: copy 📝

#820 [🗣] NT-1117 Errored backings icon a11y
  app/src/main/res/layout/item_errored_backing.xml
  app/src/main/res/values-de/strings_i18n.xml
  app/src/main/res/values-es/strings_i18n.xml
  app/src/main/res/values-fr/strings_i18n.xml
  app/src/main/res/values-ja/strings_i18n.xml
  app/src/main/res/values/strings_i18n.xml
Labels: a11y ♿️

#821 [⬇] NT-1120 Vertical payment methods in Pledge screen
  app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
  app/src/main/java/com/kickstarter/ui/itemdecorations/RewardCardItemDecoration.kt
  app/src/main/res/layout/item_reward_add_card.xml
  app/src/main/res/layout/item_reward_credit_card.xml
  app/src/main/res/layout/item_reward_placeholder_card.xml
  app/src/main/res/values/dimens.xml
Labels: UI 🎨

#823 [🛒] NT-1105 Kickstarter is not a store redesign
  app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/main/res/drawable/ic_not_a_store.xml
  app/src/main/res/layout/fragment_pledge.xml
  app/src/main/res/layout/fragment_pledge_section_accountability.xml
  app/src/main/res/layout/fragment_pledge_section_reward_summary.xml
  app/src/main/res/values-de/strings_i18n.xml
  app/src/main/res/values-es/strings_i18n.xml
  app/src/main/res/values-fr/strings_i18n.xml
  app/src/main/res/values-ja/strings_i18n.xml
  app/src/main/res/values/strings_i18n.xml
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Labels: UI 🎨

#824 [💳] NT-1122 Initial card selection
  app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
  app/src/main/java/com/kickstarter/ui/viewholders/RewardCardUnselectedViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/BaseRewardCardViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardCardUnselectedViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardLoadingCardViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardCardSelectedViewHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardCardUnselectedViewHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardLoadingCardViewHolderViewModelTest.kt
Labels: feature ✨, refactor 🛠

#825 [⏳] NT-1124 Loading state for payment methods
  app/src/main/res/layout/item_reward_placeholder_card.xml
  app/src/main/res/layout/loading_placeholder_body.xml
  app/src/main/res/layout/loading_placeholder_caption_2.xml
Labels: UI 🎨

#828 [➕] NT-1125 New card CTA
  app/src/main/res/drawable/circle_accent_alpha_20.xml
  app/src/main/res/drawable/ic_add_rounded.xml
  app/src/main/res/layout/item_add_card.xml
  app/src/main/res/values-de/strings_i18n.xml
  app/src/main/res/values-es/strings_i18n.xml
  app/src/main/res/values-fr/strings_i18n.xml
  app/src/main/res/values-ja/strings_i18n.xml
  app/src/main/res/values/strings_i18n.xml
Labels: copy 📝

#826 [💳] NT-1123 Last four digits copy
  app/src/main/java/com/kickstarter/models/StoredCard.kt
  app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
  app/src/main/java/com/kickstarter/ui/viewholders/RewardCardSelectedViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/RewardCardUnselectedViewHolder.kt
  app/src/main/res/layout/reward_card_details.xml
  app/src/main/res/values/strings.xml
Labels: bug 🐛, copy 📝

#827 [💳] NT-1123 Card not allowed copy
  app/src/main/java/com/kickstarter/ui/viewholders/RewardCardUnselectedViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardCardUnselectedViewHolderViewModel.kt
  app/src/main/res/layout/item_reward_unselected_card.xml
  app/src/main/res/values-de/strings_i18n.xml
  app/src/main/res/values-es/strings_i18n.xml
  app/src/main/res/values-fr/strings_i18n.xml
  app/src/main/res/values-ja/strings_i18n.xml
  app/src/main/res/values/strings_i18n.xml
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardCardUnselectedViewHolderViewModelTest.kt
Labels: bug 🐛, copy 📝

#830 [🎨] NT-1111 Adding 2 buttons in the new pledge footer
  app/src/main/res/layout/fragment_pledge_section_footer.xml
Labels: UI 🎨

#829 [🗣] NT-1126 Payment methods a11y
  app/src/main/res/layout/item_reward_selected_card.xml
  app/src/main/res/layout/item_reward_unselected_card.xml
  app/src/main/res/values-de/strings_i18n.xml
  app/src/main/res/values-es/strings_i18n.xml
  app/src/main/res/values-fr/strings_i18n.xml
  app/src/main/res/values-ja/strings_i18n.xml
  app/src/main/res/values/strings_i18n.xml
Labels: a11y ♿️

#833 [👷🏾‍♀️] NT-1128 Moved continue button in Pledge screen to footer
  app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/main/res/layout/fragment_pledge.xml
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Labels: feature ✨

#832 [⚠️] NT-1131 Pledge error Toasts
  app/src/main/java/com/kickstarter/extensions/ToastExt.kt
  app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
  app/src/main/res/drawable/ic_icon_alert.xml
  app/src/main/res/layout/toast_error.xml
  app/src/main/res/values-de/strings_i18n.xml
  app/src/main/res/values-es/strings_i18n.xml
  app/src/main/res/values-fr/strings_i18n.xml
  app/src/main/res/values-ja/strings_i18n.xml
  app/src/main/res/values/strings_i18n.xml
Labels: UI 🎨, feature ✨

#834 [␡] NT-1127 Removing Update pledge button
  app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/main/res/layout/fragment_pledge.xml
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Labels: UI 🎨

#835 [📝] NT-1130 Pledge button CTA
  app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Labels: copy 📝

#836 [✅] NT-1133 Enabling pledge button only when all fields are valid
  app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Labels: bug 🐛, feature ✨

#818 [🚀] 2.5.0 RC
  app/external_version_code.txt
  app/external_version_name.txt
  app/internal_version_code.txt
  app/internal_version_name.txt
Labels: release 🚀

#839 [ℹ️] NT-1143 Adding more info to TrackingWorker error logs
  app/src/main/java/com/kickstarter/services/TrackingWorker.kt
  build.gradle
Labels: infrastructure 👷‍♀️

#840 [🚀] 2.5.1 RC
  app/external_version_code.txt
  app/external_version_name.txt
  app/internal_version_code.txt
  app/internal_version_name.txt
Labels: release 🚀

#843 [🆕] Updating config and strings
  app/src/main/assets/json/server-config.json
  app/src/main/res/values-de/strings_i18n.xml
  app/src/main/res/values-es/strings_i18n.xml
  app/src/main/res/values-fr/strings_i18n.xml
  app/src/main/res/values-ja/strings_i18n.xml
  app/src/main/res/values/strings_i18n.xml
Labels: maintenance 🗜

#846 [💥] NT-1177 Adding Optimizely property group (to Project Page Pledge Button Clicked event)
  app/src/main/java/com/kickstarter/ApplicationModule.java
  app/src/main/java/com/kickstarter/libs/ExperimentsClientType.kt
  app/src/main/java/com/kickstarter/libs/Koala.java
  app/src/main/java/com/kickstarter/libs/KoalaTrackingClient.java
  app/src/main/java/com/kickstarter/libs/LakeTrackingClient.kt
  app/src/main/java/com/kickstarter/libs/OptimizelyExperimentsClient.kt
  app/src/main/java/com/kickstarter/libs/TrackingClient.kt
  app/src/main/java/com/kickstarter/libs/TrackingClientType.java
  app/src/main/java/com/kickstarter/libs/models/OptimizelyEnvironment.kt
  app/src/main/java/com/kickstarter/libs/utils/ExperimentUtils.kt
  app/src/main/java/com/kickstarter/libs/utils/KoalaUtils.java
  app/src/main/java/com/kickstarter/mock/MockExperimentsClientType.kt
  app/src/test/java/com/kickstarter/KSRobolectricTestCase.java
  app/src/test/java/com/kickstarter/libs/KoalaTest.kt
  app/src/test/java/com/kickstarter/libs/LakeTest.kt
  app/src/test/java/com/kickstarter/libs/MockTrackingClient.java
  app/src/test/java/com/kickstarter/libs/utils/ExperimentUtilsTest.kt
Labels: refactor 🛠

#850 [💥] NT-1177 Adding Optimizely property group (to Project Page Pledge Button Clicked event)
  app/src/main/java/com/kickstarter/ApplicationModule.java
  app/src/main/java/com/kickstarter/libs/ExperimentsClientType.kt
  app/src/main/java/com/kickstarter/libs/Koala.java
  app/src/main/java/com/kickstarter/libs/KoalaTrackingClient.java
  app/src/main/java/com/kickstarter/libs/LakeTrackingClient.kt
  app/src/main/java/com/kickstarter/libs/OptimizelyExperimentsClient.kt
  app/src/main/java/com/kickstarter/libs/TrackingClient.kt
  app/src/main/java/com/kickstarter/libs/TrackingClientType.java
  app/src/main/java/com/kickstarter/libs/models/OptimizelyEnvironment.kt
  app/src/main/java/com/kickstarter/libs/utils/ExperimentUtils.kt
  app/src/main/java/com/kickstarter/libs/utils/KoalaUtils.java
  app/src/main/java/com/kickstarter/mock/MockExperimentsClientType.kt
  app/src/test/java/com/kickstarter/KSRobolectricTestCase.java
  app/src/test/java/com/kickstarter/libs/KoalaTest.kt
  app/src/test/java/com/kickstarter/libs/LakeTest.kt
  app/src/test/java/com/kickstarter/libs/MockTrackingClient.java
  app/src/test/java/com/kickstarter/libs/utils/ExperimentUtilsTest.kt
Labels: refactor 🛠

#848 [🐛] NT-1193 Pledge button disabled bug
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
Labels: bug 🐛

#851 NT-1074: Improve the Project Updates empty state
  app/src/main/java/com/kickstarter/libs/ApiPaginator.java
  app/src/main/java/com/kickstarter/libs/utils/IntegerUtils.java
  app/src/main/java/com/kickstarter/models/Project.java
  app/src/main/java/com/kickstarter/ui/adapters/UpdatesAdapter.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ProjectViewHolder.java
  app/src/main/java/com/kickstarter/viewmodels/ProjectHolderViewModel.java
  app/src/main/res/drawable/ic_bubble.xml
  app/src/main/res/layout/empty_updates_layout.xml
  app/src/test/java/com/kickstarter/viewmodels/ProjectHolderViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/ProjectUpdatesViewModelTest.java
Labels: feature ✨

#852 [🔄] NT-1190 Moving Campaign Details Pledge Button Clicked event from Optimizely to Data 💧
  app/src/main/java/com/kickstarter/libs/Koala.java
  app/src/main/java/com/kickstarter/libs/LakeEvent.kt
  app/src/main/java/com/kickstarter/libs/OptimizelyEvent.kt
  app/src/main/java/com/kickstarter/viewmodels/CampaignDetailsViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/CampaignDetailsViewModelTest.kt
Labels: events 🛤

#853 [🔄] NT-1191 Moving Campaign Details Button Clicked event from Optimizely to Data 💧
  app/src/main/java/com/kickstarter/libs/Koala.java
  app/src/main/java/com/kickstarter/libs/LakeEvent.kt
  app/src/main/java/com/kickstarter/libs/OptimizelyEvent.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Labels: events 🛤

#847 [⛔️] NT-598 Fix your pledge
  app/build.gradle
  app/src/main/graphql/activity.graphql
  app/src/main/graphql/schema.json
  app/src/main/java/com/kickstarter/ApplicationModule.java
  app/src/main/java/com/kickstarter/libs/graphql/DateTimeAdapter.kt
  app/src/main/java/com/kickstarter/libs/utils/BackingUtils.java
  app/src/main/java/com/kickstarter/libs/utils/ProjectViewUtils.kt
  app/src/main/java/com/kickstarter/mock/factories/ErroredBackingFactory.kt
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/models/ErroredBacking.kt
  app/src/main/java/com/kickstarter/services/ApolloClientType.kt
  app/src/main/java/com/kickstarter/services/KSApolloClient.kt
  app/src/main/java/com/kickstarter/ui/IntentKey.java
  app/src/main/java/com/kickstarter/ui/activities/ActivityFeedActivity.java
  app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
  app/src/main/java/com/kickstarter/ui/adapters/ActivityFeedAdapter.java
  app/src/main/java/com/kickstarter/ui/data/PledgeReason.kt
  app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ErroredBackingViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/RewardCardSelectedViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/RewardCardUnselectedViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/ActivityFeedViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/BaseRewardCardViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ErroredBackingViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardCardUnselectedViewHolderViewModel.kt
  app/src/main/res/color/button_pledge_error.xml
  app/src/main/res/layout/fragment_backing.xml
  app/src/main/res/layout/item_errored_backing.xml
  app/src/main/res/layout/item_header_errored_backings.xml
  app/src/main/res/layout/item_reward_selected_card.xml
  app/src/main/res/layout/item_reward_unselected_card.xml
  app/src/main/res/layout/pledge_container.xml
  app/src/main/res/layout/retry_card_warning.xml
  app/src/main/res/layout/reward_card_details.xml
  app/src/test/java/com/kickstarter/libs/utils/BackingUtilsTest.java
  app/src/test/java/com/kickstarter/ui/adapters/ActivityFeedAdapterTest.java
  app/src/test/java/com/kickstarter/viewmodels/ActivityFeedViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/BackingFragmentViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ErroredBackingViewHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardCardUnselectedViewHolderViewModelTest.kt
Labels: feature ✨

#854 [🐜] Fixes imports in ProjectViewModelTest so the tests can build!
  app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Labels: bug 🐛

#855 [🔄] NT-1192 Moving Creator Details Button Clicked event from Optimizely to Data 💧
  app/src/main/java/com/kickstarter/libs/Koala.java
  app/src/main/java/com/kickstarter/libs/LakeEvent.kt
  app/src/main/java/com/kickstarter/libs/OptimizelyEvent.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Labels: events 🛤

#856 [␡] NT-1195 No longer tracking Project Page Pledge Button Clicked in Optimizely
  app/src/main/java/com/kickstarter/libs/Koala.java
  app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Labels: events 🛤

#857 [🔢] NT-1196 Including erroredBackingsCount in drawer Activity count
  app/src/main/java/com/kickstarter/models/User.java
  app/src/main/java/com/kickstarter/ui/viewholders/discoverydrawer/LoggedInViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/ActivityFeedViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/LoggedInViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ActivityFeedViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/LoggedInViewHolderViewModelTest.kt
Labels: feature ✨

#858 [␡] NT-1189 Removed App Completed Checkout Optimizely event
  app/src/main/java/com/kickstarter/libs/OptimizelyEvent.kt
  app/src/main/java/com/kickstarter/viewmodels/ThanksViewModel.java
  app/src/test/java/com/kickstarter/viewmodels/ThanksViewModelTest.java
Labels: events 🛤

#859 [🔴] NT-1197 Red drawer activity count text color when there are errored backings
  app/src/main/java/com/kickstarter/ui/viewholders/discoverydrawer/LoggedInViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/LoggedInViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/LoggedInViewHolderViewModelTest.kt
Labels: UI 🎨

#860 [🔴] NT-1198 Red menu indicator for errored backings
  app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.java
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java
  app/src/main/res/drawable/ic_menu_error_indicator.xml
  app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.java
Labels: UI 🎨

#861 [␡] NT-1199 Removing unused Optimizely tracking calls
  app/src/main/java/com/kickstarter/libs/ExperimentsClientType.kt
  app/src/main/java/com/kickstarter/libs/OptimizelyExperimentsClient.kt
  app/src/main/java/com/kickstarter/libs/utils/ExperimentUtils.kt
  app/src/main/java/com/kickstarter/mock/MockExperimentsClientType.kt
  app/src/test/java/com/kickstarter/KSRobolectricTestCase.java
  app/src/test/java/com/kickstarter/libs/utils/ExperimentUtilsTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ThanksViewModelTest.java
Labels: refactor 🛠

#862 [⛔️] NT-1149 Tracking Pledge Submit Button Clicked event for errored pledges
  app/src/main/java/com/kickstarter/ui/data/PledgeFlowContext.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
  app/src/test/java/com/kickstarter/libs/LakeTest.kt
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Labels: events 🛤

#863 NT-658 ErroredPledge push notification
  app/src/internal/java/com/kickstarter/ui/views/DebugPushNotificationsView.java
  app/src/internal/res/layout/debug_push_notifications_layout.xml
  app/src/main/java/com/kickstarter/libs/PushNotifications.java
  app/src/main/java/com/kickstarter/services/apiresponses/PushNotificationEnvelope.java
  app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
  app/src/main/res/values/strings.xml
Labels: feature ✨

#864 NT-1148: Fix pledge button clicked event
  app/src/main/java/com/kickstarter/libs/Koala.java
  app/src/main/java/com/kickstarter/libs/LakeEvent.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Labels: events 🛤

#865 NT-1207 Deep linking to project pledge URL
  app/src/main/java/com/kickstarter/services/KSUri.java
  app/src/main/java/com/kickstarter/ui/activities/DeepLinkActivity.java
  app/src/main/java/com/kickstarter/viewmodels/DeepLinkViewModel.java
  app/src/test/java/com/kickstarter/services/KSUriTest.java
  app/src/test/java/com/kickstarter/viewmodels/DeepLinkViewModelTest.java
Labels: feature ✨

#867 NT-658 Errored pledge deserialization
  app/src/main/java/com/kickstarter/services/firebase/MessageService.java
Labels: bug 🐛
