Repository kickstarter/android-oss, pull requests merged in 2020-10, with the labels that each got.

#1004 [NT-1424] - v2.8.0 - Fall 2020 country launches
  app/external_version_code.txt
  app/external_version_name.txt
  app/internal_version_code.txt
  app/internal_version_name.txt
  app/src/main/assets/json/server-config.json
  app/src/main/java/com/kickstarter/libs/models/Country.kt
  app/src/main/java/com/kickstarter/libs/utils/RewardUtils.java
  app/src/main/java/com/kickstarter/ui/activities/AccountActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/main/res/values-de/strings_i18n.xml
  app/src/main/res/values-es/strings_i18n.xml
  app/src/main/res/values-fr/strings_i18n.xml
  app/src/main/res/values-ja/strings_i18n.xml
  app/src/main/res/values/strings_i18n.xml
  app/src/test/java/com/kickstarter/libs/utils/RewardUtilsTest.java
Labels: release 🚀

#1010 NT-1589: Add-on with future start date is available in add-ons screen
  app/src/main/java/com/kickstarter/libs/utils/RewardUtils.java
  app/src/main/java/com/kickstarter/viewmodels/BackingAddOnViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
  app/src/test/java/com/kickstarter/libs/utils/RewardUtilsTest.java
Labels: feature ✨

#1009 NT-1585:Reward with starting time restriction not started yet.
  app/src/main/graphql/fragments.graphql
  app/src/main/java/com/kickstarter/libs/utils/KoalaUtils.java
  app/src/main/java/com/kickstarter/libs/utils/RewardUtils.java
  app/src/main/java/com/kickstarter/models/Reward.java
  app/src/main/java/com/kickstarter/services/KSApolloClient.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingAddOnViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardsFragmentViewModel.kt
  app/src/test/java/com/kickstarter/libs/utils/RewardUtilsTest.java
  app/src/test/java/com/kickstarter/viewmodels/RewardsFragmentViewModelTest.kt
Labels: feature ✨

#1011 NT-1587: AddOns costs
  app/src/main/graphql/fragments.graphql
  app/src/main/java/com/kickstarter/services/KSApolloClient.kt
Labels: bug 🐛

#1008 NT-1531: Android Refactor RewardUtils Java to Kotlin
  app/src/main/java/com/kickstarter/libs/utils/BackingUtils.java
  app/src/main/java/com/kickstarter/libs/utils/KoalaUtils.java
  app/src/main/java/com/kickstarter/libs/utils/RewardUtils.java
  app/src/main/java/com/kickstarter/libs/utils/RewardUtils.kt
  app/src/test/java/com/kickstarter/libs/utils/RewardUtilsTest.java
  app/src/test/java/com/kickstarter/libs/utils/RewardUtilsTest.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardViewHolderViewModelTest.kt
Labels: refactor 🛠

#1013 NT-1587: Improve performance
  app/src/main/java/com/kickstarter/viewmodels/BackingAddOnViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModelTest.kt
Labels: feature ✨, refactor 🛠

#1014 NT-1454: Android Add-ons Button Polish
  app/src/main/res/layout/item_add_on_pledge.xml
Labels: UI 🎨

#1015 NT-1587: Query with filtering for shippingRules
  app/src/main/graphql/fragments.graphql
  app/src/main/graphql/project.graphql
  app/src/main/graphql/schema.json
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/models/Location.java
  app/src/main/java/com/kickstarter/services/ApolloClientType.kt
  app/src/main/java/com/kickstarter/services/KSApolloClient.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModelTest.kt
Labels: bug 🐛, feature ✨

#1018 NT-1574: Android Add-ons Pills Polish
  app/src/main/res/layout/item_add_on_pledge.xml
Labels: UI 🎨

#1019 NT-1615: fix Edit reward when add-ons were available but not backed
  app/external_version_code.txt
  app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardViewHolderViewModelTest.kt
Labels: bug 🐛

#1020 NT-1479: Android Pledge Screen Polish
  app/src/main/res/layout/fragment_pledge_section_bonus_support.xml
  app/src/main/res/layout/fragment_pledge_section_editable_shipping.xml
  app/src/main/res/layout/fragment_pledge_section_shipping.xml
Labels: UI 🎨

#1007 NT-1428- Migration from Crashlytics to firebase crashlytics
  app/build.gradle
  app/src/main/java/com/kickstarter/ApplicationModule.java
  app/src/main/java/com/kickstarter/KSApplication.java
  app/src/main/java/com/kickstarter/libs/BaseActivity.java
  app/src/main/java/com/kickstarter/libs/TrackingClient.kt
  app/src/main/java/com/kickstarter/services/TrackingWorker.kt
  app/src/main/java/com/kickstarter/services/firebase/RegisterTokenWorker.kt
  app/src/main/java/com/kickstarter/services/firebase/ResetDeviceIdWorker.kt
  app/src/main/java/com/kickstarter/services/firebase/UnregisterTokenWorker.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
  app/src/main/java/com/kickstarter/ui/adapters/KSAdapter.java
  app/src/main/java/com/kickstarter/ui/adapters/KSListAdapter.kt
  app/src/test/java/com/kickstarter/TestKSApplication.java
Labels: maintenance 🗜

#1021 NT-1616: Shipping location retention when changing reward
  app/src/main/java/com/kickstarter/mock/factories/ShippingRulesEnvelopeFactory.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModelTest.kt
Labels: bug 🐛

#1022 NT-1624: IndexOutOfBoundsException
  app/external_version_name.txt
  app/internal_version_code.txt
  app/internal_version_name.txt
  app/src/main/java/com/kickstarter/ui/extensions/EditTextExtension.kt
  app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
  app/src/main/res/layout/fragment_pledge_section_bonus_support.xml
Labels: bug 🐛

#1023 NT-1630: Fix UpdateActivity crash
  app/src/main/java/com/kickstarter/ui/activities/UpdateActivity.java
Labels: bug 🐛

#1024 NT-1625: Fix crash
  app/src/main/java/com/kickstarter/services/KSApolloClient.kt
Labels: bug 🐛

#1025 NT-1615:copy change
  app/src/main/java/com/kickstarter/libs/utils/RewardViewUtils.kt
  app/src/main/java/com/kickstarter/mock/factories/ProjectFactory.java
  app/src/test/java/com/kickstarter/libs/utils/RewardViewUtilsTest.kt
Labels: feature ✨
