Repository kickstarter/android-oss, pull requests merged in 2020-07, with the labels that each got.

#918 NT-1326: Reward Title going two lines
  app/src/main/java/com/kickstarter/viewmodels/ExpandableHeaderViewHolderViewModel.kt
  app/src/main/res/layout/fragment_pledge_section_header_item.xml
  app/src/main/res/layout/fragment_pledge_section_header_reward_sumary.xml
Labels: bug 🐛

#931 NT-1387: Filter by location
  app/src/main/java/com/kickstarter/libs/utils/RewardUtils.java
  app/src/main/java/com/kickstarter/models/Reward.java
  app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModelTest.kt
Labels: feature ✨

#935 Update strings with translated strings
  app/src/main/assets/json/server-config.json
  app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
  app/src/main/res/layout/fragment_backing.xml
  app/src/main/res/layout/fragment_backing_section_bonus.xml
  app/src/main/res/layout/fragment_backing_section_delivery_date_reminder.xml
  app/src/main/res/layout/fragment_pledge_section_bonus_support.xml
  app/src/main/res/values-de/strings_i18n.xml
  app/src/main/res/values-es/strings_i18n.xml
  app/src/main/res/values-fr/strings_i18n.xml
  app/src/main/res/values-ja/strings_i18n.xml
  app/src/main/res/values/strings_i18n.xml
Labels: copy 📝, feature ✨

#938 Selected Shipping Rule cost for Add-ons
  app/src/main/java/com/kickstarter/ui/adapters/BackingAddOnsAdapter.kt
  app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
  app/src/main/java/com/kickstarter/ui/viewholders/BackingAddOnViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingAddOnViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
  app/src/main/res/layout/item_add_on_pledge.xml
  app/src/test/java/com/kickstarter/viewmodels/BackingAddOnViewHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModelTest.kt
Labels: feature ✨

#937 NT-1386: Stepper UI on Add-On card
  app/src/main/graphql/fragments.graphql
  app/src/main/java/com/kickstarter/services/KSApolloClient.kt
  app/src/main/java/com/kickstarter/ui/adapters/BackingAddOnsAdapter.kt
  app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
  app/src/main/java/com/kickstarter/ui/viewholders/BackingAddOnViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingAddOnViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
  app/src/main/res/color/soft_grey_enabled_drak_gray_disabled.xml
  app/src/main/res/drawable/border_rounded_soft_grey_300.xml
  app/src/main/res/drawable/border_rounded_solid_black.xml
  app/src/main/res/layout/fragment_backing_addons.xml
  app/src/main/res/layout/item_add_on_pledge.xml
  app/src/test/java/com/kickstarter/viewmodels/BackingAddOnViewHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModelTest.kt
Labels: feature ✨

#940 NT-1437: AddOns selection
  app/src/main/java/com/kickstarter/ui/adapters/BackingAddOnsAdapter.kt
  app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
  app/src/main/java/com/kickstarter/ui/viewholders/BackingAddOnViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
Labels: feature ✨
