Repository kickstarter/android-oss, pull requests merged in 2020-05, with the labels that each got.

#870 NT-1242 Support for Optimizely feature flags
  app/src/main/java/com/kickstarter/libs/ExperimentsClientType.kt
  app/src/main/java/com/kickstarter/libs/OptimizelyExperimentsClient.kt
  app/src/main/java/com/kickstarter/libs/TrackingClient.kt
  app/src/main/java/com/kickstarter/libs/models/OptimizelyFeature.kt
  app/src/main/java/com/kickstarter/mock/MockExperimentsClientType.kt
  app/src/test/java/com/kickstarter/libs/LakeTest.kt
  app/src/test/java/com/kickstarter/libs/MockTrackingClient.java
Labels: feature ✨

#871 NT-1243 Displaying enabled Optimizely feature flags in Internal Tools
  app/src/internal/java/com/kickstarter/ui/activities/FeatureFlagsActivity.kt
  app/src/internal/java/com/kickstarter/viewmodels/FeatureFlagsViewModel.kt
  app/src/internal/res/layout/activity_feature_flags.xml
  app/src/main/res/values/strings.xml
  app/src/testInternal/java/com/kickstarter/viewmodels/FeatureFlagsViewModelTest.kt
Labels: internal tools 🛠

#872 NT-1233 Showing location in project cards
  app/src/main/java/com/kickstarter/libs/utils/DiscoveryUtils.java
  app/src/main/java/com/kickstarter/services/DiscoveryParams.java
  app/src/main/java/com/kickstarter/ui/adapters/DiscoveryPagerAdapter.java
  app/src/main/java/com/kickstarter/ui/viewholders/ProjectCardViewHolder.java
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/ProjectCardHolderViewModel.java
  app/src/main/res/layout/project_tags.xml
  app/src/test/java/com/kickstarter/viewmodels/ProjectCardHolderViewModelTest.java
Labels: feature ✨

#875 NT-1232 Sorting `LIGHTS_ON` projects by distance
  app/src/main/java/com/kickstarter/viewmodels/EditorialViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/EditorialViewModelTest.kt
Labels: feature ✨

#874 NT-1244 Listening for Optimizely initialization in BaseFragment
  app/src/main/java/com/kickstarter/ApplicationModule.java
  app/src/main/java/com/kickstarter/libs/BaseFragment.java
  app/src/main/java/com/kickstarter/libs/ExperimentsClientType.kt
  app/src/main/java/com/kickstarter/libs/FragmentViewModel.java
  app/src/main/java/com/kickstarter/ui/viewholders/EditorialViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
  app/src/test/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModelTest.java
Labels: experiments 🔮, feature ✨

#877 NT-1230: Style Lights On in Editorial view
  app/src/main/java/com/kickstarter/ui/viewholders/EditorialViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
  app/src/main/res/layout/activity_editorial.xml
  app/src/test/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModelTest.java
Labels: feature ✨

#876 Updating graphQL schema
  app/src/main/graphql/schema.json
Labels: maintenance 🗜

#878 NT-1246 Moving Editorial Card Clicked Event into Data Lake
  app/src/main/java/com/kickstarter/libs/Koala.java
  app/src/main/java/com/kickstarter/libs/KoalaEvent.java
  app/src/main/java/com/kickstarter/libs/LakeEvent.kt
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
Labels: events 🛤

#879 Backing status bug fix
  app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
Labels: bug 🐛

#880 StoredCard Marshmallow bug
  app/src/main/java/com/kickstarter/models/StoredCard.kt
Labels: bug 🐛

#881 2.6.1 RC
  app/external_version_code.txt
  app/external_version_name.txt
  app/internal_version_code.txt
  app/internal_version_name.txt
  app/src/main/java/com/kickstarter/models/StoredCard.kt
  app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
Labels: release 🚀

#882 Bumping internal and external version names and codes post 2.6.1 RC
  app/external_version_code.txt
  app/external_version_name.txt
  app/internal_version_code.txt
  app/internal_version_name.txt
Labels: maintenance 🗜

#883 Broken currency tests: BackingViewModelTest
  app/src/test/java/com/kickstarter/viewmodels/BackingViewModelTest.java
Labels: refactor 🛠

#884 Broken currency tests: BackingFragmentViewModelTest
  app/src/test/java/com/kickstarter/viewmodels/BackingFragmentViewModelTest.kt
Labels: refactor 🛠

#885 Broken currency tests: CancelPledgeViewModelTest
  app/src/test/java/com/kickstarter/viewmodels/CancelPledgeViewModelTest.kt
Labels: refactor 🛠

#886 Broken currency tests: ProjectViewModelTest
  app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Labels: refactor 🛠

#887 Broken currency tests: RewardViewHolderViewModelTest
  app/src/test/java/com/kickstarter/viewmodels/RewardViewHolderViewModelTest.kt
Labels: refactor 🛠

#888 Broken currency tests: ShippingRuleViewHolderViewModelTest
  app/src/test/java/com/kickstarter/viewmodels/ShippingRuleViewHolderViewModelTest.kt
Labels: refactor 🛠

#889 Broken currency tests: PledgeFragmentViewModelTest
  app/src/main/java/com/kickstarter/mock/factories/RewardFactory.java
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Labels: refactor 🛠

#894 Fix: potential security vulnerability in one of our dependencies.
  Gemfile.lock
Labels: maintenance 🗜
