Repository kickstarter/android-oss, pull requests merged in 2021-09, with the labels that each got.

#1384 NTV-7: Review Widget
  app/build.gradle
  app/src/main/java/com/kickstarter/ApplicationGraph.java
  app/src/main/java/com/kickstarter/libs/utils/ViewUtils.java
  app/src/main/java/com/kickstarter/ui/activities/ThanksActivity.kt
  app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt
  app/src/main/java/com/kickstarter/ui/views/AppRatingDialog.kt
  app/src/main/res/layout/app_rating_prompt.xml
Labels: feature ✨

#1386 NTV-23: Add deeplink for discovery with sort
  app/src/main/java/com/kickstarter/libs/utils/extensions/UriExt.kt
  app/src/main/java/com/kickstarter/services/DiscoveryParams.java
  app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.kt
  app/src/test/java/com/kickstarter/services/UriExtTest.kt
  app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.java
Labels: feature ✨

#1387 NTV-41: Add deeplink for discovery with collections
  app/src/main/java/com/kickstarter/services/DiscoveryParams.java
  app/src/test/java/com/kickstarter/services/DiscoveryParamsTest.java
Labels: feature ✨

#1388 NTV-171: Project query
  app/src/main/graphql/fragments.graphql
  app/src/main/graphql/project.graphql
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/models/Category.java
  app/src/main/java/com/kickstarter/models/Project.java
  app/src/main/java/com/kickstarter/services/ApolloClientType.kt
  app/src/main/java/com/kickstarter/services/KSApolloClient.kt
  app/src/main/java/com/kickstarter/ui/intentmappers/ProjectIntentMapper.java
  app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
Labels: feature ✨, refactor 🛠

#1391 NTV-182: missing values v1 Currency + No Reward
  app/src/main/graphql/fragments.graphql
  app/src/main/java/com/kickstarter/libs/utils/extensions/ProjectExt.kt
  app/src/main/java/com/kickstarter/mock/factories/ConfigFactory.java
  app/src/main/java/com/kickstarter/mock/factories/ProjectFactory.java
  app/src/main/java/com/kickstarter/mock/factories/UserFactory.java
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/models/User.java
  app/src/main/java/com/kickstarter/services/ApolloClientType.kt
  app/src/main/java/com/kickstarter/services/KSApolloClient.kt
  app/src/main/java/com/kickstarter/ui/intentmappers/ProjectIntentMapper.java
  app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/ProjectExtTest.kt
  app/src/test/java/com/kickstarter/ui/intents/ProjectIntentMapperTest.java
  app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Labels: refactor 🛠

#1394 NTV-183: Fix discovery crash when changing sort after choosing category
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.java
Labels: bug 🐛

#1393 NTV-191: rewards missing fields
  app/src/main/graphql/fragments.graphql
  app/src/main/graphql/schema.json
  app/src/main/java/com/kickstarter/libs/utils/RewardUtils.kt
  app/src/main/java/com/kickstarter/services/KSApolloClient.kt
Labels: refactor 🛠

#1396 Regression 2.19.0
  app/external_version_code.txt
  app/internal_version_code.txt
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.java
Labels: bug 🐛, release 🚀

#1400 [NTV-174 & NTV-175]: fetch faq & environmentCommitment from GraphQL
  app/src/main/graphql/fragments.graphql
  app/src/main/java/com/kickstarter/models/EnvironmentalCommitment.kt
  app/src/main/java/com/kickstarter/models/Project.java
  app/src/main/java/com/kickstarter/models/ProjectFaq.kt
  app/src/main/java/com/kickstarter/services/KSApolloClient.kt
  app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
  app/src/test/java/com/kickstarter/libs/utils/TransformersTest.kt
  app/src/test/java/com/kickstarter/models/EnvironmentalCommitmentTest.kt
  app/src/test/java/com/kickstarter/models/ProjectFaqTest.kt
Labels: feature ✨

#1402 [No-Jira]: Remove unnecessary network call
  app/src/main/java/com/kickstarter/services/KSApolloClient.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
Labels: refactor 🛠

#1398 NTV-190: Help – Contact button not working
  app/src/main/java/com/kickstarter/ui/activities/HelpSettingsActivity.kt
Labels: bug 🐛

#1403 NTV-163: Optimizely experiment flag for risk message modal
  app/src/main/java/com/kickstarter/libs/models/OptimizelyExperiment.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Labels: feature ✨, experiments 🔮

#1405 NTV-189: Bug investigation
  app/src/main/java/com/kickstarter/libs/utils/RewardUtils.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ThanksViewModel.java
  app/src/test/java/com/kickstarter/libs/utils/RewardUtilsTest.kt
Labels: bug 🐛, refactor 🛠

#1406 [no-jira]: Remove "suggested_no_reward_amount" experiment
  app/src/main/java/com/kickstarter/libs/models/OptimizelyExperiment.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardViewHolderViewModelTest.kt
Labels: refactor 🛠

#1407 NTV-189: Wrong bonus update pledge
  app/src/main/java/com/kickstarter/libs/utils/NumberUtils.java
  app/src/main/java/com/kickstarter/libs/utils/extensions/StringExt.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/StringExtKtTest.kt
Labels: bug 🐛

#1408 NTV-220: Crash after opening deep link and change Sort
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.kt
Labels: bug 🐛

#1404 NTV-204: Add new ProjectPageActivity and ProjectPageViewModel, and remove references to overview recyclerview
  app/src/internal/java/com/kickstarter/ui/activities/PlaygroundActivity.kt
  app/src/internal/res/layout/playground_layout.xml
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectPageViewModel.kt
  app/src/main/res/layout/activity_project_page.xml
  app/src/test/java/com/kickstarter/viewmodels/ProjectPageViewModelTest.kt
Labels: feature ✨, UI 🎨

#1412 NTV-205: Navigation Selector
  app/src/main/java/com/kickstarter/libs/Configure.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/ui/adapters/ProjectPagerAdapter.kt
  app/src/main/java/com/kickstarter/ui/fragments/ProjectFaqFragment.kt
  app/src/main/java/com/kickstarter/ui/fragments/projectpage/FrequentlyAskedQuestionFragment.kt
  app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectCampaignFragment.kt
  app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectEnvironmentalCommitmentsFragment.kt
  app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectOverviewFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectFaqViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/FrequentlyAskedQuestionViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectCampaignViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectEnvironmentalCommitmentsViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectOverviewViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectPageViewModel.kt
  app/src/main/res/layout/activity_project_page.xml
  app/src/main/res/layout/fragment_project_campaign.xml
  app/src/main/res/layout/fragment_project_environmental_commitments.xml
  app/src/main/res/layout/fragment_project_faq.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/com/kickstarter/viewmodels/FrequentlyAskedQuestionViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectPageViewModelTest.kt
Labels: feature ✨

#1414 NTV-203: Project Page v2 Feature Flag
  app/src/main/java/com/kickstarter/ApplicationModule.java
  app/src/main/java/com/kickstarter/libs/PushNotifications.java
  app/src/main/java/com/kickstarter/libs/models/OptimizelyFeature.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/IntentExt.kt
  app/src/main/java/com/kickstarter/ui/activities/ActivityFeedActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ProfileActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/SearchActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ThanksActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/UpdateActivity.kt
  app/src/main/java/com/kickstarter/ui/fragments/DiscoveryFragment.kt
  app/src/main/java/com/kickstarter/ui/viewholders/CreatorDashboardHeaderViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/ActivityFeedViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/CreatorDashboardHeaderHolderViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/ProfileViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/SearchViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/ThanksViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/UpdateViewModel.kt
  app/src/test/java/com/kickstarter/libs/PushNotificationsTest.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/IntentExtTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ActivityFeedViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/CreatorDashboardHeaderHolderViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/ProfileViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/SearchViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/ThanksViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/UpdateViewModelTest.java
Labels: feature ✨, UI 🎨
