Repository kickstarter/android-oss, pull requests merged in 2021-06, with the labels that each got.

#1265 NT-1992: Automatic release process step 3
  fastlane/Appfile
  fastlane/Fastfile
  lib/milkrun/version_code.rb
Labels: feature ✨, internal tools 🛠, maintenance 🗜

#1266 NT-953: Fetch a thread query
  app/build.gradle
  app/src/main/graphql/replies.graphql
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/models/Comment.java
  app/src/main/java/com/kickstarter/services/ApolloClientType.kt
  app/src/main/java/com/kickstarter/services/KSApolloClient.kt
  app/src/main/java/com/kickstarter/viewmodels/ThreadViewModel.kt
Labels: feature ✨

#1269 NT-1977: UX – Not logged in / not backer for Comment Card
  app/src/main/java/com/kickstarter/mock/factories/CommentFactory.kt
  app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
  app/src/main/java/com/kickstarter/ui/adapters/CommentsAdapter.kt
  app/src/main/java/com/kickstarter/ui/data/CommentCardData.kt
  app/src/main/java/com/kickstarter/ui/viewholders/CommentCardViewHolder.kt
  app/src/main/java/com/kickstarter/ui/views/CommentCard.kt
  app/src/main/java/com/kickstarter/ui/views/CommentComposerView.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
  app/src/main/res/layout/activity_comments_layout.xml
  app/src/main/res/values/attrs.xml
  app/src/test/java/com/kickstarter/ui/view/CommentCardTest.kt
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.kt
Labels: feature ✨

#1271 NT-1910: UX – Not logged in / Not backer for Comment Composer
  app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
  app/src/main/java/com/kickstarter/ui/views/CommentComposerView.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
  app/src/main/res/layout/activity_comments_layout.xml
  app/src/main/res/layout/comment_composer_view.xml
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.kt
Labels: UI 🎨, feature ✨

#1272 NT-1984: Feature flags for threads
  app/src/main/java/com/kickstarter/libs/models/OptimizelyFeature.kt
  app/src/main/java/com/kickstarter/ui/activities/ThreadActivity.kt
  app/src/main/java/com/kickstarter/ui/viewholders/CommentCardViewHolder.kt
  app/src/main/java/com/kickstarter/ui/views/CommentCard.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewHolderViewModel.kt
  app/src/main/res/layout/comment_card.xml
  app/src/main/res/values/attrs.xml
  app/src/test/java/com/kickstarter/ui/view/CommentCardTest.kt
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewHolderViewModelTest.kt
Labels: UI 🎨, feature ✨

#1273 NT-1911 :UX – Error posting comment
  app/src/main/java/com/kickstarter/mock/factories/CommentFactory.kt
  app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
  app/src/main/java/com/kickstarter/ui/viewholders/CommentCardViewHolder.kt
  app/src/main/java/com/kickstarter/ui/views/CommentCard.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
  app/src/main/res/drawable/ic_posted_check.xml
  app/src/main/res/drawable/rect_trans_rounded_darker.xml
  app/src/main/res/layout/activity_comments_layout.xml
  app/src/main/res/layout/comment_card.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/kickstarter/ui/view/CommentCardTest.kt
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.kt
Labels: UI 🎨, feature ✨

#1282 NT-1912: String translations and update copy
  app/src/main/assets/json/server-config.json
  app/src/main/java/com/kickstarter/ui/views/CommentCard.kt
  app/src/main/res/layout/comment_card.xml
  app/src/main/res/layout/comment_composer_view.xml
  app/src/main/res/values-de/strings_i18n.xml
  app/src/main/res/values-es/strings_i18n.xml
  app/src/main/res/values-fr/strings_i18n.xml
  app/src/main/res/values-ja/strings_i18n.xml
  app/src/main/res/values/strings_i18n.xml
Labels: UI 🎨, bug 🐛, copy 📝

#1280 NT-2025: Fix duplicated comments
  app/src/main/java/com/kickstarter/mock/factories/CommentFactory.kt
  app/src/main/java/com/kickstarter/ui/viewholders/CommentCardViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewHolderViewModelTest.kt
Labels: bug 🐛, maintenance 🗜

#1281 NT-2004: Fix comments and updates screen on Thank You page
  app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Labels: UI 🎨, bug 🐛, feature ✨

#1283 NT-1908:UI for Comment Composer
  app/src/main/res/layout/comment_composer_view.xml
Labels: UI 🎨, bug 🐛

#1285 NT-2029:UX – Add delay to "Posting..." error state
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewHolderViewModelTest.kt
Labels: UI 🎨, bug 🐛

#1286 NT-2037: Pagination Error Cell displayed at the same time as the comments cells
  app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
  app/src/main/java/com/kickstarter/ui/adapters/CommentsAdapter.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
  app/src/main/res/layout/activity_comments_layout.xml
  app/src/main/res/layout/item_error_pagination.xml
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.kt
Labels: feature ✨

#1288 NT-1962:UX – Show removed comments
  app/src/main/java/com/kickstarter/ui/viewholders/CommentCardViewHolder.kt
  app/src/main/java/com/kickstarter/ui/views/CommentCard.kt
  app/src/main/res/values/styles.xml
Labels: UI 🎨, bug 🐛

#1290 NT-2038: Cell UI for pagination error & NT-2039: Reload the errored page
  app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
  app/src/main/java/com/kickstarter/ui/adapters/CommentsAdapter.kt
  app/src/main/java/com/kickstarter/ui/viewholders/PaginationErrorViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/PaginationErrorViewHolderViewModel.kt
  app/src/main/res/layout/item_error_pagination.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/kickstarter/viewmodels/PaginationErrorViewHolderViewModelTest.kt
Labels: UI 🎨, feature ✨

#1293 NT-2055: Duplicated comments
  app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
  app/src/main/java/com/kickstarter/ui/adapters/CommentsAdapter.kt
  app/src/main/java/com/kickstarter/ui/viewholders/CommentCardViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
  app/src/main/res/layout/comment_card.xml
Labels: bug 🐛

#1294 Fix "Reply" copy
  app/src/main/res/layout/comment_card.xml
  app/src/main/res/values/styles.xml
Labels: copy 📝

#1296 NT-1962:UX – Show removed comments
  app/src/main/java/com/kickstarter/libs/utils/extensions/StringExt.kt
  app/src/main/java/com/kickstarter/ui/extensions/TextViewExt.kt
  app/src/main/java/com/kickstarter/ui/views/CommentCard.kt
Labels: UI 🎨, bug 🐛

#1291 NT-1968:UX – Add comment composer to thread
  app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ThreadActivity.kt
  app/src/main/java/com/kickstarter/ui/views/CommentComposerView.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ThreadViewModel.kt
  app/src/main/res/layout/activity_thread_layout.xml
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ThreadViewModelTest.kt
Labels: UI 🎨, feature ✨

#1298 NT-2058:Updates – Showing project comments instead of update's
  app/src/main/graphql/fragments.graphql
  app/src/main/graphql/project.graphql
  app/src/main/java/com/kickstarter/mock/factories/CommentFactory.kt
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/services/ApolloClientType.kt
  app/src/main/java/com/kickstarter/services/KSApolloClient.kt
  app/src/main/java/com/kickstarter/services/apiresponses/commentresponse/CommentEnvelope.kt
  app/src/main/java/com/kickstarter/services/mutations/PostCommentData.kt
  app/src/main/java/com/kickstarter/ui/data/CommentCardData.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.kt
Labels: bug 🐛, feature ✨

#1300 NT-2059: Update stripe sdk (payments) from 12.0.1 to 16.10.0
  app/build.gradle
  app/src/main/java/com/kickstarter/mock/factories/CardFactory.kt
  app/src/main/java/com/kickstarter/mock/factories/CardParamsFactory.kt
  app/src/main/java/com/kickstarter/mock/factories/TokenFactory.kt
  app/src/main/java/com/kickstarter/models/StoredCard.kt
  app/src/main/java/com/kickstarter/ui/fragments/NewCardFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/NewCardFragmentViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/BackingFragmentViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/NewCardFragmentViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/PaymentMethodsViewHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardCardSelectedViewHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardCardUnselectedViewHolderViewModelTest.kt
Labels: feature ✨, maintenance 🗜

#1303 NT-2069:Refactor Comment Pagination code
  app/src/main/java/com/kickstarter/libs/RecyclerViewPaginator.java
  app/src/main/java/com/kickstarter/libs/loadmore/ApolloPaginate.kt
  app/src/main/java/com/kickstarter/models/ApolloEnvelope.kt
  app/src/main/java/com/kickstarter/services/apiresponses/commentresponse/CommentEnvelope.kt
  app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.kt
Labels: bug 🐛, feature ✨

#1304 NT-2005: Update Dependencies to Latest Version
  app/build.gradle
Labels: maintenance 🗜

#1308 NT-2069:Refactor Comment Pagination code
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
Labels: bug 🐛, wontfix 🙉
