Repository kickstarter/android-oss, pull requests merged in 2021-05, with the labels that each got.

#1235 NT-1872: Middleware + persist users traits
  app/src/main/java/com/kickstarter/ApplicationModule.java
  app/src/main/java/com/kickstarter/libs/SegmentTrackingClient.kt
  app/src/main/java/com/kickstarter/mock/factories/UserFactory.java
  app/src/main/java/com/kickstarter/models/extensions/UserExt.kt
  app/src/test/java/com/kickstarter/libs/SegmentTest.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/UserExtensionTest.kt
Labels: feature ✨

#1237 [no-jira]: Update segment version + flush queue with 1 event on staging
  app/build.gradle
  app/src/main/java/com/kickstarter/libs/SegmentTrackingClient.kt
Labels: bug 🐛, events 🛤

#1240 NT-1735: Target API 30 🚀
  .circleci/config.yml
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/viewmodels/CreatorBioViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/LoginViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/MessageCreatorViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/VideoViewModel.kt
  app/src/test/java/com/kickstarter/KSRobolectrictTestCase.kt
  app/src/test/java/com/kickstarter/libs/rx/transformers/ObserveForUITransformerTest.java
  app/src/test/java/com/kickstarter/libs/utils/DateTimeUtilsTest.java
  app/src/test/java/com/kickstarter/libs/utils/NumberUtilsTest.java
  codecov.yml
Labels: infrastructure 👷‍♀️

#1241 NT-1871: InAppMessage listener + DeepLink
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/libs/SegmentTrackingClient.kt
  app/src/main/java/com/kickstarter/libs/braze/BrazeClient.kt
  app/src/main/java/com/kickstarter/libs/braze/InAppCustomListener.kt
  app/src/main/java/com/kickstarter/libs/braze/InAppCustomListenerHandler.kt
  app/src/main/java/com/kickstarter/services/KSUri.java
  app/src/main/java/com/kickstarter/ui/activities/DeepLinkActivity.java
  app/src/main/java/com/kickstarter/viewmodels/DeepLinkViewModel.java
  app/src/main/res/values/styles.xml
  app/src/test/java/com/kickstarter/libs/InAppCustomListenerHandlerTest.kt
  app/src/test/java/com/kickstarter/services/KSUriTest.java
  app/src/test/java/com/kickstarter/viewmodels/DeepLinkViewModelTest.java
Labels: feature ✨

#1242 NT-1860: Move up newsletter row
  app/src/main/res/layout/activity_newsletter.xml
Labels: UI 🎨

#1244 NT-1923: remove jcenter()
  app/build.gradle
  build.gradle
Labels: maintenance 🗜

#1243 NT-1916: Feature flag comment threading
  app/src/main/java/com/kickstarter/libs/ExperimentsClientType.kt
  app/src/main/java/com/kickstarter/libs/OptimizelyExperimentsClient.kt
  app/src/main/java/com/kickstarter/libs/models/OptimizelyFeature.kt
  app/src/main/java/com/kickstarter/libs/utils/ExperimentUtils.kt
  app/src/main/java/com/kickstarter/mock/MockExperimentsClientType.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
  app/src/test/java/com/kickstarter/libs/utils/ExperimentUtilsTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Labels: feature ✨

#1247 NT-1920: Setup Skeleton Activity and ViewModel for Root Comments
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/libs/utils/CommentUtils.java
  app/src/main/java/com/kickstarter/mock/factories/CommentFactory.java
  app/src/main/java/com/kickstarter/mock/factories/CommentsEnvelopeFactory.java
  app/src/main/java/com/kickstarter/mock/factories/DeprecatedCommentsEnvelopeFactory.java
  app/src/main/java/com/kickstarter/mock/services/MockApiClient.java
  app/src/main/java/com/kickstarter/models/DeprecatedComment.java
  app/src/main/java/com/kickstarter/services/ApiClient.java
  app/src/main/java/com/kickstarter/services/ApiClientType.java
  app/src/main/java/com/kickstarter/services/ApiService.java
  app/src/main/java/com/kickstarter/services/apirequests/DeprecatedCommentBody.java
  app/src/main/java/com/kickstarter/services/apiresponses/DeprecatedCommentsEnvelope.java
  app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/DeprecatedCommentsActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/UpdateActivity.kt
  app/src/main/java/com/kickstarter/ui/adapters/DeprecatedCommentsAdapter.java
  app/src/main/java/com/kickstarter/ui/adapters/data/CommentsData.java
  app/src/main/java/com/kickstarter/ui/viewholders/DeprecatedCommentViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/DeprecatedCommentsViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
  app/src/main/res/layout/deprecated_comment_card_view.xml
  app/src/main/res/layout/deprecated_comment_dialog.xml
  app/src/main/res/layout/deprecated_comments_layout.xml
  app/src/main/res/layout/deprecated_comments_toolbar.xml
  app/src/main/res/layout/post_comment_toolbar.xml
  app/src/main/res/layout/updates_toolbar.xml
  app/src/test/java/com/kickstarter/viewmodels/DeprecatedCommentsViewModelTest.java
Labels: feature ✨

#1263 [NO JIRA]: Updated gradle plugin
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: maintenance 🗜
