Repository kickstarter/android-oss, pull requests merged in 2021-07, with the labels that each got.

#1306 NT-2071: Update exoplayer, mockito, and timber dependencies to latest versions
  app/build.gradle
  app/src/main/java/com/kickstarter/ApplicationModule.java
  app/src/main/java/com/kickstarter/libs/CurrentConfig.java
  app/src/main/java/com/kickstarter/libs/PushNotifications.java
  app/src/main/java/com/kickstarter/models/chrome/ChromeTabsHelper.kt
  app/src/main/java/com/kickstarter/ui/activities/VideoActivity.kt
Labels: maintenance 🗜

#1311 NT-2053:UX – Add pagination to replies
  app/src/main/java/com/kickstarter/libs/RecyclerViewPaginator.java
  app/src/main/java/com/kickstarter/libs/loadmore/ApolloPaginate.kt
  app/src/main/java/com/kickstarter/libs/loadmore/PaginatedViewModelOutput.kt
  app/src/main/java/com/kickstarter/libs/loadmore/PaginationHandler.kt
  app/src/main/java/com/kickstarter/libs/loadmore/PaginationListener.kt
  app/src/main/java/com/kickstarter/mock/factories/CommentEnvelopeFactory.kt
  app/src/main/java/com/kickstarter/mock/factories/PageInfoEnvelopeFactory.kt
  app/src/main/java/com/kickstarter/services/ApolloClientType.kt
  app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ThreadActivity.kt
  app/src/main/java/com/kickstarter/ui/adapters/RepliesAdapter.kt
  app/src/main/java/com/kickstarter/ui/viewholders/CommentCardViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/PaginationViewMoreRepliesViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/RootCommentViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/PaginationViewMoreViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/RootCommentViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ThreadViewModel.kt
  app/src/main/res/layout/activity_thread_layout.xml
  app/src/main/res/layout/item_comment_card.xml
  app/src/main/res/layout/item_show_more_replies.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/com/kickstarter/viewmodels/PaginationViewMoreViewHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/RootCommentViewHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ThreadViewModelTest.kt
Labels: UI 🎨, feature ✨

#1312 NT-2095:View Replies show and hide with scrolling
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewHolderViewModelTest.kt
Labels: UI 🎨, bug 🐛

#1313 NT-1997:UI/UX – Error loading more replies
  app/src/main/java/com/kickstarter/ui/activities/ThreadActivity.kt
  app/src/main/java/com/kickstarter/ui/adapters/RepliesAdapter.kt
  app/src/main/java/com/kickstarter/ui/viewholders/PaginationErrorViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/ThreadViewModel.kt
Labels: UI 🎨

#1314 NT-2099:Crash when we create new comment and Press reply button
  app/src/main/java/com/kickstarter/services/KSApolloClient.kt
  app/src/main/java/com/kickstarter/ui/adapters/RepliesAdapter.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewHolderViewModel.kt
Labels: bug 🐛

#1315 NT-2067: 3DS card crash with SCA flow
  app/src/main/java/com/kickstarter/ApplicationModule.java
  app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
Labels: maintenance 🗜

#1318 Hadia/refactor replies adapter
  app/src/main/java/com/kickstarter/ui/activities/ThreadActivity.kt
  app/src/main/java/com/kickstarter/ui/adapters/RepliesAdapter.kt
  app/src/main/java/com/kickstarter/ui/adapters/RepliesStatusAdapter.kt
  app/src/main/java/com/kickstarter/ui/adapters/RootCommentAdapter.kt
  app/src/main/java/com/kickstarter/ui/viewholders/RepliesStatusCellViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/RootCommentViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/PaginationViewMoreViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/RepliesStatusCellViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ThreadViewModel.kt
  app/src/main/res/layout/item_root_comment_card.xml
  app/src/main/res/layout/item_show_more_replies.xml
  app/src/test/java/com/kickstarter/viewmodels/PaginationViewMoreViewHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/RepliesStatusCellViewHolderViewModelTest.kt
Labels: UI 🎨, bug 🐛

#1320 NT-1996:UI/UX – Error loading thread
  app/src/main/java/com/kickstarter/ui/activities/ThreadActivity.kt
  app/src/main/java/com/kickstarter/ui/adapters/RepliesStatusAdapter.kt
  app/src/main/java/com/kickstarter/ui/viewholders/RepliesStatusCellViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/RepliesStatusCellViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ThreadViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ThreadViewModelTest.kt
Labels: UI 🎨

#1326 NT-2130 :Pull missing translations
  app/src/main/assets/json/server-config.json
  app/src/main/res/layout/activity_thread_layout.xml
  app/src/main/res/layout/item_show_more_replies.xml
  app/src/main/res/values-de/strings_i18n.xml
  app/src/main/res/values-es/strings_i18n.xml
  app/src/main/res/values-fr/strings_i18n.xml
  app/src/main/res/values-ja/strings_i18n.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/strings_i18n.xml
Labels: UI 🎨

#1322 NT-2000: Retrying posting a failed reply
  app/src/main/java/com/kickstarter/ui/activities/ThreadActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewHolderViewModelTest.kt
Labels: UI 🎨, feature ✨

#1327 NT-2000: Retrying posting a failed reply Scrolling bug
  app/src/main/java/com/kickstarter/models/extensions/CommentExt.kt
  app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ThreadActivity.kt
  app/src/main/java/com/kickstarter/ui/viewholders/CommentCardViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ThreadViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ThreadViewModelTest.kt
Labels: bug 🐛

#1323 NT-2093: Skip first emitted value from paginated data to avoid initially showing empty state showing on root comments screen
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.kt
Labels: UI 🎨, bug 🐛, feature ✨

#1328 NT-1996 :UI/UX – Error loading thread
  app/src/main/java/com/kickstarter/services/apiresponses/commentresponse/CommentEnvelope.kt
  app/src/main/java/com/kickstarter/ui/activities/ThreadActivity.kt
  app/src/main/java/com/kickstarter/ui/adapters/RepliesStatusAdapter.kt
  app/src/main/java/com/kickstarter/ui/viewholders/RepliesStatusCellViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/RepliesStatusCellViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/RepliesStatusCellViewHolderViewModelTest.kt
Labels: bug 🐛

#1329 NT-2003:UX – Show pending comment dialog
  app/src/main/java/com/kickstarter/libs/utils/extensions/ContextExt.kt
  app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.kt
Labels: UI 🎨

#1330 NT-2001:UX – Show pending reply dialog
  app/src/main/java/com/kickstarter/ui/activities/ThreadActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/ThreadViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ThreadViewModelTest.kt
Labels: UI 🎨

#1331 NT-2125: CommentCard Screen shot test.
  app/build.gradle
  app/screenshots/external/debug/com.kickstarter.screenshoot.testing.ui.components.CommentCardShotTest_commentCardScreenshotTest_COMMENT_FOR_LOGIN_BACKED_USERS.png
  app/screenshots/external/debug/com.kickstarter.screenshoot.testing.ui.components.CommentCardShotTest_commentCardScreenshotTest_COMMENT_WITH_REPLIES.png
  app/screenshots/external/debug/com.kickstarter.screenshoot.testing.ui.components.CommentCardShotTest_commentCardScreenshotTest_DELETED_COMMENT.png
  app/screenshots/external/debug/com.kickstarter.screenshoot.testing.ui.components.CommentCardShotTest_commentCardScreenshotTest_FAILED_TO_SEND_COMMENT.png
  app/screenshots/external/debug/com.kickstarter.screenshoot.testing.ui.components.CommentCardShotTest_commentCardScreenshotTest_RE_TRYING_TO_POST.png
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.CommentCardShotTest_commentCardScreenshotTest_COMMENT_FOR_LOGIN_BACKED_USERS.png
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.CommentCardShotTest_commentCardScreenshotTest_COMMENT_WITH_REPLIES.png
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.CommentCardShotTest_commentCardScreenshotTest_DELETED_COMMENT.png
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.CommentCardShotTest_commentCardScreenshotTest_FAILED_TO_SEND_COMMENT.png
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.CommentCardShotTest_commentCardScreenshotTest_RE_TRYING_TO_POST.png
  app/src/androidTest/java/com/kickstarter/screenshoot/testing/InstrumentedApp.kt
  app/src/androidTest/java/com/kickstarter/screenshoot/testing/KSScreenShotTestRunner.kt
  app/src/androidTest/java/com/kickstarter/screenshoot/testing/di/AndroidTestApplicationModule.kt
  app/src/androidTest/java/com/kickstarter/screenshoot/testing/di/ApplicationComponent.kt
  app/src/androidTest/java/com/kickstarter/screenshoot/testing/di/NoopBuildCheck.kt
  app/src/androidTest/java/com/kickstarter/screenshoot/testing/ui/components/CommentCardShotTest.kt
  app/src/internal/AndroidManifest.xml
  app/src/internalDebug/AndroidManifest.xml
  app/src/main/java/com/kickstarter/IKSApplicationComponent.java
  app/src/main/java/com/kickstarter/KSApplication.java
  app/src/test/java/com/kickstarter/TestKSApplication.java
Labels: maintenance 🗜

#1332 NT-2001 :UX – Show pending dialog
  app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ThreadActivity.kt
  app/src/main/java/com/kickstarter/ui/views/CommentComposerView.kt
Labels: UI 🎨, bug 🐛

#1334 NT-1965:UX – Show not-a-backer-anymore comments
  app/src/main/graphql/fragments.graphql
  app/src/main/java/com/kickstarter/libs/utils/extensions/CommentListExt.kt
  app/src/main/java/com/kickstarter/mock/factories/CommentCardDataFactory.kt
  app/src/main/java/com/kickstarter/mock/factories/CommentFactory.kt
  app/src/main/java/com/kickstarter/models/Comment.java
  app/src/main/java/com/kickstarter/models/extensions/CommentExt.kt
  app/src/main/java/com/kickstarter/services/KSApolloClient.kt
  app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ThreadActivity.kt
  app/src/main/java/com/kickstarter/ui/adapters/RootCommentAdapter.kt
  app/src/main/java/com/kickstarter/ui/viewholders/CommentCardViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/RootCommentViewHolder.kt
  app/src/main/java/com/kickstarter/ui/views/CommentCard.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/RootCommentViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ThreadViewModel.kt
  app/src/main/res/layout/comment_card.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/kickstarter/ui/view/CommentCardTest.kt
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/RootCommentViewHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ThreadViewModelTest.kt
Labels: UI 🎨

#1335 NT-2133:UI – Misaligned icon on error messages
  app/src/main/java/com/kickstarter/ui/viewholders/PaginationErrorViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/RepliesStatusCellViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/ThreadViewModel.kt
  app/src/main/res/layout/item_error_pagination.xml
  app/src/main/res/layout/item_show_more_replies.xml
Labels: UI 🎨

#1336 NT-2003:UX – Show pending comment dialog
  app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
Labels: UI 🎨, bug 🐛

#1338 NT-2139:Screenshot Test Comment Composer
  app/screenshots/external/debug/com.kickstarter.screenshoot.testing.ui.components.CommentComposerShotTest_commentComposerViewScreenshotTest_DISABLED.png
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.CommentComposerShotTest_commentComposerViewScreenshotTest_DISABLED.png
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.CommentComposerShotTest_commentComposerViewScreenshotTest_ENABLED.png
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.CommentComposerShotTest_commentComposerViewScreenshotTest_WithLongText.png
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.CommentComposerShotTest_commentComposerViewScreenshotTest_WithMediumText.png
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.CommentComposerShotTest_commentComposerViewScreenshotTest_WithShortText.png
  app/src/androidTest/java/com/kickstarter/screenshoot/testing/ui/components/CommentComposerShotTest.kt
  app/src/main/java/com/kickstarter/ui/views/CommentComposerView.kt
  app/src/main/res/layout/comment_composer_view.xml
  app/src/main/res/layout/item_comment_composer.xml
Labels: maintenance 🗜

#1337 NT-1948: UI User badges
  app/src/main/java/com/kickstarter/mock/factories/CommentFactory.kt
  app/src/main/java/com/kickstarter/models/Comment.java
  app/src/main/java/com/kickstarter/models/extensions/CommentExt.kt
  app/src/main/java/com/kickstarter/ui/viewholders/CommentCardViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/RootCommentViewHolder.kt
  app/src/main/java/com/kickstarter/ui/views/CommentCard.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/RootCommentViewHolderViewModel.kt
  app/src/main/res/layout/comment_card.xml
  app/src/main/res/values/attrs.xml
  app/src/main/res/values/dimens.xml
  app/src/main/res/values/strings_i18n.xml
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/RootCommentViewHolderViewModelTest.kt
Labels: UI 🎨, feature ✨

#1340 NT-2150: Screenshot Test CommentCard: Not a backer any more state
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.CommentCardShotTest_commentCardScreenshotTest_CANCELED_PLEDGE_MESSAGE.png
  app/src/androidTest/java/com/kickstarter/screenshoot/testing/ui/components/CommentCardShotTest.kt
Labels: maintenance 🗜

#1339 NT-2093: UX – Empty state showing up when loading comments
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.kt
Labels: UI 🎨, bug 🐛, feature ✨
