Repository kickstarter/android-oss, pull requests merged in 2021-12, with the labels that each got.

#1476 no-jira: orientation changes issue
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
Labels: bug 🐛

#1481 NTV-301: Remove gray line above images
  app/src/main/res/layout/view_element_image_from_html.xml
Labels: bug 🐛, UI 🎨

#1489 NTV-320: migrate to kotlin preferences package
  app/build.gradle
  app/src/main/java/com/kickstarter/ApplicationModule.java
  app/src/main/java/com/kickstarter/libs/preferences/BooleanDataStore.kt
  app/src/main/java/com/kickstarter/libs/preferences/BooleanDataStoreType.kt
  app/src/main/java/com/kickstarter/libs/preferences/BooleanPreference.java
  app/src/main/java/com/kickstarter/libs/preferences/BooleanPreference.kt
  app/src/main/java/com/kickstarter/libs/preferences/BooleanPreferenceType.java
  app/src/main/java/com/kickstarter/libs/preferences/BooleanPreferenceType.kt
  app/src/main/java/com/kickstarter/libs/preferences/IntPreference.java
  app/src/main/java/com/kickstarter/libs/preferences/IntPreference.kt
  app/src/main/java/com/kickstarter/libs/preferences/IntPreferenceType.java
  app/src/main/java/com/kickstarter/libs/preferences/IntPreferenceType.kt
  app/src/main/java/com/kickstarter/libs/preferences/StringPreference.java
  app/src/main/java/com/kickstarter/libs/preferences/StringPreference.kt
  app/src/main/java/com/kickstarter/libs/preferences/StringPreferenceType.java
  app/src/main/java/com/kickstarter/libs/preferences/StringPreferenceType.kt
  app/src/test/java/com/kickstarter/libs/BooleanDataStoreTest.kt
Labels: migration

#1492 NTV-313 Migrate to Kotlin Extension KSColorUtils.java
  app/src/main/java/com/kickstarter/libs/utils/KSColorUtils.java
  app/src/test/java/com/kickstarter/KSColorUtilsTest.java
Labels: migration

#1495 NTV-317 DiffUtils.java delete
  app/src/main/java/com/kickstarter/libs/utils/DiffUtils.java
  app/src/test/java/com/kickstarter/libs/utils/DiffUtilsTest.java
Labels: migration

#1494 NTV-314: Migrate to Kotlin Extension BundleUtils.java
  app/src/main/java/com/kickstarter/libs/ActivityViewModelManager.java
  app/src/main/java/com/kickstarter/libs/BaseActivity.java
  app/src/main/java/com/kickstarter/libs/BaseBottomSheetDialogFragment.java
  app/src/main/java/com/kickstarter/libs/BaseFragment.java
  app/src/main/java/com/kickstarter/libs/FragmentViewModelManager.java
  app/src/main/java/com/kickstarter/libs/utils/BundleUtils.java
  app/src/main/java/com/kickstarter/libs/utils/extensions/BundleExt.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/BundleExtKtTest.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/DoubleExtTest.kt
Labels: migration

#1493 NTV-307 :Migrate to Kotlin Extension Primitive Utils classes
  app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
  app/src/main/java/com/kickstarter/libs/RecyclerViewPaginator.java
  app/src/main/java/com/kickstarter/libs/utils/AnalyticEventsUtils.kt
  app/src/main/java/com/kickstarter/libs/utils/BooleanUtils.java
  app/src/main/java/com/kickstarter/libs/utils/DiscoveryDrawerUtils.java
  app/src/main/java/com/kickstarter/libs/utils/DiscoveryParamsUtils.java
  app/src/main/java/com/kickstarter/libs/utils/IntegerUtils.java
  app/src/main/java/com/kickstarter/libs/utils/RewardUtils.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/BoolenExt.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/IntExt.kt
  app/src/main/java/com/kickstarter/models/Project.java
  app/src/main/java/com/kickstarter/models/Reward.java
  app/src/main/java/com/kickstarter/services/ApiClient.java
  app/src/main/java/com/kickstarter/services/DiscoveryParams.java
  app/src/main/java/com/kickstarter/services/KSApolloClient.kt
  app/src/main/java/com/kickstarter/services/firebase/RegisterTokenWorker.kt
  app/src/main/java/com/kickstarter/ui/activities/EditProfileActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/NewsletterActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/NotificationsActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/PrivacyActivity.kt
  app/src/main/java/com/kickstarter/ui/viewholders/CreatorDashboardRewardStatsRowViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/EmptyActivityFeedViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/RewardViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/discoverydrawer/LoggedInViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/ActivityFeedViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/AddOnViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/CreatorDashboardReferrerBreakdownHolderViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/CreatorDashboardViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/EditProfileViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/LoggedInViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/LoginViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/MessageHolderViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/MessageThreadHolderViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/MessageThreadsViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/MessagesViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/NewCardFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/NewsletterViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/NotificationsViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/PrivacyViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ProfileViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectCardHolderViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/ProjectHolderViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/ProjectUpdatesViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardCardUnselectedViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/SearchViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/ThanksViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/UpdateCardViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectOverviewViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectPageViewModel.kt
  app/src/test/java/com/kickstarter/libs/utils/BooleanUtilsTest.java
  app/src/test/java/com/kickstarter/libs/utils/IntegerUtilsTest.java
  app/src/test/java/com/kickstarter/libs/utils/extensions/BooleanExtTest.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/IntExtTest.kt
Labels: migration
