Repository kickstarter/android-oss, pull requests merged in 2021-08, with the labels that each got.

#1342 NT-2161:UI – Not-a-backer-anymore taking the space of the original comment
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.CommentCardShotTest_commentCardScreenshotTest_CANCELED_PLEDGE_MESSAGE.png
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.CommentCardShotTest_commentCardScreenshotTest_COMMENT_FOR_LOGIN_BACKED_USERS.png
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.CommentCardShotTest_commentCardScreenshotTest_COMMENT_WITH_REPLIES.png
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.CommentCardShotTest_commentCardScreenshotTest_DELETED_COMMENT.png
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.CommentCardShotTest_commentCardScreenshotTest_FAILED_TO_SEND_COMMENT.png
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.CommentCardShotTest_commentCardScreenshotTest_RE_TRYING_TO_POST.png
  app/src/androidTest/java/com/kickstarter/screenshoot/testing/ui/components/CommentCardShotTest.kt
  app/src/main/java/com/kickstarter/ui/viewholders/CommentCardViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/RootCommentViewHolder.kt
  app/src/main/java/com/kickstarter/ui/views/CommentCard.kt
  app/src/main/res/layout/comment_card.xml
  app/src/test/java/com/kickstarter/ui/view/CommentCardTest.kt
Labels: UI 🎨, bug 🐛

#1343 NT-2145:Limit Add-On Tag Reusable Component
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.AddOnTagShotTest_addOnTagComponentViewScreenshotTest_TextValue.png
  app/src/androidTest/java/com/kickstarter/screenshoot/testing/ui/components/AddOnTagShotTest.kt
  app/src/main/java/com/kickstarter/ui/viewholders/BackingAddOnViewHolder.kt
  app/src/main/java/com/kickstarter/ui/views/AddOnTagComponent.kt
  app/src/main/res/layout/add_on_tag.xml
  app/src/main/res/layout/item_add_on_pledge.xml
  app/src/main/res/values/attrs.xml
Labels: UI 🎨, maintenance 🗜

#1349 Fix limit and left
  app/src/main/java/com/kickstarter/ui/viewholders/BackingAddOnViewHolder.kt
  app/src/main/res/layout/item_add_on_pledge.xml
Labels: bug 🐛

#1351 NT-2012:Finalize the Adoption of View Bindings
  app/build.gradle
  app/src/internal/java/com/kickstarter/ui/activities/FeatureFlagsActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/AccountActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/CampaignDetailsActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ChangeEmailActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ChangePasswordActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/CreatePasswordActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/CreatorBioActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/EditProfileActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/EditorialActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/LoginActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/MessageCreatorActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/NewsletterActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/NotificationsActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/PaymentMethodsSettingsActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/PrivacyActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ProfileActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ResetPasswordActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/SettingsActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/UpdateActivity.kt
  app/src/main/java/com/kickstarter/ui/adapters/KSArrayAdapter.kt
  app/src/main/java/com/kickstarter/ui/adapters/ShippingRulesAdapter.kt
  app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
  app/src/main/java/com/kickstarter/ui/fragments/CancelPledgeFragment.kt
  app/src/main/java/com/kickstarter/ui/fragments/DiscoveryFragment.kt
  app/src/main/java/com/kickstarter/ui/fragments/NewCardFragment.kt
  app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
  app/src/main/java/com/kickstarter/ui/fragments/RewardsFragment.kt
  app/src/main/java/com/kickstarter/ui/viewholders/RewardCardUnselectedViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ShippingRuleViewHolder.kt
  app/src/main/java/com/kickstarter/ui/views/KSWebView.kt
  app/src/main/res/layout/activity_account.xml
  app/src/main/res/layout/activity_campaign_details.xml
  app/src/main/res/layout/activity_change_email.xml
  app/src/main/res/layout/activity_change_password.xml
  app/src/main/res/layout/activity_create_password.xml
  app/src/main/res/layout/activity_project.xml
  app/src/main/res/layout/activity_settings_payment_methods.xml
  app/src/main/res/layout/fragment_backing_addons.xml
  app/src/main/res/layout/fragment_new_card.xml
  app/src/main/res/layout/fragment_pledge.xml
  app/src/main/res/layout/fragment_pledge_section_editable_shipping.xml
  app/src/main/res/layout/fragment_pledge_section_shipping.xml
  app/src/main/res/layout/item_reward_unselected_card.xml
  app/src/main/res/layout/login_layout.xml
  app/src/main/res/layout/modal_fragment_new_card.xml
  app/src/main/res/layout/pledge_container.xml
  app/src/main/res/layout/profile_layout.xml
  app/src/main/res/layout/reset_password_layout.xml
  app/src/main/res/layout/update_layout.xml
Labels: maintenance 🗜

#1355 NT-2178 :💥 – Posting comment on update
  app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
  app/src/main/java/com/kickstarter/ui/adapters/CommentInitialErrorAdapter.kt
  app/src/main/java/com/kickstarter/ui/adapters/CommentPaginationErrorAdapter.kt
  app/src/main/java/com/kickstarter/ui/adapters/CommentsAdapter.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.kt
Labels: bug 🐛

#1356 Fix shipping isssue
  app/src/main/java/com/kickstarter/ui/adapters/KSArrayAdapter.kt
Labels: bug 🐛

#1358 NT-2143: Create add-on reusable component and migrate current add-ons screen to use new component
  app/src/androidTest/java/com/kickstarter/screenshoot/testing/ui/components/AddOnTagShotTest.kt
  app/src/main/java/com/kickstarter/ui/adapters/BackingAddOnsAdapter.kt
  app/src/main/java/com/kickstarter/ui/viewholders/BackingAddOnViewHolder.kt
  app/src/main/java/com/kickstarter/ui/views/AddOnCard.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingAddOnViewHolderViewModel.kt
  app/src/main/res/layout/add_on_card.xml
  app/src/main/res/layout/fragment_backing_addons.xml
  app/src/main/res/layout/item_add_on_pledge.xml
  app/src/main/res/values/attrs.xml
  app/src/test/java/com/kickstarter/viewmodels/BackingAddOnViewHolderViewModelTest.kt
Labels: UI 🎨, maintenance 🗜

#1362 Update "you" badge translation
  app/src/main/res/layout/comment_card.xml
  app/src/main/res/values-de/strings_i18n.xml
  app/src/main/res/values-es/strings_i18n.xml
  app/src/main/res/values-fr/strings_i18n.xml
  app/src/main/res/values-ja/strings_i18n.xml
  app/src/main/res/values/strings_i18n.xml
Labels: maintenance 🗜

#1363 Your comment wasn't posted dialog showing always after error
  app/src/main/java/com/kickstarter/ui/activities/ThreadActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/ThreadViewModel.kt
Labels: bug 🐛, maintenance 🗜

#1366 NT-2180: Empty state showing when pull to refresh
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
Labels: bug 🐛

#1360 NT-2182: Allow identify calls every time the app opens
  app/src/main/java/com/kickstarter/libs/SegmentTrackingClient.kt
Labels: bug 🐛

#1364 NT-2077: sent to Optimizely "app_build_number"
  app/src/main/java/com/kickstarter/libs/utils/ExperimentUtils.kt
  app/src/test/java/com/kickstarter/libs/utils/ExperimentUtilsTest.kt
Labels: events 🛤

#1365 [no-jira]: prepare for arctic fox
  app/build.gradle
  build.gradle
  gradle.properties
  gradle/wrapper/gradle-wrapper.properties
Labels: maintenance 🗜

#1372 NT-2192:Open Creator Bio crashes the app
  app/src/main/AndroidManifest.xml
Labels: bug 🐛

#1369 NT-4123: Addon card component with fixed missing description
  app/src/main/java/com/kickstarter/ui/adapters/BackingAddOnsAdapter.kt
  app/src/main/java/com/kickstarter/ui/viewholders/BackingAddOnViewHolder.kt
Labels: bug 🐛, UI 🎨

#1375 NT-2142: Addon card shot test
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.AddonCardShotTest_allViewsVisible.png
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.AddonCardShotTest_backerLimitInvisible.png
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.AddonCardShotTest_conversionInvisible.png
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.AddonCardShotTest_descriptionInvisible.png
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.AddonCardShotTest_dividerInvisible.png
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.AddonCardShotTest_itemListInvisible.png
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.AddonCardShotTest_quantityRemainingInvisible.png
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.AddonCardShotTest_shippingAmountInvisible.png
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.AddonCardShotTest_stepperVisible.png
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.AddonCardShotTest_timeLeftInvisible.png
  app/src/androidTest/java/com/kickstarter/screenshoot/testing/ui/components/AddonCardShotTest.kt
Labels: UI 🎨

#1373 [no-jira]: delete KSUri.java adopt Uri kotlin extension
  app/src/main/java/com/kickstarter/services/DiscoveryParams.java
  app/src/main/java/com/kickstarter/services/KSUri.java
  app/src/main/java/com/kickstarter/services/interceptors/ApiRequestInterceptor.kt
  app/src/main/java/com/kickstarter/services/interceptors/WebRequestInterceptor.kt
  app/src/main/java/com/kickstarter/ui/activities/SurveyResponseActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/UpdateActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/DeepLinkViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/UpdateViewModel.java
  app/src/test/java/com/kickstarter/services/KSUriTest.java
Labels: refactor 🛠, maintenance 🗜

#1374 NT-2193: Braze push notifications
  app/build.gradle
  app/src/main/java/com/kickstarter/libs/braze/BrazeClient.kt
Labels: bug 🐛, maintenance 🗜

#1377 Nt-2068: Fix update payment fails on pledges with addons, and no rewards
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Labels: bug 🐛

#1376 NT-2170: Remove segment feature flag
  app/src/internal/java/com/kickstarter/ui/activities/FeatureFlagsActivity.kt
  app/src/internal/java/com/kickstarter/viewmodels/FeatureFlagsViewModel.kt
  app/src/main/java/com/kickstarter/libs/TrackingClient.kt
  app/src/main/java/com/kickstarter/libs/TrackingClientType.kt
  app/src/main/java/com/kickstarter/libs/utils/ConfigFeatureFlagName.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/ConfigExtension.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/ConfigExtensionTest.kt
  app/src/testInternal/java/com/kickstarter/viewmodels/FeatureFlagsViewModelTest.kt
Labels: maintenance 🗜

#1378 NTV-48: Migrate DiscoveryViewModel.java to kotlin
  app/src/main/java/com/kickstarter/libs/BuildCheck.java
  app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ThanksViewModel.java
  app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.java
Labels: feature ✨, maintenance 🗜

#1379 NTV-14 :Add deep link to project comments
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/libs/utils/extensions/UriExt.kt
  app/src/main/java/com/kickstarter/ui/IntentKey.java
  app/src/main/java/com/kickstarter/ui/activities/DeepLinkActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/DeepLinkViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
  app/src/test/java/com/kickstarter/services/UriExtTest.kt
  app/src/test/java/com/kickstarter/viewmodels/DeepLinkViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Labels: feature ✨

#1380 NTV-18:Add deep link to update
  app/src/main/java/com/kickstarter/ui/IntentKey.java
  app/src/main/java/com/kickstarter/ui/activities/DeepLinkActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/DeepLinkViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/UpdateViewModel.java
  app/src/test/java/com/kickstarter/viewmodels/DeepLinkViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/UpdateViewModelTest.java
Labels: feature ✨
