Repository kickstarter/android-oss, pull requests merged in 2021-02, with the labels that each got.

#1082 NT-1751: Small Refactor
  app/src/main/java/com/kickstarter/libs/LakeTrackingClient.kt
  app/src/main/java/com/kickstarter/libs/SegmentTrackingClient.kt
  app/src/main/java/com/kickstarter/libs/TrackingClient.kt
  app/src/main/java/com/kickstarter/libs/TrackingClientType.kt
Labels: refactor 🛠

#1081 NT-1747: Identify users on segment
  app/src/main/java/com/kickstarter/ApplicationModule.java
  app/src/main/java/com/kickstarter/libs/LakeTrackingClient.kt
  app/src/main/java/com/kickstarter/libs/SegmentTrackingClient.kt
  app/src/main/java/com/kickstarter/libs/TrackingClient.kt
  app/src/main/java/com/kickstarter/libs/TrackingClientType.kt
  app/src/test/java/com/kickstarter/KSRobolectrictTestCase.kt
  app/src/test/java/com/kickstarter/libs/MockTrackingClient.java
  app/src/test/java/com/kickstarter/libs/SegmentTest.kt
  app/src/test/java/com/kickstarter/viewmodels/LoginToutViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/LoginViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/SignupViewModelTest.java
Labels: feature ✨

#1079 NT-1736: Migrate BackingUtils.java to kotlin ext
  app/src/main/java/com/kickstarter/libs/utils/ProjectViewUtils.kt
  app/src/main/java/com/kickstarter/libs/utils/RewardViewUtils.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/BackingExt.kt
  app/src/main/java/com/kickstarter/mock/factories/BackingFactory.java
  app/src/main/java/com/kickstarter/mock/factories/ProjectFactory.java
  app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/BaseRewardCardViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardsFragmentViewModel.kt
  app/src/test/java/com/kickstarter/libs/utils/ProjectViewUtilsTest.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/BackingExtKtTest.kt
Labels: maintenance 🗜, refactor 🛠

#1084 NT-1751: Reset method called when user logs out
  app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
  app/src/main/java/com/kickstarter/libs/SegmentTrackingClient.kt
  app/src/main/java/com/kickstarter/libs/TrackingClient.kt
  app/src/main/java/com/kickstarter/libs/TrackingClientType.kt
  app/src/main/java/com/kickstarter/viewmodels/ChangePasswordViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/CreatePasswordViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/SettingsViewModel.kt
  app/src/test/java/com/kickstarter/libs/MockTrackingClient.java
  app/src/test/java/com/kickstarter/viewmodels/ChangePasswordViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/CreatePasswordViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/SettingsViewModelTest.kt
Labels: feature ✨

#1085 NT-1763: Remove BackingUtils.java and corresponding test
  app/src/main/java/com/kickstarter/libs/utils/BackingUtils.java
  app/src/main/java/com/kickstarter/viewmodels/BaseRewardCardViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/libs/utils/BackingUtilsTest.java
Labels: maintenance 🗜, refactor 🛠

#1086 EP-153:Rename properties session_*
  app/src/main/java/com/kickstarter/libs/TrackingClientType.kt
  app/src/test/java/com/kickstarter/libs/LakeTest.kt
  app/src/test/java/com/kickstarter/libs/SegmentTest.kt
Labels: events 🛤

#1087 EP-153: Rename properties checkout_reward_*
  app/src/main/java/com/kickstarter/libs/utils/KoalaUtils.java
  app/src/test/java/com/kickstarter/libs/LakeTest.kt
  app/src/test/java/com/kickstarter/libs/SegmentTest.kt
Labels: events 🛤

#1089 NT-1762: Create Phase 1 "Back a Project" EventNames and EventContext Constants
  app/src/main/java/com/kickstarter/libs/utils/EventContext.kt
  app/src/main/java/com/kickstarter/libs/utils/EventName.kt
Labels: events 🛤

#1090 EP-215: Create event for Add-ons Continue button
  app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModelTest.kt
Labels: events 🛤

#1091 EP-153: Rename Properties
  app/src/main/java/com/kickstarter/libs/utils/KoalaUtils.java
  app/src/main/java/com/kickstarter/libs/utils/extensions/CheckoutDataExt.kt
  app/src/main/java/com/kickstarter/ui/data/CheckoutData.kt
  app/src/test/java/com/kickstarter/libs/LakeTest.kt
  app/src/test/java/com/kickstarter/libs/SegmentTest.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/CheckoutDataExtTest.kt
Labels: events 🛤

#1094 EP-216: Create event for Pledge Initiate CTA
  app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Labels: events 🛤

#1096 EP-217: Create event for Pledge Submit CTA
  app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Labels: events 🛤

#1098 EP-218: Create event for Select Reward CTA
  app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardViewHolderViewModelTest.kt
Labels: events 🛤

#1099 EP-219: Create event for Add-ons screen viewed
  app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
  app/src/main/java/com/kickstarter/libs/utils/EventContext.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Labels: events 🛤

#1102 NT-1775:Refactor LoginToutActivity
  app/src/main/java/com/kickstarter/ui/activities/LoginToutActivity.java
  app/src/main/java/com/kickstarter/ui/activities/LoginToutActivity.kt
  app/src/main/res/layout-land/login_tout_layout.xml
  app/src/main/res/layout/login_tout_layout.xml
Labels: refactor 🛠

#1097 NT-1765:Refactor ActivityFeedActivity
  app/src/main/java/com/kickstarter/ui/activities/ActivityFeedActivity.java
  app/src/main/java/com/kickstarter/ui/activities/ActivityFeedActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ThanksActivity.java
  app/src/main/java/com/kickstarter/ui/activities/ThanksActivity.kt
  app/src/main/res/layout/thanks_layout.xml
Labels: refactor 🛠

#1092 NT-1763:Refactor CommentsActivity
  app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.java
  app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
  app/src/main/res/layout/comments_layout.xml
Labels: refactor 🛠

#1104 NT-1777:Refactor Picasso code due to integrate firebase in-app sdk
  app/build.gradle
  app/src/main/java/com/kickstarter/libs/PushNotifications.java
  app/src/main/java/com/kickstarter/ui/activities/EditProfileActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ProfileActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/SettingsActivity.kt
  app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ActivitySampleFriendBackingViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ActivitySampleFriendFollowViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ActivitySampleProjectViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/CommentViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/FeaturedSearchResultViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/FriendBackingViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/FriendFollowViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/MessageThreadViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/MessageViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ProfileCardViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ProjectCardViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ProjectContextViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ProjectSearchResultViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ProjectSocialViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ProjectStateChangedPositiveViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ProjectStateChangedViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ProjectUpdateViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ProjectViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/SurveyViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/discoverydrawer/LoggedInViewHolder.kt
Labels: refactor 🛠

#1095 NT-1764:Refactor ThanksActivity
  app/src/main/java/com/kickstarter/ui/activities/ThanksActivity.kt
  app/src/main/res/layout/thanks_layout.xml
Labels: refactor 🛠

#1103 NT-1776:Refactor SignupActivity
  app/src/main/java/com/kickstarter/ui/activities/SignupActivity.java
  app/src/main/java/com/kickstarter/ui/activities/SignupActivity.kt
  app/src/main/res/layout/signup_layout.xml
Labels: refactor 🛠

#1106 EP-220: Create event for Checkout screen viewed
  app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Labels: events 🛤

#1117 NT-1770: Perimeter X Managing Denied Requests
  app/src/main/java/com/kickstarter/ApplicationModule.java
  app/src/main/java/com/kickstarter/libs/perimeterx/PerimeterXClient.kt
  app/src/main/java/com/kickstarter/libs/perimeterx/PerimeterXClientType.kt
  app/src/main/java/com/kickstarter/mock/factories/PXClientFactory.kt
  app/src/main/java/com/kickstarter/services/interceptors/ApiRequestInterceptor.java
  app/src/main/java/com/kickstarter/services/interceptors/GraphQLInterceptor.kt
  app/src/main/java/com/kickstarter/ui/views/KSWebView.kt
  app/src/main/java/com/kickstarter/viewmodels/LoginViewModel.kt
  app/src/test/java/com/kickstarter/libs/PerimeterXTest.kt
Labels: feature ✨

#1122 NT-1759: Feature Flag for Segment
  app/src/main/java/com/kickstarter/libs/TrackingClient.kt
  app/src/main/java/com/kickstarter/libs/TrackingClientType.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/ConfigExtension.kt
  app/src/test/java/com/kickstarter/libs/MockTrackingClient.java
Labels: feature ✨

#1108 Reorganized key and value enums for segment.events
  app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
  app/src/main/java/com/kickstarter/libs/utils/EventContextValues.kt
  app/src/main/java/com/kickstarter/libs/utils/EventKeys.kt
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Labels: refactor 🛠

#1113 EP-221: Create event for Rewards Carousel viewed
  app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardsFragmentViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardsFragmentViewModelTest.kt
Labels: events 🛤

#1111 NT-1783:Refactor ProjectSocialActivity
  app/src/main/java/com/kickstarter/ui/activities/ProjectSocialActivity.java
  app/src/main/java/com/kickstarter/ui/activities/ProjectSocialActivity.kt
Labels: refactor 🛠

#1110 NT-1782:Refactor ProjectNotificationSettingsActivity
  app/src/main/java/com/kickstarter/ui/activities/ProjectNotificationSettingsActivity.java
  app/src/main/java/com/kickstarter/ui/activities/ProjectNotificationSettingsActivity.kt
Labels: refactor 🛠

#1107 NT-1780: Refactor Message and MessageThread Activity
  app/src/main/java/com/kickstarter/ui/activities/MessageThreadsActivity.java
  app/src/main/java/com/kickstarter/ui/activities/MessageThreadsActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/MessagesActivity.java
  app/src/main/java/com/kickstarter/ui/activities/MessagesActivity.kt
  app/src/main/res/layout/message_threads_layout.xml
  app/src/main/res/layout/messages_layout.xml
Labels: refactor 🛠

#1105 NT-1778:Refactor HelpActivity
  app/src/main/java/com/kickstarter/ui/activities/HelpActivity.java
  app/src/main/java/com/kickstarter/ui/activities/HelpActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/HelpSettingsActivity.kt
Labels: refactor 🛠

#1112 NT-1784:Refactor SearchActivity
  app/src/main/java/com/kickstarter/ui/activities/SearchActivity.java
  app/src/main/java/com/kickstarter/ui/activities/SearchActivity.kt
Labels: refactor 🛠

#1109 NT-1781:Refactor SurveyResponseActivity
  app/src/main/java/com/kickstarter/ui/activities/SurveyResponseActivity.java
  app/src/main/java/com/kickstarter/ui/activities/SurveyResponseActivity.kt
Labels: refactor 🛠

#1115 NT-1785:Refactor CreatorDashboardActivity
  app/src/main/java/com/kickstarter/ui/activities/CreatorDashboardActivity.java
  app/src/main/java/com/kickstarter/ui/activities/CreatorDashboardActivity.kt
  app/src/main/res/layout/creator_dashboard_layout.xml
Labels: refactor 🛠

#1116 NT-1786:Refactor WebViewActivity
  app/src/main/java/com/kickstarter/ui/activities/WebViewActivity.java
  app/src/main/java/com/kickstarter/ui/activities/WebViewActivity.kt
Labels: refactor 🛠

#1118 NT-1787:Refactor VideoActivity
  app/src/main/java/com/kickstarter/ui/activities/VideoActivity.java
  app/src/main/java/com/kickstarter/ui/activities/VideoActivity.kt
Labels: refactor 🛠

#1120 NT-1789:Refactor DownloadBetaActivity
  app/src/main/java/com/kickstarter/ui/activities/DownloadBetaActivity.java
  app/src/main/java/com/kickstarter/ui/activities/DownloadBetaActivity.kt
Labels: refactor 🛠

#1127 NT-1795:Refactor ProjectUpdatesActivity
  app/src/main/java/com/kickstarter/ui/activities/ProjectUpdatesActivity.java
  app/src/main/java/com/kickstarter/ui/activities/ProjectUpdatesActivity.kt
Labels: refactor 🛠

#1114 EP-221: Create event for Project screen viewed
  app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
  app/src/main/java/com/kickstarter/libs/utils/EventContextValues.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/ProjectDataExt.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/CampaignDetailsViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/ProjectUpdatesViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/CampaignDetailsViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/ProjectUpdatesViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
Labels: events 🛤

#1121 NT-1790:Refactor DiscoveryActivity and DiscoveryToolbar
  app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.java
  app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.kt
  app/src/main/java/com/kickstarter/ui/toolbars/DiscoveryToolbar.java
  app/src/main/java/com/kickstarter/ui/toolbars/DiscoveryToolbar.kt
  app/src/main/res/layout/discovery_layout.xml
Labels: refactor 🛠

#1125 EP-223: Create event for Thanks screen viewed
  app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
  app/src/main/java/com/kickstarter/viewmodels/ThanksViewModel.java
  app/src/test/java/com/kickstarter/viewmodels/ThanksViewModelTest.java
Labels: events 🛤

#1126 NT-1794:Refactor KSToolbar,SearchToolbar,ProjectToolbar
  app/src/main/java/com/kickstarter/ui/toolbars/KSToolbar.java
  app/src/main/java/com/kickstarter/ui/toolbars/KSToolbar.kt
  app/src/main/java/com/kickstarter/ui/toolbars/ProjectToolbar.java
  app/src/main/java/com/kickstarter/ui/toolbars/ProjectToolbar.kt
  app/src/main/java/com/kickstarter/ui/toolbars/SearchToolbar.java
  app/src/main/java/com/kickstarter/ui/toolbars/SearchToolbar.kt
Labels: refactor 🛠

#1123 NT-1792:Refactor FacebookConfirmationActivity
  app/src/main/java/com/kickstarter/ui/activities/FacebookConfirmationActivity.java
  app/src/main/java/com/kickstarter/ui/activities/FacebookConfirmationActivity.kt
Labels: refactor 🛠

#1124 NT-1793:Refactor LoginToolbar
  app/src/main/java/com/kickstarter/ui/toolbars/LoginToolbar.java
  app/src/main/java/com/kickstarter/ui/toolbars/LoginToolbar.kt
Labels: refactor 🛠

#1130 NT-1796 :Refactor ConfirmDialog and AppRatingDialog
  app/src/main/java/com/kickstarter/ui/views/AppRatingDialog.java
  app/src/main/java/com/kickstarter/ui/views/AppRatingDialog.kt
  app/src/main/java/com/kickstarter/ui/views/ConfirmDialog.java
  app/src/main/java/com/kickstarter/ui/views/ConfirmDialog.kt
Labels: refactor 🛠

#1128 EP-156: Session variants optimizely
  app/build.gradle
  app/src/main/java/com/kickstarter/libs/ExperimentsClientType.kt
  app/src/main/java/com/kickstarter/libs/OptimizelyExperimentsClient.kt
  app/src/main/java/com/kickstarter/libs/TrackingClient.kt
  app/src/main/java/com/kickstarter/libs/TrackingClientType.kt
  app/src/main/java/com/kickstarter/mock/MockExperimentsClientType.kt
  app/src/test/java/com/kickstarter/libs/SegmentTest.kt
Labels: events 🛤

#1132 NT-1797:Refactor InternalToolsActivity and DebugPushNotificationsView
  app/build.gradle
  app/src/internal/java/com/kickstarter/ui/activities/InternalToolsActivity.java
  app/src/internal/java/com/kickstarter/ui/activities/InternalToolsActivity.kt
  app/src/internal/java/com/kickstarter/ui/views/DebugPushNotificationsView.java
  app/src/internal/java/com/kickstarter/ui/views/DebugPushNotificationsView.kt
  app/src/internal/res/layout/internal_tools_layout.xml
  app/src/main/java/com/kickstarter/libs/EnumAdapter.java
  app/src/main/java/com/kickstarter/ui/toolbars/DiscoveryToolbar.kt
  app/src/main/java/com/kickstarter/ui/toolbars/KSToolbar.kt
  app/src/main/java/com/kickstarter/ui/toolbars/LoginToolbar.kt
  app/src/main/res/layout/loading_placeholder_footnote.xml
Labels: refactor 🛠

#1136 EP-241: Create event for Discover sort CTA
  app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
  app/src/main/java/com/kickstarter/libs/utils/AnalyticEventsUtils.kt
  app/src/main/java/com/kickstarter/libs/utils/EventContextValues.kt
  app/src/main/java/com/kickstarter/libs/utils/EventKeys.kt
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java
  app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.java
Labels: events 🛤

#1137 EP-239: Create event for Discover filters CTA
  app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
  app/src/main/java/com/kickstarter/libs/utils/EventContextValues.kt
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.java
  app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.java
Labels: events 🛤
