Repository kickstarter/android-oss, pull requests merged in 2021-11, with the labels that each got.

#1439 NTV-247 : Add to navigation and implement UI
  app/src/main/res/layout/fragment_frequently_asked_question.xml
  app/src/main/res/layout/fragment_project_environmental_commitments.xml
  app/src/main/res/layout/fragment_project_risks.xml
Labels: bug 🐛

#1438 NTV-272: Migrate AvatarDataModel to kotlin
  app/src/main/java/com/kickstarter/mock/factories/AvatarFactory.java
  app/src/main/java/com/kickstarter/models/Avatar.java
  app/src/main/java/com/kickstarter/models/Avatar.kt
  app/src/test/java/com/kickstarter/models/AvatarTest.kt
Labels: maintenance 🗜

#1397 [no-jira]: automatize regression build
  .circleci/config.yml
  Makefile
  fastlane/Fastfile
Labels: maintenance 🗜

#1440 [no-jira]: Update fastlane
  Gemfile.lock
Labels: maintenance 🗜

#1444 NTV-277: Backer cannot comment on updates
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
Labels: bug 🐛

#1447 NTV-278: UI pre-load polish
  app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectOverviewFragment.kt
  app/src/main/res/layout/project_creator_dashboard_header.xml
Labels: UI 🎨

#1450 NTV-276: Polish Project screen loading experience
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.MediaHeaderShotTest_playButton_whenVisibilityFalse_isGone.png
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.MediaHeaderShotTest_playButton_whenVisibilityTrue_isVisible.png
  app/src/androidTest/java/com/kickstarter/screenshoot/testing/ui/components/MediaHeaderShotTest.kt
  app/src/main/res/drawable/rectangle_grey.xml
  app/src/main/res/layout/media_header.xml
Labels: UI 🎨

#1456 NTV-289 :Remove old awareness component for experiment
  app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Labels: bug 🐛

#1454 NTV-280: Cannot edit a pledge with a sold out reward on a project with add-ons
  app/src/main/java/com/kickstarter/mock/factories/ProjectFactory.java
  app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/libs/utils/RewardViewUtilsTest.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardViewHolderViewModelTest.kt
Labels: bug 🐛

#1462 NTV-293: Project overview – Wrong updates count
  app/src/main/java/com/kickstarter/services/KSApolloClient.kt
Labels: bug 🐛

#1461 NTV-208: Scrolling transition of the video player
  app/build.gradle
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.MediaHeaderShotTest_playButton_whenVisibilityFalse_isGone.png
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.MediaHeaderShotTest_playButton_whenVisibilityTrue_isVisible.png
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectPageViewModel.kt
  app/src/main/res/drawable/ic_toolbar_button_background.xml
  app/src/main/res/layout/activity_project_page.xml
  app/src/main/res/layout/media_header.xml
  app/src/test/java/com/kickstarter/viewmodels/ProjectPageViewModelTest.kt
Labels: feature ✨, UI 🎨

#1464 NTV-263: Parser text elements
  app/src/main/java/com/kickstarter/libs/htmlparser/ElementExt.kt
  app/src/main/java/com/kickstarter/libs/htmlparser/HTMLModels.kt
  app/src/main/java/com/kickstarter/libs/htmlparser/HTMLParser.kt
  app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectCampaignFragment.kt
  app/src/test/java/com/kickstarter/libs/htmlparser/HTMLParserTest.kt
Labels: feature ✨

#1465 NTV-261 :Fetch and apply new translations
  app/src/main/java/com/kickstarter/ui/fragments/projectpage/FrequentlyAskedQuestionFragment.kt
  app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectEnvironmentalCommitmentsFragment.kt
  app/src/main/res/layout/fragment_frequently_asked_question.xml
Labels: bug 🐛
