Repository kickstarter/android-oss, pull requests merged in 2022-03, with the labels that each got.

#1551 NTV-383: Migrate Message.java to kotlin and deprecate Autoparcel
  app/src/main/java/com/kickstarter/mock/factories/MessageFactory.java
  app/src/main/java/com/kickstarter/mock/factories/MessageFactory.kt
  app/src/main/java/com/kickstarter/models/Message.java
  app/src/main/java/com/kickstarter/models/Message.kt
  app/src/main/java/com/kickstarter/services/apiresponses/MessageThreadEnvelope.java
  app/src/test/java/com/kickstarter/models/MessageTest.kt
Labels: maintenance 🗜, infrastructure 👷‍♀️, migration

#1553 Migrate update.java to kotlin and deprecate AutoParcel
  app/src/main/java/com/kickstarter/mock/factories/UpdateFactory.java
  app/src/main/java/com/kickstarter/mock/factories/UpdateFactory.kt
  app/src/main/java/com/kickstarter/models/Update.java
  app/src/main/java/com/kickstarter/models/Update.kt
  app/src/main/java/com/kickstarter/viewmodels/UpdateCardViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/UpdateViewModel.kt
  app/src/test/java/com/kickstarter/models/UpdateTest.kt
Labels: migration

#1555 NTV-417 : Total number of comments in project overview tabs not matching Web and Ios
  app/src/main/graphql/fragments.graphql
Labels: bug 🐛

#1561 WEB-361: Fix flaky date time test in RefTagUtils
  app/src/test/java/com/kickstarter/libs/utils/RefTagUtilsTest.java
Labels: bug 🐛

#1559 NTV-382: Migrate Activity.java to kotlin, deprecate autoparcel
  app/src/main/java/com/kickstarter/libs/utils/AnalyticEventsUtils.kt
  app/src/main/java/com/kickstarter/mock/factories/ActivityFactory.java
  app/src/main/java/com/kickstarter/mock/factories/ActivityFactory.kt
  app/src/main/java/com/kickstarter/models/Activity.java
  app/src/main/java/com/kickstarter/models/Activity.kt
  app/src/test/java/com/kickstarter/models/ActivityTest.kt
Labels: maintenance 🗜, migration

#1565 NTV-384 : Migrate MessageThread.java to kotlin and deprecate Autoparcel
  app/src/main/java/com/kickstarter/mock/factories/MessageThreadFactory.java
  app/src/main/java/com/kickstarter/mock/factories/MessageThreadFactory.kt
  app/src/main/java/com/kickstarter/models/MessageThread.java
  app/src/main/java/com/kickstarter/models/MessageThread.kt
  app/src/test/java/com/kickstarter/models/MessageThreadTest.kt
Labels: maintenance 🗜, migration

#1566 NTV-429: Gifs on last row on campaign tab not loading on first try
  app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.kt
  app/src/main/java/com/kickstarter/ui/extensions/ImageViewExt.kt
  app/src/main/java/com/kickstarter/ui/views/ImageWithCaptionView.kt
Labels: bug 🐛

#1567 NTV-385: Migrate to kotlin and deprecate autoparcel ProjectNotification model
  app/src/main/java/com/kickstarter/mock/factories/ProjectNotificationFactory.java
  app/src/main/java/com/kickstarter/mock/factories/ProjectNotificationFactory.kt
  app/src/main/java/com/kickstarter/models/ProjectNotification.java
  app/src/main/java/com/kickstarter/models/ProjectNotification.kt
  app/src/test/java/com/kickstarter/models/ProjectNotificationTest.kt
Labels: migration

#1572 NTV-435 :Migrate NumberOptions.java to kotlin and deprecate
  app/src/main/java/com/kickstarter/libs/NumberOptions.java
  app/src/main/java/com/kickstarter/libs/NumberOptions.kt
  app/src/test/java/com/kickstarter/models/NumberOptionsTest.kt
Labels: maintenance 🗜, migration

#1571 NTV-439 :Deprecate Autoparcel for CreatorDetails.kt
  app/src/main/java/com/kickstarter/mock/factories/CreatorDetailsFactory.kt
  app/src/main/java/com/kickstarter/models/CreatorDetails.kt
  app/src/test/java/com/kickstarter/models/CreatorDetailsTest.kt
Labels: maintenance 🗜, migration

#1570 NTV-444 :Migrate MessageBody.java to kotlin and deprecate Autoparcel
  app/src/main/java/com/kickstarter/services/apirequests/MessageBody.java
  app/src/main/java/com/kickstarter/services/apirequests/MessageBody.kt
  app/src/test/java/com/kickstarter/models/MessageBodyTest.kt
Labels: maintenance 🗜, migration

#1569 NTV-440 : Deprecate Autoparcel for ErroredBacking.kt
  app/src/main/java/com/kickstarter/mock/factories/ErroredBackingFactory.kt
  app/src/main/java/com/kickstarter/models/ErroredBacking.kt
  app/src/test/java/com/kickstarter/models/ErroredBackingTest.kt
  app/src/test/java/com/kickstarter/ui/adapters/ActivityFeedAdapterTest.java
Labels: maintenance 🗜

#1576 NTV-434 :Deprecate Autoparcel for ShippingRule.kt
  app/src/main/java/com/kickstarter/mock/factories/ShippingRuleFactory.kt
  app/src/main/java/com/kickstarter/mock/factories/ShippingRulesEnvelopeFactory.kt
  app/src/main/java/com/kickstarter/mock/services/MockApiClient.kt
  app/src/main/java/com/kickstarter/models/ShippingRule.kt
  app/src/main/java/com/kickstarter/services/apiresponses/ShippingRulesEnvelope.java
  app/src/main/java/com/kickstarter/services/apiresponses/ShippingRulesEnvelope.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingAddOnViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ShippingRuleViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/models/ShippingRuleTest.kt
  app/src/test/java/com/kickstarter/models/ShippingRulesEnvelopeTest.kt
  app/src/test/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Labels: migration

#1577 NTV-441 : Migrat Video.java to kotlin and deprecate Autoparcel
  app/src/main/java/com/kickstarter/mock/factories/VideoFactory.java
  app/src/main/java/com/kickstarter/mock/factories/VideoFactory.kt
  app/src/main/java/com/kickstarter/models/Video.java
  app/src/main/java/com/kickstarter/models/Video.kt
  app/src/test/java/com/kickstarter/models/VideoTest.kt
Labels: migration

#1578 NTV-381: Migrate KSCurrency to kotlin and deprecate autoparcel
  app/src/main/java/com/kickstarter/libs/CurrencyOptions.kt
  app/src/main/java/com/kickstarter/libs/KSCurrency.java
  app/src/main/java/com/kickstarter/libs/KSCurrency.kt
  app/src/test/java/com/kickstarter/KSCurrencyTest.java
  app/src/test/java/com/kickstarter/KSCurrencyTest.kt
  app/src/test/java/com/kickstarter/libs/CurrencyOptionsTest.kt
Labels: maintenance 🗜

#1580 NTV-437:Migrate RelativeDateTimeOptions to Kotlin and deprecate Autoparcel
  app/src/main/java/com/kickstarter/libs/RelativeDateTimeOptions.java
  app/src/main/java/com/kickstarter/libs/RelativeDateTimeOptions.kt
  app/src/main/java/com/kickstarter/libs/utils/DateTimeUtils.java
  app/src/main/java/com/kickstarter/libs/utils/DateTimeUtils.kt
  app/src/test/java/com/kickstarter/libs/utils/DateTimeUtilsTest.java
  app/src/test/java/com/kickstarter/libs/utils/DateTimeUtilsTest.kt
  app/src/test/java/com/kickstarter/models/RelativeDateTimeOptionsTest.kt
Labels: maintenance 🗜, migration

#1584 NTV-465: Add audio parsing
  app/build.gradle
  app/src/main/java/com/kickstarter/libs/htmlparser/ElementExt.kt
  app/src/main/java/com/kickstarter/libs/htmlparser/HTMLModels.kt
  app/src/main/java/com/kickstarter/libs/htmlparser/HTMLParser.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectCampaignViewModel.kt
  app/src/test/java/com/kickstarter/libs/htmlparser/HTMLParserTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectCampaignViewModelTests.kt
  jacoco.gradle
Labels: feature ✨

#1585 NTV-443 : Migrate LoginWithFacebookBody.java to kotlin and deprecate Autoparcel
  app/src/main/java/com/kickstarter/services/apirequests/LoginWithFacebookBody.java
  app/src/main/java/com/kickstarter/services/apirequests/LoginWithFacebookBody.kt
  app/src/test/java/com/kickstarter/models/LoginWithFacebookBodyTest.kt
Labels: migration
