Repository kickstarter/android-oss, pull requests merged in 2022-05, with the labels that each got.

#1619 PAY-1441: Add ons for local pickup reward
  app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModelTest.kt
Labels: feature ✨

#1620 NTV-535: Fix crashes
  app/src/main/java/com/kickstarter/libs/utils/ApplicationLifecycleUtil.java
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/ui/intentmappers/DiscoveryIntentMapper.kt
  app/src/main/java/com/kickstarter/viewmodels/ActivityFeedViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ProfileViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ThanksViewModel.kt
  jacoco.gradle
Labels: bug 🐛

#1621 PAY-1445: Add ons local receipt UI
  .circleci/config.yml
  app/screenshots/internal/debug/com.kickstarter.screenshoot.testing.ui.components.AddonCardShotTest_localPickupIsVisible.png
  app/src/androidTest/java/com/kickstarter/screenshoot/testing/ui/components/AddonCardShotTest.kt
  app/src/main/java/com/kickstarter/ui/viewholders/BackingAddOnViewHolder.kt
  app/src/main/java/com/kickstarter/ui/views/AddOnCard.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingAddOnViewHolderViewModel.kt
  app/src/main/res/layout/add_on_card.xml
  app/src/main/res/layout/reward_item_local_pickup.xml
  app/src/main/res/values/attrs.xml
Labels: feature ✨, UI 🎨

#1612 NTV-480: Migrate InternalBuildEnvelope.java to kotlin and deprecate Autoparcel
  app/src/main/java/com/kickstarter/mock/factories/InternalBuildEnvelopeFactory.java
  app/src/main/java/com/kickstarter/mock/factories/InternalBuildEnvelopeFactory.kt
  app/src/main/java/com/kickstarter/services/apiresponses/InternalBuildEnvelope.java
  app/src/main/java/com/kickstarter/services/apiresponses/InternalBuildEnvelope.kt
  app/src/test/java/com/kickstarter/services/apiresponses/InternalBuildEnvelopeTest.kt
Labels: maintenance 🗜, migration

#1624 NTV-537: Update perimeterX version
  app/build.gradle
Labels: maintenance 🗜

#1625 NTV-483: Migrate ProjectStatsEnvelope.java to kotlin and deprecate Autoparcel
  app/src/main/java/com/kickstarter/mock/factories/ProjectStatsEnvelopeFactory.java
  app/src/main/java/com/kickstarter/mock/factories/ProjectStatsEnvelopeFactory.kt
  app/src/main/java/com/kickstarter/services/apiresponses/ProjectStatsEnvelope.java
  app/src/main/java/com/kickstarter/services/apiresponses/ProjectStatsEnvelope.kt
  app/src/test/java/com/kickstarter/services/apiresponses/ProjectStatsEnvelopeTest.kt
  app/src/test/java/com/kickstarter/viewmodels/CreatorDashboardReferrerBreakdownHolderViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/CreatorDashboardReferrerStatsHolderViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/CreatorDashboardReferrerStatsRowHolderViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/CreatorDashboardRewardStatsHolderViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/DashboardRewardStatsRowHolderViewModelTest.java
Labels: maintenance 🗜, migration

#1632 NTV-548: Unable to resolve host "api.kickstarter.com"
  app/src/main/java/com/kickstarter/libs/rx/operators/ApiErrorOperator.java
  app/src/main/java/com/kickstarter/libs/rx/operators/ApiErrorOperator.kt
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.kt
  app/src/test/java/com/kickstarter/libs/rx/operators/ApiErrorOperatorTest.java
  app/src/test/java/com/kickstarter/libs/rx/operators/ApiErrorOperatorTest.kt
  app/src/test/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModelTest.java
Labels: bug 🐛
