Repository kickstarter/android-oss, pull requests merged in 2022-06, with the labels that each got.

#1631 NTV-546 Migrate qualifiers package Interface to Kotlin
  app/src/main/java/com/kickstarter/libs/qualifiers/AccessTokenPreference.java
  app/src/main/java/com/kickstarter/libs/qualifiers/AccessTokenPreference.kt
  app/src/main/java/com/kickstarter/libs/qualifiers/ActivitySamplePreference.java
  app/src/main/java/com/kickstarter/libs/qualifiers/ActivitySamplePreference.kt
  app/src/main/java/com/kickstarter/libs/qualifiers/ApiEndpointPreference.java
  app/src/main/java/com/kickstarter/libs/qualifiers/ApiEndpointPreference.kt
  app/src/main/java/com/kickstarter/libs/qualifiers/ApiRetrofit.java
  app/src/main/java/com/kickstarter/libs/qualifiers/ApiRetrofit.kt
  app/src/main/java/com/kickstarter/libs/qualifiers/AppRatingPreference.java
  app/src/main/java/com/kickstarter/libs/qualifiers/AppRatingPreference.kt
  app/src/main/java/com/kickstarter/libs/qualifiers/ApplicationContext.java
  app/src/main/java/com/kickstarter/libs/qualifiers/ApplicationContext.kt
  app/src/main/java/com/kickstarter/libs/qualifiers/ConfigPreference.java
  app/src/main/java/com/kickstarter/libs/qualifiers/ConfigPreference.kt
  app/src/main/java/com/kickstarter/libs/qualifiers/GamesNewsletterPreference.java
  app/src/main/java/com/kickstarter/libs/qualifiers/GamesNewsletterPreference.kt
  app/src/main/java/com/kickstarter/libs/qualifiers/PackageNameString.java
  app/src/main/java/com/kickstarter/libs/qualifiers/PackageNameString.kt
  app/src/main/java/com/kickstarter/libs/qualifiers/UserPreference.java
  app/src/main/java/com/kickstarter/libs/qualifiers/UserPreference.kt
  app/src/main/java/com/kickstarter/libs/qualifiers/WebEndpoint.java
  app/src/main/java/com/kickstarter/libs/qualifiers/WebEndpoint.kt
  app/src/main/java/com/kickstarter/libs/qualifiers/WebRetrofit.java
  app/src/main/java/com/kickstarter/libs/qualifiers/WebRetrofit.kt
Labels: migration

#1633 NTV 547 : Migrate key classes to kotlin
  app/src/main/java/com/kickstarter/libs/ActivityRequestCodes.java
  app/src/main/java/com/kickstarter/libs/ActivityRequestCodes.kt
  app/src/main/java/com/kickstarter/ui/ArgumentsKey.java
  app/src/main/java/com/kickstarter/ui/ArgumentsKey.kt
  app/src/main/java/com/kickstarter/ui/IntentKey.java
  app/src/main/java/com/kickstarter/ui/IntentKey.kt
  app/src/main/java/com/kickstarter/ui/SharedPreferenceKey.java
  app/src/main/java/com/kickstarter/ui/SharedPreferenceKey.kt
Labels: migration

#1630 NTV-371 : Migrate `DiscoveryPagerAdapter.java`
  app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.kt
  app/src/main/java/com/kickstarter/ui/adapters/DiscoveryPagerAdapter.java
  app/src/main/java/com/kickstarter/ui/adapters/DiscoveryPagerAdapter.kt
Labels: migration

#1635 NTV-552 : Migrate BackingActivity ,BackingViewModel classes to kotlin
  app/src/main/java/com/kickstarter/ui/activities/BackingActivity.java
  app/src/main/java/com/kickstarter/ui/activities/BackingActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/BackingViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/BackingViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/BackingViewModelTest.kt
Labels: migration

#1642 PAY-1716: Update stripe SDK
  app/build.gradle
Labels: maintenance 🗜

#1644 NTV-560: Updated gems
  Gemfile.lock
Labels: maintenance 🗜

#1648 WEB-567: Show flagged comment UI/state when pending T&S review
  app/src/main/graphql/fragments.graphql
  app/src/main/java/com/kickstarter/libs/utils/extensions/CommentListExt.kt
  app/src/main/java/com/kickstarter/mock/factories/CommentFactory.kt
  app/src/main/java/com/kickstarter/models/Comment.kt
  app/src/main/java/com/kickstarter/models/extensions/CommentExt.kt
  app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
  app/src/main/java/com/kickstarter/ui/viewholders/CommentCardViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/RootCommentViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ThreadViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.kt
Labels: feature ✨
