Repository kickstarter/android-oss, pull requests merged in 2022-09, with the labels that each got.

#1681 NTV-603: Mark as received UI inconsistent behaviour
  app/src/main/java/com/kickstarter/libs/utils/RewardUtils.kt
  app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
  app/src/main/res/layout/fragment_backing_section_reward_delivery.xml
  app/src/test/java/com/kickstarter/viewmodels/BackingFragmentViewModelTest.kt
Labels: bug 🐛

#1684 NTV-607 : upgrade facebook sdk to latest for android 13
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/ui/viewholders/ThanksShareViewHolder.kt
  app/src/main/res/values/strings_config.xml
Labels: migration

#1686 NTV-591: Android 13
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/libs/braze/BrazeClient.kt
  app/src/main/java/com/kickstarter/libs/htmlparser/ElementExt.kt
  app/src/main/java/com/kickstarter/libs/perimeterx/PerimeterXClient.kt
  app/src/main/java/com/kickstarter/libs/rx/operators/ApiErrorOperator.kt
  app/src/main/java/com/kickstarter/libs/utils/AnalyticEventsUtils.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/ContextExt.kt
  app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
  app/src/main/java/com/kickstarter/ui/SharedPreferenceKey.kt
  app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/ui/views/CommentCard.kt
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/MessagesViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentLegacyViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardsFragmentViewModel.kt
  app/src/test/java/com/kickstarter/libs/InAppCustomListenerHandlerTest.kt
  app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.kt
  build.gradle
Labels: feature ✨

#1687 PAY-1895: Present PaymentSheet on user settings
  app/src/main/graphql/checkout.graphql
  app/src/main/graphql/schema.json
  app/src/main/java/com/kickstarter/libs/utils/extensions/ContextExt.kt
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/services/ApolloClientType.kt
  app/src/main/java/com/kickstarter/services/KSApolloClient.kt
  app/src/main/java/com/kickstarter/ui/activities/PaymentMethodsSettingsActivity.kt
  app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/PaymentMethodsViewModel.kt
  app/src/main/res/layout/activity_settings_payment_methods.xml
  app/src/test/java/com/kickstarter/viewmodels/PaymentMethodsViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Labels: feature ✨

#1688 PAY-1899: Save payment method
  app/src/main/graphql/payments.graphql
  app/src/main/java/com/kickstarter/services/KSApolloClient.kt
  app/src/main/java/com/kickstarter/services/mutations/SavePaymentMethodData.kt
  app/src/main/java/com/kickstarter/ui/activities/PaymentMethodsSettingsActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/PaymentMethodsViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/PaymentMethodsViewModelTest.kt
Labels: feature ✨

#1689 PAY-1950: ViewModel architecture component + RXJava 2
  app/build.gradle
  app/src/external/java/com/kickstarter/ExternalApplicationModule.java
  app/src/internal/java/com/kickstarter/InternalApplicationModule.java
  app/src/main/java/com/kickstarter/ApplicationModule.java
  app/src/main/java/com/kickstarter/libs/Environment.kt
  app/src/main/java/com/kickstarter/libs/rx/transformers/ErrorsTransformerV2.kt
  app/src/main/java/com/kickstarter/libs/rx/transformers/NeverErrorTransformerV2.kt
  app/src/main/java/com/kickstarter/libs/rx/transformers/TakeWhenTransformerV2.kt
  app/src/main/java/com/kickstarter/libs/rx/transformers/Transformers.java
  app/src/main/java/com/kickstarter/libs/rx/transformers/ValuesTransformerV2.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/ContextExt.kt
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
  app/src/main/java/com/kickstarter/ui/activities/PaymentMethodsSettingsActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/PaymentMethodsViewModel.kt
  app/src/test/java/com/kickstarter/KSRobolectricTestCase.kt
  app/src/test/java/com/kickstarter/viewmodels/PaymentMethodsViewModelTest.kt
Labels: maintenance 🗜

#1690 NTV-622: Internal builds not being generated
  .circleci/config.yml
Labels: maintenance 🗜

#1694 PAY-1988: Fixed 3DS validation error
  app/src/main/java/com/kickstarter/ui/activities/PaymentMethodsSettingsActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/PaymentMethodsViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/PaymentMethodsViewModelTest.kt
Labels: bug 🐛

#1693 WEB-747
  app/src/main/res/layout/comment_card.xml
Labels: bug 🐛, UI 🎨
