Repository kickstarter/android-oss, pull requests merged in 2022-11, with the labels that each got.

#1704 NTV-628: Android Studio Dolphin
  app/build.gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: maintenance 🗜

#1706 [no-jira]: Fix Hide backer tag when video clicked
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/ui/views/MediaHeader.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectPageViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectPageViewModelTest.kt
Labels: bug 🐛

#1707 PAY-2067: Block links & pledge button when loading PaymentSheet
  app/internal_version_code.txt
  app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Labels: bug 🐛

#1708 PAY-1526: Removed feature flag for Local pickup
  app/src/main/java/com/kickstarter/libs/models/OptimizelyFeature.kt
  app/src/main/java/com/kickstarter/viewmodels/AddOnViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingAddOnViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentLegacyViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/AddOnViewHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentLegacyViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardViewHolderViewModelTest.kt
Labels: feature ✨

#1709 NTV-141 : New comments disappearing on pagination
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ThreadViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ThreadViewModelTest.kt
Labels: bug 🐛

#1710 PAY-2080: Retry pledge after error with PaymentSheet
  app/build.gradle
  app/src/main/java/com/kickstarter/libs/utils/extensions/ProjectExt.kt
  app/src/main/java/com/kickstarter/ui/activities/ActivityFeedActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ThanksActivity.kt
  app/src/main/java/com/kickstarter/ui/fragments/DiscoveryFragment.kt
  app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
  app/src/main/java/com/kickstarter/ui/fragments/RewardsFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/ProjectExtTest.kt
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Labels: bug 🐛, maintenance 🗜
