Repository kickstarter/android-oss, pull requests merged in 2022-04, with the labels that each got.

#1586 NTV-468 :Migrate CheckoutData.java to kotlin and deprecate Autoparcel
  app/src/main/java/com/kickstarter/mock/factories/CheckoutDataFactory.kt
  app/src/main/java/com/kickstarter/ui/data/CheckoutData.kt
  app/src/test/java/com/kickstarter/models/CheckoutDataTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ThanksViewModelTest.java
  jacoco.gradle
Labels: migration

#1589 NTV-436: Migrate Reftag.java to kotlin and deprecate Autoparcel
  app/src/main/java/com/kickstarter/libs/RefTag.java
  app/src/main/java/com/kickstarter/libs/RefTag.kt
  app/src/test/java/com/kickstarter/models/RefTagTest.kt
Labels: maintenance 🗜, migration

#1590 NTV-472 : Migrate ResetPasswordBody.java to kotlin and deprecate Autoparcel
  app/src/main/java/com/kickstarter/services/apirequests/ResetPasswordBody.java
  app/src/main/java/com/kickstarter/services/apirequests/ResetPasswordBody.kt
  app/src/test/java/com/kickstarter/models/ResetPasswordBodyTest.kt
Labels: migration

#1591 NTV-474 :Migrate SignupBody.java to kotlin and deprecate Autoparcel
  app/src/main/java/com/kickstarter/services/apirequests/SignupBody.java
  app/src/main/java/com/kickstarter/services/apirequests/SignupBody.kt
  app/src/test/java/com/kickstarter/models/SignupBodyTest.kt
Labels: maintenance 🗜

#1592 NTV-476 :Migrate AccessTokenEnvelope.java to kotlin and deprecate Autoparcel
  app/src/main/java/com/kickstarter/services/apiresponses/AccessTokenEnvelope.java
  app/src/main/java/com/kickstarter/services/apiresponses/AccessTokenEnvelope.kt
  app/src/test/java/com/kickstarter/models/AccessTokenEnvelopeTest.kt
Labels: maintenance 🗜

#1593 NTV-475: Migrate XauthBody.java to kotlin and deprecate Autoparcel
  app/src/main/java/com/kickstarter/services/apirequests/XauthBody.java
  app/src/main/java/com/kickstarter/services/apirequests/XauthBody.kt
  app/src/test/java/com/kickstarter/models/XauthBodyTest.kt
Labels: migration

#1597 NTV-492 :Deprecate Autoparcel for EmailVerificationEnvelope.kt
  app/src/main/java/com/kickstarter/services/apiresponses/EmailVerificationEnvelope.kt
  app/src/test/java/com/kickstarter/models/EmailVerificationEnvelopeTest.kt
Labels: maintenance 🗜

#1598 NTV-515: Hotfix for 3.1.1
  app/build.gradle
  app/external_version_code.txt
  app/external_version_name.txt
  app/internal_version_code.txt
  app/internal_version_name.txt
  app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/ui/fragments/DiscoveryFragment.kt
Labels: bug 🐛, release 🚀

#1595 NTV-482 :Migrate MessageThreadEnvelope.java and MessageThreadsEnvelope.java t…
  app/src/main/java/com/kickstarter/mock/factories/MessageThreadEnvelopeFactory.java
  app/src/main/java/com/kickstarter/mock/factories/MessageThreadEnvelopeFactory.kt
  app/src/main/java/com/kickstarter/mock/factories/MessageThreadsEnvelopeFactory.java
  app/src/main/java/com/kickstarter/mock/factories/MessageThreadsEnvelopeFactory.kt
  app/src/main/java/com/kickstarter/services/apiresponses/MessageThreadEnvelope.java
  app/src/main/java/com/kickstarter/services/apiresponses/MessageThreadEnvelope.kt
  app/src/main/java/com/kickstarter/services/apiresponses/MessageThreadsEnvelope.java
  app/src/main/java/com/kickstarter/services/apiresponses/MessageThreadsEnvelope.kt
  app/src/test/java/com/kickstarter/models/MessageThreadEnvelopeTest.kt
  app/src/test/java/com/kickstarter/models/MessageThreadsEnvelopeTest.kt
Labels: maintenance 🗜, migration

#1601 NTV-488: Migrate DiscoveryFilterStyle.java to kotlin and deprecate Autoparcel
  app/src/main/java/com/kickstarter/ui/DiscoveryFilterStyle.java
  app/src/main/java/com/kickstarter/ui/DiscoveryFilterStyle.kt
  app/src/test/java/com/kickstarter/ui/DiscoveryFilterStyleTest.kt
Labels: maintenance 🗜, migration

#1603 NTV-490: Migrate ActivityResult.java to kotlin and deprecate Autoparcel
  app/src/main/java/com/kickstarter/ui/data/ActivityResult.java
  app/src/main/java/com/kickstarter/ui/data/ActivityResult.kt
  app/src/test/java/com/kickstarter/models/ActivityResultTest.kt
Labels: maintenance 🗜, migration

#1596 NTV-491:Deprecate Autoparcel for StoredCard.kt
  app/src/main/java/com/kickstarter/mock/factories/StoredCardFactory.kt
  app/src/main/java/com/kickstarter/models/StoredCard.kt
  app/src/test/java/com/kickstarter/models/StoredCardTest.kt
Labels: maintenance 🗜

#1600 NTV-442 : Migrate ActivityEnvelope.java to kotlin and deprecate Autoparcel
  app/src/main/java/com/kickstarter/mock/factories/ActivityEnvelopeFactory.java
  app/src/main/java/com/kickstarter/mock/factories/ActivityEnvelopeFactory.kt
  app/src/main/java/com/kickstarter/services/apiresponses/ActivityEnvelope.java
  app/src/main/java/com/kickstarter/services/apiresponses/ActivityEnvelope.kt
  app/src/test/java/com/kickstarter/models/ActivityEnvelopeTest.kt
Labels: maintenance 🗜, migration

#1602 NTV-469: Migrate PushTokenBody.java to kotlin and deprecate Autoparcel
  app/src/main/java/com/kickstarter/services/apirequests/PushTokenBody.java
  app/src/main/java/com/kickstarter/services/apirequests/PushTokenBody.kt
  app/src/test/java/com/kickstarter/services/apirequests/PushTokenBodyTest.kt
Labels: maintenance 🗜, migration

#1604 NTV-489 :Migrate NavigationDrawerData.java to kotlin and deprecate Autoparcel
  app/src/main/java/com/kickstarter/ui/adapters/data/NavigationDrawerData.java
  app/src/main/java/com/kickstarter/ui/adapters/data/NavigationDrawerData.kt
  app/src/test/java/com/kickstarter/models/NavigationDrawerDataTest.kt
Labels: maintenance 🗜, migration

#1605 NTV-478 Migrate CategoriesEnvelope.java to kotlin and deprecate Autoparcel
  app/src/main/java/com/kickstarter/services/apiresponses/CategoriesEnvelope.java
  app/src/main/java/com/kickstarter/services/apiresponses/CategoriesEnvelope.kt
  app/src/test/java/com/kickstarter/models/CategoriesEnvelopeTest.kt
Labels: maintenance 🗜, migration

#1606 NTV-487: Migrate UpdatesEnvelop.java to kotlin and deprecate Autoparcel
  app/src/main/java/com/kickstarter/services/apiresponses/UpdatesEnvelope.java
  app/src/main/java/com/kickstarter/services/apiresponses/UpdatesEnvelope.kt
  app/src/test/java/com/kickstarter/services/apiresponses/UpdatesEnvelopeTest.kt
Labels: maintenance 🗜, migration

#1607 NTV-485: Migrate ProjectsEnvelope.java to kotlin and deprecate Autoparcel
  app/src/main/java/com/kickstarter/services/apiresponses/ProjectsEnvelope.java
  app/src/main/java/com/kickstarter/services/apiresponses/ProjectsEnvelope.kt
  app/src/test/java/com/kickstarter/services/apiresponses/ProjectsEnvelopeTest.kt
Labels: maintenance 🗜, migration

#1608 NTV-530: ApiOperator.java crash
  app/src/main/java/com/kickstarter/libs/rx/operators/ApiErrorOperator.java
  app/src/main/java/com/kickstarter/services/apiresponses/ErrorEnvelope.java
  app/src/main/java/com/kickstarter/services/apiresponses/ErrorEnvelope.kt
  app/src/test/java/com/kickstarter/libs/rx/operators/ApiErrorOperatorTest.java
  app/src/test/java/com/kickstarter/models/ErrorEnvelopeTest.kt
  app/src/test/java/com/kickstarter/viewmodels/FacebookConfimationViewModelTest.java
Labels: bug 🐛

#1609 NTV-494: Deprecate Autoparcel for ProjectData.kt
  app/src/main/java/com/kickstarter/mock/factories/ProjectDataFactory.kt
  app/src/main/java/com/kickstarter/ui/data/ProjectData.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/PledgeDataExtTest.kt
  app/src/test/java/com/kickstarter/models/ProjectDataTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectOverviewViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectUpdatesViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/ThanksViewModelTest.java
Labels: maintenance 🗜, migration

#1613 PAY-1524: Added new feature flag + updated Schema.json
  app/src/main/graphql/fragments.graphql
  app/src/main/graphql/schema.json
  app/src/main/java/com/kickstarter/libs/models/OptimizelyFeature.kt
Labels: feature ✨

#1614 PAY-1571: Rewards Carousel can display localReceiptLocation UI
  app/src/main/java/com/kickstarter/libs/utils/RewardUtils.kt
  app/src/main/java/com/kickstarter/mock/factories/RewardFactory.kt
  app/src/main/java/com/kickstarter/models/Reward.kt
  app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
  app/src/main/java/com/kickstarter/ui/viewholders/RewardViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
  app/src/main/res/layout/add_on_card.xml
  app/src/main/res/layout/item_add_on.xml
  app/src/main/res/layout/item_reward.xml
  app/src/main/res/layout/reward_item_local_pickup.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/kickstarter/libs/utils/RewardUtilsTest.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardViewHolderViewModelTest.kt
Labels: feature ✨, UI 🎨

#1616 [No-jira]: Update schema.json
  app/src/main/graphql/schema.json
Labels: maintenance 🗜

#1617 PAY-1521: Pledge Screen show localReceiptLocation UI
  app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
  app/src/main/java/com/kickstarter/ui/viewholders/AddOnViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/AddOnViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/main/res/layout/fragment_pledge.xml
  app/src/main/res/layout/fragment_pledge_section_local_pickup.xml
  app/src/main/res/layout/item_add_on.xml
  app/src/test/java/com/kickstarter/viewmodels/AddOnViewHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Labels: feature ✨, UI 🎨

#1618 NTV-479 :Migrate Activity.java Push model to kotlin and deprecate Autoparcel
  app/src/internal/java/com/kickstarter/ui/views/DebugPushNotificationsView.kt
  app/src/main/java/com/kickstarter/models/pushdata/Activity.java
  app/src/main/java/com/kickstarter/models/pushdata/Activity.kt
  app/src/test/java/com/kickstarter/models/pushdata/ActivityTest.kt
Labels: migration
