Repository kickstarter/android-oss, pull requests merged in 2022-12, with the labels that each got.

#1711 NTV-601 : Android displaying inaccurate estimated delivery date
  app/src/main/java/com/kickstarter/libs/utils/AnalyticEventsUtils.kt
  app/src/main/java/com/kickstarter/libs/utils/DateTimeUtils.kt
  app/src/main/java/com/kickstarter/mock/factories/RewardFactory.kt
  app/src/main/java/com/kickstarter/models/Reward.kt
  app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/libs/utils/DateTimeUtilsTest.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardViewHolderViewModelTest.kt
Labels: bug 🐛

#1712 PAY-2077: Updating amount using input text on update pledge flow did not enabled button
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentLegacyViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentLegacyViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Labels: bug 🐛

#1715 NTV-364: [Regression bug] Creator dashboard not loading for release 3.7.0
  app/src/main/java/com/kickstarter/libs/utils/AnalyticEventsUtils.kt
  app/src/main/java/com/kickstarter/libs/utils/DateTimeUtils.kt
  app/src/main/java/com/kickstarter/mock/factories/RewardFactory.kt
  app/src/main/java/com/kickstarter/models/Reward.kt
  app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/libs/utils/DateTimeUtilsTest.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardViewHolderViewModelTest.kt
Labels: bug 🐛

#1716 NTV-637: Messages screen unable to load more messages
  app/src/main/java/com/kickstarter/libs/RecyclerViewPaginator.java
  app/src/main/res/layout/message_thread_view.xml
Labels: bug 🐛

#1717 WEB-845 : [Android] Migrate Updates Service from V1 to graphQl
  app/src/main/graphql/fragments.graphql
  app/src/main/graphql/project.graphql
  app/src/main/graphql/schema.json
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/models/Update.kt
  app/src/main/java/com/kickstarter/services/ApolloClientType.kt
  app/src/main/java/com/kickstarter/services/KSApolloClient.kt
  app/src/main/java/com/kickstarter/services/apiresponses/updatesresponse/UpdatesGraphQlEnvelope.kt
  app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectUpdatesActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectUpdatesViewModel.kt
  app/src/main/res/layout/activity_updates.xml
  app/src/test/java/com/kickstarter/services/GraphQLTransformersTest.kt
  app/src/test/java/com/kickstarter/services/apiresponses/UpdatesGraphQlEnvelopeTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectUpdatesViewModelTest.kt
Labels: bug 🐛

#1718 PAY-2100: Compose spike
  app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectRiskFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectRiskViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectRiskViewModelTest.kt
Labels: maintenance 🗜, migration

#1719 WEB-827: Add Page Viewed analytic to Creator Dashboard
  app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
  app/src/main/java/com/kickstarter/libs/utils/EventContextValues.kt
  app/src/main/java/com/kickstarter/viewmodels/CreatorDashboardViewModel.kt
  app/src/test/java/com/kickstarter/libs/SegmentTest.kt
Labels: events 🛤

#1720 WEB-856: Create feature flag for consent management
  app/src/main/java/com/kickstarter/libs/models/OptimizelyFeature.kt
Labels: feature ✨

#1721 WEB-833: CTA Clicked event on creator dashboard "select another project" button
  app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
  app/src/main/java/com/kickstarter/libs/utils/EventContextValues.kt
  app/src/main/java/com/kickstarter/viewmodels/CreatorDashboardViewModel.kt
  app/src/test/java/com/kickstarter/libs/SegmentTest.kt
  app/src/test/java/com/kickstarter/viewmodels/CreatorDashboardViewModelTest.kt
Labels: events 🛤
