Repository kickstarter/android-oss, pull requests merged in 2022-08, with the labels that each got.

#1672 WEB-688 :[Android ]Forget Password screen back few times
  app/src/main/java/com/kickstarter/libs/ActivityRequestCodes.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/IntentExt.kt
  app/src/main/java/com/kickstarter/ui/activities/LoginActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ResetPasswordActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/LoginViewModel.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/IntentExtTest.kt
  app/src/test/java/com/kickstarter/viewmodels/LoginViewModelTest.kt
Labels: bug 🐛

#1670 PAY-1814: Loading states
  app/src/androidTest/java/com/kickstarter/screenshoot/testing/ui/components/TextViewElementShotTest.kt
  app/src/main/java/com/kickstarter/ui/adapters/RewardCardAdapter.kt
  app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
  app/src/main/java/com/kickstarter/ui/viewholders/AddCardViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/ui/viewholders/RewardAddCardViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/main/res/layout/item_add_card.xml
  app/src/test/java/com/kickstarter/viewmodels/AddCardViewHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Labels: feature ✨, UI 🎨

#1675 NTV-597: Appboy 12.0.0
  app/build.gradle
  app/src/main/java/com/kickstarter/libs/braze/BrazeClient.kt
  app/src/test/java/com/kickstarter/libs/InAppCustomListenerHandlerTest.kt
  build.gradle
Labels: maintenance 🗜

#1676 NTV-594: Appboy 13.0.0
  app/build.gradle
  app/src/main/java/com/kickstarter/libs/braze/BrazeClient.kt
Labels: maintenance 🗜

#1677 NTV-598: kotlin 1.7.10
  app/build.gradle
  app/src/main/java/com/kickstarter/libs/htmlparser/ElementExt.kt
  app/src/main/java/com/kickstarter/libs/perimeterx/PerimeterXClient.kt
  app/src/main/java/com/kickstarter/libs/rx/operators/ApiErrorOperator.kt
  app/src/main/java/com/kickstarter/libs/utils/AnalyticEventsUtils.kt
  app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
  app/src/main/java/com/kickstarter/ui/views/CommentCard.kt
  app/src/main/java/com/kickstarter/viewmodels/MessagesViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentLegacyViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardsFragmentViewModel.kt
  build.gradle
Labels: maintenance 🗜

#1678 NTV-602 && SD-1499: Crash when opening updates for concrete project
  app/src/main/java/com/kickstarter/libs/utils/extensions/IntentExt.kt
  app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt
  app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectOverviewFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectUpdatesViewModel.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/IntentExtTest.kt
Labels: bug 🐛

#1683 PAY-1931: Upgrade stripe SDK to latest version
  app/build.gradle
Labels: feature ✨
