Repository kickstarter/android-oss, pull requests merged in 2022-02, with the labels that each got.

#1531 NTV-365 Migrate to Kotlin `DiscoveryAdapter.java`
  app/src/main/java/com/kickstarter/ui/adapters/DiscoveryActivitySampleAdapter.kt
  app/src/main/java/com/kickstarter/ui/adapters/DiscoveryAdapter.java
  app/src/main/java/com/kickstarter/ui/adapters/DiscoveryEditorialAdapter.kt
  app/src/main/java/com/kickstarter/ui/adapters/DiscoveryOnboardingAdapter.kt
  app/src/main/java/com/kickstarter/ui/adapters/DiscoveryProjectCardAdapter.kt
  app/src/main/java/com/kickstarter/ui/fragments/DiscoveryFragment.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ActivitySampleFriendBackingViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ActivitySampleFriendFollowViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ActivitySampleProjectViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/DiscoveryOnboardingViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/ActivitySampleFriendBackingViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ActivitySampleFriendFollowViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ActivitySampleProjectViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/outputs/DiscoveryFragmentViewModelInputs.java
  app/src/test/java/com/kickstarter/viewmodels/ActivitySampleFriendBackingViewHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ActivitySampleFriendFollowViewHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ActivitySampleProjectViewHolderViewModelTest.kt
Labels: migration

#1534 NTV-362: Selectable text
  app/src/main/res/layout/environmental_commitments_card.xml
  app/src/main/res/layout/fragment_project_overview.xml
  app/src/main/res/layout/fragment_project_risks.xml
  app/src/main/res/layout/frequently_asked_question_card.xml
  app/src/main/res/layout/project_creator_info.xml
  app/src/main/res/layout/project_stats_view.xml
  app/src/main/res/layout/view_element_header.xml
  app/src/main/res/layout/view_element_text_from_html.xml
  app/src/main/res/layout/view_image_with_caption.xml
Labels: UI 🎨

#1535 [no-jira]: percentage funded
  app/src/main/graphql/fragments.graphql
  app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
Labels: bug 🐛

#1532 NTV-372: Update braze/segment dependency to 10.0.0
  app/build.gradle
  app/src/main/java/com/kickstarter/libs/braze/BrazeClient.kt
  app/src/main/java/com/kickstarter/libs/braze/InAppCustomListener.kt
  app/src/test/java/com/kickstarter/libs/InAppCustomListenerHandlerTest.kt
Labels: maintenance 🗜

#1537 NTV-349 Add Save Project button to cards on Discovery
  app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/ProjectExt.kt
  app/src/main/java/com/kickstarter/models/extensions/AvatarExt.kt
  app/src/main/java/com/kickstarter/ui/activities/ThanksActivity.kt
  app/src/main/java/com/kickstarter/ui/adapters/ThanksAdapter.java
  app/src/main/java/com/kickstarter/ui/adapters/data/ThanksData.kt
  app/src/main/java/com/kickstarter/ui/fragments/DiscoveryFragment.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ActivitySampleFriendBackingViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ActivitySampleFriendFollowViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ActivitySampleProjectViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ProjectCardViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectCardHolderViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/ProjectCardHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ThanksViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/ThanksViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectPageViewModel.kt
  app/src/main/res/layout/project_card_view.xml
  app/src/test/java/com/kickstarter/libs/utils/extensions/AvatarExtTest.kt
  app/src/test/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/ProjectCardHolderViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/ThanksViewModelTest.java
Labels: feature ✨

#1539 NTV-360: Zoom on campaign images
  app/build.gradle
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/ui/extensions/ImageViewExt.kt
  app/src/main/java/com/kickstarter/ui/views/ImageWithCaptionView.kt
  app/src/main/res/layout/view_image_with_caption.xml
  build.gradle
Labels: UI 🎨

#1541 NTV-397: Clickable images on campaign
  app/src/main/java/com/kickstarter/ui/viewholders/projectcampaign/ImageElementViewHolder.kt
  app/src/main/java/com/kickstarter/ui/views/ImageWithCaptionView.kt
Labels: UI 🎨

#1542 NTV-395: UI – Out of place image captions
  app/src/main/java/com/kickstarter/ui/viewholders/projectcampaign/ImageElementViewHolder.kt
  app/src/main/java/com/kickstarter/ui/views/ImageWithCaptionView.kt
Labels: bug 🐛, UI 🎨

#1543 NTV-406: Remove old ProjectActivity and clean feature flag
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/libs/PushNotifications.java
  app/src/main/java/com/kickstarter/libs/models/OptimizelyFeature.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/IntentExt.kt
  app/src/main/java/com/kickstarter/models/Project.kt
  app/src/main/java/com/kickstarter/ui/activities/ActivityFeedActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/DeepLinkActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ProfileActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/SearchActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ThanksActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/UpdateActivity.kt
  app/src/main/java/com/kickstarter/ui/adapters/ProjectAdapter.java
  app/src/main/java/com/kickstarter/ui/fragments/DiscoveryFragment.kt
  app/src/main/java/com/kickstarter/ui/viewholders/CreatorDashboardHeaderViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ProjectViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/ActivityFeedViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/CreatorDashboardBottomSheetHolderViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/CreatorDashboardBottomSheetHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/CreatorDashboardHeaderHolderViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/CreatorDashboardHeaderHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/DeepLinkViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ProfileViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectHolderViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/SearchViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/SearchViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ThanksViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/UpdateViewModel.kt
  app/src/main/res/layout/activity_project.xml
  app/src/main/res/layout/project_creator_info.xml
  app/src/test/java/com/kickstarter/libs/utils/extensions/IntentExtTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ActivityFeedViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/CreatorDashboardHeaderHolderViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/DeepLinkViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/ProfileViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectHolderViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/SearchViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/ThanksViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/UpdateViewModelTest.java
Labels: maintenance 🗜

#1544 NTV-410: Upgrade stripe SDK
  app/build.gradle
  app/src/main/java/com/kickstarter/ui/fragments/NewCardFragment.kt
Labels: maintenance 🗜

#1547 NTV-412: Hide old campaign links
  app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectOverviewFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectOverviewViewModel.kt
  app/src/main/res/layout/fragment_project_overview.xml
  app/src/test/java/com/kickstarter/viewmodels/ProjectOverviewViewModelTest.kt
Labels: UI 🎨
