Repository kickstarter/android-oss, pull requests merged in 2022-01, with the labels that each got.

#1498 NTV-273: Location Model
  app/src/main/java/com/kickstarter/mock/factories/LocationFactory.java
  app/src/main/java/com/kickstarter/mock/factories/LocationFactory.kt
  app/src/main/java/com/kickstarter/models/Location.java
  app/src/main/java/com/kickstarter/models/Location.kt
  app/src/test/java/com/kickstarter/models/LocationTest.kt
Labels: maintenance 🗜, migration

#1491 NTV-329 :Picasso IllegalArgumentException error on 3.0.0
  app/src/main/java/com/kickstarter/ui/viewholders/ProjectViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectHolderViewModel.java
Labels: bug 🐛

#1501 NTV-315: Migrate ComparatorUtils.java to kotlin FloatExt
  app/src/main/java/com/kickstarter/libs/utils/ComparatorUtils.java
  app/src/main/java/com/kickstarter/libs/utils/extensions/FloatExt.kt
  app/src/main/java/com/kickstarter/viewmodels/CreatorDashboardReferrerStatsHolderViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/CreatorDashboardRewardStatsHolderViewModel.java
  app/src/test/java/com/kickstarter/libs/utils/extensions/FloatExtKtTest.kt
Labels: migration

#1500 NTV-274: User model
  app/src/main/java/com/kickstarter/libs/OptimizelyExperimentsClient.kt
  app/src/main/java/com/kickstarter/libs/utils/AnalyticEventsUtils.kt
  app/src/main/java/com/kickstarter/mock/factories/CommentFactory.kt
  app/src/main/java/com/kickstarter/mock/factories/UpdateFactory.java
  app/src/main/java/com/kickstarter/mock/factories/UserFactory.java
  app/src/main/java/com/kickstarter/mock/factories/UserFactory.kt
  app/src/main/java/com/kickstarter/models/Avatar.kt
  app/src/main/java/com/kickstarter/models/EnvironmentalCommitment.kt
  app/src/main/java/com/kickstarter/models/Location.kt
  app/src/main/java/com/kickstarter/models/ProjectFaq.kt
  app/src/main/java/com/kickstarter/models/User.java
  app/src/main/java/com/kickstarter/models/User.kt
  app/src/main/java/com/kickstarter/models/extensions/UserExt.kt
  app/src/main/java/com/kickstarter/ui/intentmappers/ProjectIntentMapper.java
  app/src/main/java/com/kickstarter/ui/intentmappers/ProjectIntentMapper.kt
  app/src/main/java/com/kickstarter/viewmodels/MessageThreadsViewModel.java
  app/src/test/java/com/kickstarter/libs/utils/extensions/UserExtensionTest.kt
  app/src/test/java/com/kickstarter/ui/intents/ProjectIntentMapperTest.java
  app/src/test/java/com/kickstarter/ui/intents/ProjectIntentMapperTest.kt
  app/src/test/java/com/kickstarter/viewmodels/MessageHolderViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/ThanksShareHolderViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/UpdateViewModelTest.java
Labels: maintenance 🗜, migration

#1502 NTV-332: Category Model
  app/src/main/java/com/kickstarter/libs/utils/AnalyticEventsUtils.kt
  app/src/main/java/com/kickstarter/mock/factories/CategoryFactory.java
  app/src/main/java/com/kickstarter/mock/factories/CategoryFactory.kt
  app/src/main/java/com/kickstarter/models/Category.java
  app/src/main/java/com/kickstarter/models/Category.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/ProjectExtTest.kt
  app/src/test/java/com/kickstarter/models/CategoryTest.java
  app/src/test/java/com/kickstarter/models/CategoryTest.kt
Labels: maintenance 🗜, migration

#1503 NTV-333: RewardItems, Item Models
  app/src/main/java/com/kickstarter/mock/factories/ItemFactory.java
  app/src/main/java/com/kickstarter/mock/factories/ItemFactory.kt
  app/src/main/java/com/kickstarter/mock/factories/RewardsItemFactory.java
  app/src/main/java/com/kickstarter/mock/factories/RewardsItemFactory.kt
  app/src/main/java/com/kickstarter/models/Item.java
  app/src/main/java/com/kickstarter/models/Item.kt
  app/src/main/java/com/kickstarter/models/RewardsItem.java
  app/src/main/java/com/kickstarter/models/RewardsItem.kt
  app/src/main/java/com/kickstarter/ui/viewholders/RewardsItemViewHolder.kt
  app/src/test/java/com/kickstarter/models/ItemTest.kt
  app/src/test/java/com/kickstarter/models/RewardsItemTest.kt
Labels: maintenance 🗜, migration

#1496 NTV-306 : Migrate to Kotlin Extension Discovery Utils classes
  app/src/main/java/com/kickstarter/libs/utils/AnalyticEventsUtils.kt
  app/src/main/java/com/kickstarter/libs/utils/DiscoveryDrawerUtils.java
  app/src/main/java/com/kickstarter/libs/utils/DiscoveryParamsUtils.java
  app/src/main/java/com/kickstarter/libs/utils/DiscoveryUtils.java
  app/src/main/java/com/kickstarter/libs/utils/DiscoveryUtils.kt
  app/src/main/java/com/kickstarter/libs/utils/RefTagUtils.java
  app/src/main/java/com/kickstarter/libs/utils/extensions/DiscoveryParamsExt.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/ProjectExt.kt
  app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.kt
  app/src/main/java/com/kickstarter/ui/adapters/DiscoveryPagerAdapter.java
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.kt
  app/src/test/java/com/kickstarter/libs/utils/DiscoverDrawerUtilsTests.java
  app/src/test/java/com/kickstarter/libs/utils/DiscoveryParamsUtilsTest.java
  app/src/test/java/com/kickstarter/libs/utils/extensions/DiscoveryParamsExtKtTest.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/ProjectExtTest.kt
  app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.java
Labels: migration

#1504 NTV-337: PaymentSource Model
  app/src/main/java/com/kickstarter/mock/factories/PaymentSourceFactory.kt
  app/src/main/java/com/kickstarter/models/Backing.java
  app/src/main/java/com/kickstarter/models/PaymentSource.kt
  app/src/main/java/com/kickstarter/services/KSApolloClient.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
Labels: maintenance 🗜, migration

#1508 NTV-335: Backing model
  app/src/main/java/com/kickstarter/mock/factories/BackingFactory.java
  app/src/main/java/com/kickstarter/mock/factories/BackingFactory.kt
  app/src/main/java/com/kickstarter/mock/factories/ProjectFactory.java
  app/src/main/java/com/kickstarter/mock/factories/ProjectFactory.kt
  app/src/main/java/com/kickstarter/mock/services/MockApiClient.java
  app/src/main/java/com/kickstarter/mock/services/MockApiClient.kt
  app/src/main/java/com/kickstarter/models/Backing.java
  app/src/main/java/com/kickstarter/models/Backing.kt
  app/src/main/java/com/kickstarter/models/Location.kt
  app/src/main/java/com/kickstarter/services/apirequests/BackingBody.java
  app/src/main/java/com/kickstarter/services/apirequests/BackingBody.kt
  app/src/test/java/com/kickstarter/models/BackingBodyTest.kt
  app/src/test/java/com/kickstarter/viewmodels/EditorialViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectNotificationSettingsViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ThanksViewModelTest.java
Labels: maintenance 🗜, migration

#1509 NTV-50 :Posting a (root) comment
  app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
  app/src/main/java/com/kickstarter/libs/utils/EventContextValues.kt
  app/src/main/java/com/kickstarter/libs/utils/EventKeys.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
  app/src/test/java/com/kickstarter/libs/SegmentTest.kt
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.kt
Labels: events 🛤

#1510 NTV-336: Project Model
  app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
  app/src/main/java/com/kickstarter/libs/utils/AnalyticEventsUtils.kt
  app/src/main/java/com/kickstarter/libs/utils/ProjectViewUtils.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/ProjectExt.kt
  app/src/main/java/com/kickstarter/mock/factories/ProjectFactory.kt
  app/src/main/java/com/kickstarter/mock/services/MockApiClient.kt
  app/src/main/java/com/kickstarter/models/Api.kt
  app/src/main/java/com/kickstarter/models/Backing.kt
  app/src/main/java/com/kickstarter/models/Project.java
  app/src/main/java/com/kickstarter/models/Project.kt
  app/src/main/java/com/kickstarter/models/Reward.kt
  app/src/main/java/com/kickstarter/models/Urls.kt
  app/src/main/java/com/kickstarter/models/Web.kt
  app/src/main/java/com/kickstarter/services/KSApolloClient.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/ui/data/PledgeData.kt
  app/src/main/java/com/kickstarter/ui/viewholders/EmptyCommentsViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/CampaignDetailsViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/CreatorBioViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardsFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ThreadViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/UpdateCardViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/FrequentlyAskedQuestionViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectOverviewViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectPageViewModel.kt
  app/src/test/java/com/kickstarter/libs/SegmentTest.kt
  app/src/test/java/com/kickstarter/libs/utils/RefTagUtilsTest.java
  app/src/test/java/com/kickstarter/libs/utils/extensions/PledgeDataExtTest.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/ProjectExtTest.kt
  app/src/test/java/com/kickstarter/models/ProjectTest.java
  app/src/test/java/com/kickstarter/viewmodels/CampaignDetailsViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/CreatorDashboardReferrerStatsRowHolderViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/DashboardRewardStatsRowHolderViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectHolderViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/ProjectPageViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectSearchResultHolderViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/ProjectViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ThanksShareHolderViewModelTest.java
Labels: maintenance 🗜, migration

#1511 NTV-51 : Posting a reply
  app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
  app/src/main/java/com/kickstarter/libs/utils/EventContextValues.kt
  app/src/main/java/com/kickstarter/libs/utils/EventKeys.kt
  app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ThreadViewModel.kt
  app/src/test/java/com/kickstarter/libs/SegmentTest.kt
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ThreadViewModelTest.kt
Labels: events 🛤

#1513 NTV-52 : Viewing (root) comments
  app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
  app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.kt
Labels: events 🛤

#1514 NTV-53:Viewing comment thread
  app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
  app/src/main/java/com/kickstarter/viewmodels/ThreadViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ThreadViewModelTest.kt
Labels: events 🛤

#1515 NTV-351 Segment – Add project_url to properties
  app/src/main/java/com/kickstarter/libs/utils/AnalyticEventsUtils.kt
  app/src/test/java/com/kickstarter/libs/SegmentTest.kt
Labels: events 🛤

#1517 NTV-53 :Viewing /Posting comment thread
  app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
  app/src/main/java/com/kickstarter/libs/utils/EventKeys.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ThreadViewModel.kt
  app/src/test/java/com/kickstarter/libs/SegmentTest.kt
Labels: events 🛤

#1516 NTV-339: getProjects from GraphQL queries
  app/src/main/graphql/fragments.graphql
  app/src/main/graphql/project.graphql
  app/src/main/java/com/kickstarter/libs/loadmore/ApolloPaginate.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/DiscoveryParamsExt.kt
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/services/ApolloClientType.kt
  app/src/main/java/com/kickstarter/services/KSApolloClient.kt
  app/src/main/java/com/kickstarter/services/apiresponses/DiscoverEnvelope.java
  app/src/main/java/com/kickstarter/services/apiresponses/DiscoverEnvelope.kt
  app/src/main/java/com/kickstarter/services/apiresponses/commentresponse/PageInfoEnvelope.kt
  app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/ProfileViewModel.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/DiscoveryParamsExtKtTest.kt
Labels: migration

#1518 NTV-353:Segment – Add project_image_url to properties
  app/src/main/java/com/kickstarter/libs/utils/AnalyticEventsUtils.kt
  app/src/test/java/com/kickstarter/libs/SegmentTest.kt
Labels: events 🛤

#1519 NTV-327: Copy formatting Errors
  app/src/main/assets/json/server-config.json
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/res/layout/activity_project_page.xml
  app/src/main/res/layout/fragment_frequently_asked_question.xml
  app/src/main/res/layout/fragment_project_environmental_commitments.xml
  app/src/main/res/values-de/strings_i18n.xml
  app/src/main/res/values-es/strings_i18n.xml
  app/src/main/res/values-fr/strings_i18n.xml
  app/src/main/res/values-ja/strings_i18n.xml
  app/src/main/res/values/strings_i18n.xml
Labels: events 🛤

#1521 NTV-357: Fix-crashes
  app/src/main/java/com/kickstarter/mock/factories/PhotoFactory.java
  app/src/main/java/com/kickstarter/mock/factories/PhotoFactory.kt
  app/src/main/java/com/kickstarter/models/Comment.java
  app/src/main/java/com/kickstarter/models/Comment.kt
  app/src/main/java/com/kickstarter/models/Photo.java
  app/src/main/java/com/kickstarter/models/Photo.kt
  app/src/main/java/com/kickstarter/models/extensions/CommentExt.kt
  app/src/main/java/com/kickstarter/services/KSApolloClient.kt
  app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
  app/src/main/java/com/kickstarter/ui/adapters/data/CommentsData.java
  app/src/main/java/com/kickstarter/ui/viewholders/RootCommentViewHolder.kt
  app/src/test/java/com/kickstarter/models/PhotoTest.kt
Labels: bug 🐛

#1523 NTV-359: Fix pledge with Reward+AddOns that are shippable
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Labels: bug 🐛

#1524 NTV-356: Joined queries to fecth projects
  app/src/main/graphql/project.graphql
  app/src/main/java/com/kickstarter/libs/utils/extensions/IntExt.kt
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/models/Category.kt
  app/src/main/java/com/kickstarter/services/ApolloClientType.kt
  app/src/main/java/com/kickstarter/services/KSApolloClient.kt
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
Labels: migration

#1527 NTV-363: Hide collection option Social
  app/src/main/java/com/kickstarter/libs/utils/extensions/DiscoveryParamsExt.kt
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.java
  app/src/test/java/com/kickstarter/libs/utils/extensions/DiscoveryParamsExtKtTest.kt
  app/src/test/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModelTest.java
Labels: migration

#1529 NTV-378: Bumblebee updates
  Gemfile.lock
  app/build.gradle
  app/lint.xml
  app/src/main/AndroidManifest.xml
  app/src/main/res/layout-land/app_rating_prompt.xml
  build.gradle
  fastlane/README.md
  gradle/wrapper/gradle-wrapper.properties
Labels: maintenance 🗜

#1530 NTV-367: Discovery drawer adapter
  app/src/main/java/com/kickstarter/ui/adapters/DiscoveryDrawerAdapter.java
  app/src/main/java/com/kickstarter/ui/adapters/DiscoveryDrawerAdapter.kt
Labels: migration
