Repository kickstarter/android-oss, pull requests merged in 2023-07, with the labels that each got.

#1816 fix visuals for compose version of change password, fix issue with error
  app/src/main/java/com/kickstarter/ui/activities/ChangePasswordActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/ChangePasswordScreen.kt
  app/src/main/java/com/kickstarter/viewmodels/ChangePasswordViewModel.kt
Labels: bug 🐛

#1815 MBL-886: Crash when no networking + duplicated network call
  app/src/main/java/com/kickstarter/services/apiresponses/ErrorEnvelope.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
  app/src/test/java/com/kickstarter/models/ErrorEnvelopeTest.kt
Labels: bug 🐛

#1817 MBL-874: Upgrades in preparation for API 34
  .circleci/config.yml
  app/build.gradle
  build.gradle
Labels: maintenance 🗜

#1818 [No Ticket] Fix loop of error handler
  app/src/main/java/com/kickstarter/ui/activities/ChangePasswordActivity.kt
Labels: bug 🐛

#1820 [NoTicket] Adjust usage and visuals of compose screen based on learnings
  app/src/internal/java/com/kickstarter/ui/activities/DesignSystemActivity.kt
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/ui/activities/ChangePasswordActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/ChangePasswordScreen.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSAlerts.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSTextInput.kt
Labels: UI 🎨, maintenance 🗜
