Repository kickstarter/android-oss, pull requests merged in 2023-08, with the labels that each got.

#1824 MBL-896: Added feature flag for new "Use of AI" tab
  app/src/main/java/com/kickstarter/libs/featureflag/FeatureFlagClient.kt
Labels: feature ✨

#1825 [MBL-881/909] Compose standards and dark mode feature flag
  app/build.gradle
  app/src/internal/java/com/kickstarter/ui/activities/DesignSystemActivity.kt
  app/src/main/java/com/kickstarter/libs/featureflag/FeatureFlagClient.kt
  app/src/main/java/com/kickstarter/ui/activities/ChangePasswordActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/ChangePasswordScreen.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSAlerts.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSBadges.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSButtons.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSControls.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSDimensions.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSFooters.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSProgressIndicators.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSStepper.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSTextInput.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSTheme.kt
Labels: refactor 🛠, internal tools 🛠

#1830 MBL-798: SetPasswordViewModel.kt to Jetpack ViewModel and RxJava2.2
  app/src/main/java/com/kickstarter/ui/activities/SetPasswordActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/SetPasswordViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/SetPasswordViewModelTest.kt
Labels: migration

#1831 [MBL-815] Update LoginToutViewmodel to RX2
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/ui/activities/LoginToutActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/LoginToutViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/LoginToutViewModelTest.kt
Labels: refactor 🛠

#1833 [MBL-927] Add questions and vertical flag dividers to use of UI tab
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AiDisclosureScreen.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSDimensions.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/kickstarter/ui/activities/compose/AiDisclosureScreenTest.kt
Labels: UI 🎨

#1832 MBL-751: CreatePasswordViewModel.kt to Jetpack ViewModel and RxJava2.2
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
  app/src/main/java/com/kickstarter/ui/activities/CreatePasswordActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/SetPasswordActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/CreatePasswordViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/SetPasswordViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/CreatePasswordViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/SetPasswordViewModelTest.kt
Labels: maintenance 🗜

#1835 MBL-942: HTMLParser now accepts headers
  app/build.gradle
  app/src/internal/java/com/kickstarter/ui/activities/PlaygroundActivity.kt
  app/src/internal/res/layout/playground_layout.xml
  app/src/main/java/com/kickstarter/libs/htmlparser/ElementExt.kt
  app/src/main/java/com/kickstarter/libs/htmlparser/HTMLModels.kt
  app/src/main/java/com/kickstarter/ui/viewholders/projectcampaign/TextElementViewHolder.kt
  app/src/main/res/values/dimens.xml
  app/src/test/java/com/kickstarter/libs/htmlparser/HTMLParserTest.kt
Labels: feature ✨

#1836 [MBL-903] Update Logintout activity visuals to compose
  app/src/main/java/com/kickstarter/ui/activities/LoginToutActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/login/LoginToutScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AiDisclosureScreen.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSDimensions.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/kickstarter/ui/activities/compose/AiDisclosureScreenTest.kt
Labels: UI 🎨, refactor 🛠

#1841 MBL-932: Connectivity status check
  .circleci/config.yml
  app/build.gradle
  app/src/main/java/com/kickstarter/libs/BaseActivity.java
  app/src/main/java/com/kickstarter/services/ConnectivityReceiver.kt
  build.gradle
Labels: feature ✨, maintenance 🗜

#1842 [MBL-945] Add tests to logintout screen, minor visual adjustment for use of ai tab
  app/src/main/java/com/kickstarter/ui/activities/compose/login/LoginToutScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AiDisclosureScreen.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSButtons.kt
  app/src/main/java/com/kickstarter/ui/toolbars/compose/ToolBar.kt
  app/src/test/java/com/kickstarter/ui/activities/compose/AiDisclosureScreenTest.kt
  app/src/test/java/com/kickstarter/ui/activities/compose/LoginToutScreenTest.kt
Labels: UI 🎨, refactor 🛠

#1844 MBL-933: Facebook Login QA Fixes for release
  app/src/main/java/com/kickstarter/ui/activities/CreatePasswordActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/SetPasswordActivity.kt
Labels: bug 🐛, release 🚀, QA

#1848 [MBL-898] Recreate create password screen in compose
  app/src/main/java/com/kickstarter/ui/activities/CreatePasswordActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/login/CreatePasswordScreen.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSTextInput.kt
  app/src/main/java/com/kickstarter/viewmodels/CreatePasswordViewModel.kt
  app/src/test/java/com/kickstarter/ui/activities/compose/CreatePasswordScreenTest.kt
  app/src/test/java/com/kickstarter/viewmodels/CreatePasswordViewModelTest.kt
Labels: UI 🎨, refactor 🛠
