Repository kickstarter/android-oss, pull requests merged in 2023-05, with the labels that each got.

#1777 MBL-727: Create splash screen and launch from Discovery Activity
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.kt
  app/src/main/res/drawable/ksr_logo_rgb_white.xml
  app/src/main/res/values/styles.xml
Labels: UI 🎨

#1776 MBL-734: Retrofit client migrated to rxjava2 + LoginViewModel lifecycle improvements
  app/build.gradle
  app/src/external/java/com/kickstarter/ExternalApplicationModule.java
  app/src/internal/java/com/kickstarter/InternalApplicationModule.java
  app/src/main/java/com/kickstarter/ApplicationModule.java
  app/src/main/java/com/kickstarter/libs/Environment.kt
  app/src/main/java/com/kickstarter/libs/qualifiers/ApiRetrofit.kt
  app/src/main/java/com/kickstarter/libs/rx/operators/ApiErrorOperatorV2.kt
  app/src/main/java/com/kickstarter/libs/rx/operators/OperatorsV2.java
  app/src/main/java/com/kickstarter/libs/rx/transformers/IgnoreValuesTransformerV2.kt
  app/src/main/java/com/kickstarter/libs/utils/ObjectUtils.java
  app/src/main/java/com/kickstarter/mock/services/MockApiClientV2.kt
  app/src/main/java/com/kickstarter/services/ApiClientTypeV2.java
  app/src/main/java/com/kickstarter/services/ApiClientV2.java
  app/src/main/java/com/kickstarter/services/ApiServiceV2.java
  app/src/main/java/com/kickstarter/ui/activities/LoginActivity.kt
  app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectCampaignFragment.kt
  app/src/main/java/com/kickstarter/ui/views/LoginPopupMenu.kt
  app/src/main/java/com/kickstarter/viewmodels/LoginViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/usecases/GetUserPrivacyUseCase.kt
  app/src/main/java/com/kickstarter/viewmodels/usecases/LoginUseCase.kt
  app/src/test/java/com/kickstarter/libs/rx/operators/ApiErrorOperatorTestV2.kt
  app/src/test/java/com/kickstarter/viewmodels/LoginViewModelTest.kt
  build.gradle
  jacoco.gradle
Labels: maintenance 🗜

#1778 MBL-700 : Fix bonus amount not being able to go past 3 digits
  app/src/main/java/com/kickstarter/libs/utils/NumberUtils.java
  app/src/main/java/com/kickstarter/libs/utils/extensions/StringExt.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/main/res/layout/fragment_pledge_section_bonus_support.xml
  app/src/test/java/com/kickstarter/libs/utils/extensions/StringExtKtTest.kt
Labels: WIP 🔨

#1780 MBL-779: [Android] Setup TriggerThirdPartyEventType GraphQL Mutation
  app/src/main/graphql/capi.graphql
  app/src/main/graphql/fragments.graphql
  app/src/main/graphql/schema.json
  app/src/main/graphql/thirdPartyEvents.graphql
  app/src/main/java/com/kickstarter/libs/utils/ThirdPartyEventName.kt
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/models/Project.kt
  app/src/main/java/com/kickstarter/services/ApolloClientType.kt
  app/src/main/java/com/kickstarter/services/KSApolloClient.kt
Labels: events 🛤

#1781 [MBL-747] Update change email screen, viewmodel and tests, to use RX2
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/services/ApolloClientType.kt
  app/src/main/java/com/kickstarter/services/KSApolloClient.kt
  app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
  app/src/main/java/com/kickstarter/ui/activities/ChangeEmailActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/ChangeEmailViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ChangeEmailViewModelTest.kt
Labels: refactor 🛠

#1790 [MBL-748] Update ChangePassword Activity, Viewmodel, and tests to RX2
  app/src/main/java/com/kickstarter/libs/rx/transformers/ObserveForUITransformerV2.kt
  app/src/main/java/com/kickstarter/libs/rx/transformers/Transformers.java
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
  app/src/main/java/com/kickstarter/ui/activities/ChangePasswordActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/ChangePasswordViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ChangePasswordViewModelTest.kt
Labels: refactor 🛠

#1788 MBL-666: [Android] Update purchase event with new mutation on thanks page after user completes checkout
  app/src/main/java/com/kickstarter/libs/utils/ThirdPartyEventName.kt
  app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ThanksViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectPageViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/usecases/SendCAPIEventUseCase.kt
  app/src/main/java/com/kickstarter/viewmodels/usecases/SendThirdPartyEventUseCase.kt
  app/src/test/java/com/kickstarter/viewmodels/ThanksViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/usecases/SendCAPIEventUseCaseTest.kt
  app/src/test/java/com/kickstarter/viewmodels/usecases/SendThirdPartyEventUseCaseTest.kt
Labels: events 🛤

#1782 MBL-827 Migrate SignupViewModel.kt to Jetpack ViewModel and RxJava2.2
  app/src/main/java/com/kickstarter/libs/rx/transformers/NeverApiErrorTransformerV2.kt
  app/src/main/java/com/kickstarter/libs/rx/transformers/Transformers.java
  app/src/main/java/com/kickstarter/ui/activities/SignupActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/SignupViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/SignupDataTest.kt
  app/src/test/java/com/kickstarter/viewmodels/SignupViewModelTest.kt
Labels: refactor 🛠

#1789 MBL-831: SearchActivity-ViewModel migrated to RXJava2
  app/src/main/java/com/kickstarter/libs/ApiPaginatorV2.kt
  app/src/main/java/com/kickstarter/libs/recyclerviewpagination/RecyclerViewPaginatorV2.kt
  app/src/main/java/com/kickstarter/libs/recyclerviewpagination/RecyclerViewScrollEvent.kt
  app/src/main/java/com/kickstarter/libs/recyclerviewpagination/RecyclerViewScrollEventOnSubscribe.kt
  app/src/main/java/com/kickstarter/libs/recyclerviewpagination/RxRecyclerView.kt
  app/src/main/java/com/kickstarter/libs/recyclerviewpagination/ViewEvent.kt
  app/src/main/java/com/kickstarter/ui/activities/SearchActivity.kt
  app/src/main/java/com/kickstarter/ui/toolbars/SearchToolbar.kt
  app/src/main/java/com/kickstarter/viewmodels/SearchViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/SearchViewModelTest.kt
  jacoco.gradle
Labels: refactor 🛠, maintenance 🗜

#1791 [MBL-826] Update settings viewmodel, activity, and tests to RX2
  app/src/main/java/com/kickstarter/ui/activities/SettingsActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/SettingsViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/SettingsViewModelTest.kt
Labels: refactor 🛠
