Repository kickstarter/android-oss, pull requests merged in 2023-02, with the labels that each got.

#1736 WEB-858: [Android] Check consent preference in isEnabled method in the TrackingClient
  app/src/main/java/com/kickstarter/libs/SegmentTrackingClient.kt
  app/src/main/java/com/kickstarter/libs/TrackingClient.kt
  app/src/test/java/com/kickstarter/libs/SegmentTest.kt
Labels: feature ✨, GDPR 🔐

#1742 NTV-643: click action for the arrow icon
  app/src/main/java/com/kickstarter/ui/activities/compose/ReportProjectScreen.kt
Labels: bug 🐛

#1743 NTV-651: JVM memory issues with tests
  app/build.gradle
  app/internal_version_code.txt
  app/internal_version_name.txt
  gradle.properties
Labels: maintenance 🗜

#1738 WEB-754 : [Android] Add Prelaunch page to Android app
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/graphql/fragments.graphql
  app/src/main/java/com/kickstarter/ApplicationModule.java
  app/src/main/java/com/kickstarter/libs/CurrentConfigV2.kt
  app/src/main/java/com/kickstarter/libs/CurrentUserV2.kt
  app/src/main/java/com/kickstarter/libs/Environment.kt
  app/src/main/java/com/kickstarter/libs/Logout.java
  app/src/main/java/com/kickstarter/libs/rx/transformers/CombineLatestPairTransformerV2.kt
  app/src/main/java/com/kickstarter/libs/rx/transformers/IgnoreValuesTransformerV2.kt
  app/src/main/java/com/kickstarter/libs/rx/transformers/TakePairWhenTransformerV2.kt
  app/src/main/java/com/kickstarter/libs/rx/transformers/Transformers.java
  app/src/main/java/com/kickstarter/libs/utils/KsOptional.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/DisposableExt.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/IntentExt.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/StringExt.kt
  app/src/main/java/com/kickstarter/mock/MockCurrentConfigV2.kt
  app/src/main/java/com/kickstarter/mock/factories/ProjectFactory.kt
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/models/Project.kt
  app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
  app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
  app/src/main/java/com/kickstarter/ui/activities/PreLaunchProjectPageActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/SearchActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/PreLaunchProjectPageScreen.kt
  app/src/main/java/com/kickstarter/ui/compose/KSButtonCompose.kt
  app/src/main/java/com/kickstarter/ui/compose/KSComposeColor.kt
  app/src/main/java/com/kickstarter/ui/compose/KSImageCompose.kt
  app/src/main/java/com/kickstarter/ui/compose/KSTextCompose.kt
  app/src/main/java/com/kickstarter/ui/compose/KsCreatorLayout.kt
  app/src/main/java/com/kickstarter/ui/compose/ToolBar.kt
  app/src/main/java/com/kickstarter/ui/fragments/DiscoveryFragment.kt
  app/src/main/java/com/kickstarter/ui/intentmappers/ProjectIntentMapper.kt
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/FacebookConfirmationViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/LoginToutViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/LoginViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/SearchViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/SetPasswordViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/SignupViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/TwoFactorViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/PrelaunchProjectViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/usecases/LoginUseCase.kt
  app/src/main/res/drawable/ic_bookmark_dark_outline.xml
  app/src/main/res/drawable/ic_bookmark_red_filled.xml
  app/src/main/res/drawable/ic_bookmark_white_outline.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/kickstarter/KSRobolectricTestCase.kt
  app/src/test/java/com/kickstarter/libs/MockCurrentUserV2.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/IntentExtTest.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/StringExtKtTest.kt
  app/src/test/java/com/kickstarter/ui/intents/ProjectIntentMapperTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ActivityFeedViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/MessageThreadsViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/PrelaunchProjectViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/SearchViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/SearchViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/SetPasswordViewModelTest.kt
Labels: feature ✨

#1746 WEB-975 : [Android] Setup TriggerCapiEventInput GraphQL Mutation
  app/src/main/graphql/capi.graphql
  app/src/main/graphql/schema.json
  app/src/main/java/com/kickstarter/libs/utils/ConversionsApiEventName.kt
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/services/ApolloClientType.kt
  app/src/main/java/com/kickstarter/services/KSApolloClient.kt
Labels: feature ✨, events 🛤

#1748 WEB-846: [Android] Bring in localized strings for consent management
  app/src/main/assets/json/server-config.json
  app/src/main/java/com/kickstarter/ui/fragments/ConsentManagementDialogFragment.kt
  app/src/main/res/values-de/strings_i18n.xml
  app/src/main/res/values-es/strings_i18n.xml
  app/src/main/res/values-fr/strings_i18n.xml
  app/src/main/res/values-ja/strings_i18n.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/strings_i18n.xml
Labels: copy 📝
