Repository kickstarter/android-oss, pull requests merged in 2023-10, with the labels that each got.

#1861 MBL-787: EnvironmentalCommitments to JetpackViewModel and RXJava2
  app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectEnvironmentalCommitmentsFragment.kt
  app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectOverviewFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectEnvironmentalCommitmentsViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectEnvironmentalCommitmentsViewModelTest.kt
Labels: maintenance 🗜, migration

#1862 [MBL-979] add the project cards for the search page
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSDimensions.kt
  app/src/main/java/com/kickstarter/ui/viewholders/compose/search/FeaturedSearchViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/compose/search/ProjectSearchViewholder.kt
Labels: UI 🎨

#1864 MBL-752: CreatorBioActivity to JetpackViewModel and RXJava2
  app/src/main/java/com/kickstarter/ui/activities/CreatorBioActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/CreatorBioViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/CreatorBioViewModelTest.kt
Labels: refactor 🛠, maintenance 🗜

#1863 [MBL-985] Convert Search Screen to Compose (w/Improvements)
  app/build.gradle
  app/src/main/java/com/kickstarter/libs/ApiPaginatorV2.kt
  app/src/main/java/com/kickstarter/ui/activities/SearchActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/search/SearchScreen.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSColors.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSDimensions.kt
  app/src/main/java/com/kickstarter/ui/viewholders/compose/search/FeaturedSearchViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/compose/search/ProjectSearchViewholder.kt
  app/src/main/java/com/kickstarter/ui/views/compose/search/SearchEmptyView.kt
  app/src/main/java/com/kickstarter/ui/views/compose/search/SearchTopBar.kt
  app/src/main/java/com/kickstarter/viewmodels/SearchViewModel.kt
  app/src/test/java/com/kickstarter/ui/activities/compose/search/SearchScreenTest.kt
Labels: UI 🎨, refactor 🛠

#1867 [BUGFIX] prevent crash with span text returning a -1 for the starting index
  app/src/main/java/com/kickstarter/ui/activities/compose/login/KSCreateAccountDisclaimerText.kt
Labels: bug 🐛

#1866 MBL-791: SocialActivity fix && migration to RXJava2+ViewModel
  app/src/main/java/com/kickstarter/ui/activities/ProjectSocialActivity.kt
  app/src/main/java/com/kickstarter/ui/adapters/ProjectSocialAdapter.java
  app/src/main/java/com/kickstarter/ui/adapters/ProjectSocialAdapter.kt
  app/src/main/java/com/kickstarter/ui/extensions/ImageViewExt.kt
  app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectOverviewFragment.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ProjectContextViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ProjectSocialViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectSocialViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectOverviewViewModel.kt
  app/src/main/res/layout/fragment_project_overview.xml
  app/src/test/java/com/kickstarter/viewmodels/ProjectSocialViewModelTest.kt
Labels: bug 🐛, refactor 🛠, migration

#1869 [MBL-986] Remove the Maison Neue font family from the app
  app/src/main/assets/fonts/maison-neue-book.ttf
  app/src/main/java/com/kickstarter/libs/Font.java
  app/src/main/res/layout/activity_set_password.xml
  app/src/main/res/layout/messages_layout.xml
  app/src/main/res/layout/reset_password_layout.xml
  app/src/main/res/values/strings_config.xml
  app/src/main/res/values/styles.xml
Labels: UI 🎨

#1868 [NO TICKET] remove button that would have lead to creator dashboard
  app/src/main/res/layout/project_creator_dashboard_header.xml
Labels: UI 🎨

#1870 [MBL-1004] Remove unneeded files from vies we converted to compose
  app/src/main/java/com/kickstarter/ui/activities/SearchActivity.kt
  app/src/main/java/com/kickstarter/ui/adapters/SearchAdapter.java
  app/src/main/java/com/kickstarter/ui/toolbars/SearchToolbar.kt
  app/src/main/java/com/kickstarter/ui/viewholders/FeaturedSearchResultViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/PopularSearchTitleViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ProjectSearchResultViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectSearchResultHolderViewModel.kt
  app/src/main/res/layout-land/login_tout_layout.xml
  app/src/main/res/layout/activity_change_password.xml
  app/src/main/res/layout/activity_create_password.xml
  app/src/main/res/layout/activity_set_password.xml
  app/src/main/res/layout/change_password_toolbar.xml
  app/src/main/res/layout/create_password_toolbar.xml
  app/src/main/res/layout/featured_search_result_view.xml
  app/src/main/res/layout/login_form_view.xml
  app/src/main/res/layout/login_layout.xml
  app/src/main/res/layout/login_toolbar.xml
  app/src/main/res/layout/login_tout_layout.xml
  app/src/main/res/layout/project_search_result_view.xml
  app/src/main/res/layout/reset_password_form_view.xml
  app/src/main/res/layout/reset_password_layout.xml
  app/src/main/res/layout/search_layout.xml
  app/src/main/res/layout/search_popular_title_view.xml
  app/src/main/res/layout/search_toolbar.xml
  app/src/main/res/layout/signup_form_view.xml
  app/src/main/res/layout/signup_layout.xml
  app/src/main/res/layout/two_factor_form_view.xml
  app/src/main/res/layout/two_factor_layout.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/com/kickstarter/ui/adapters/SearchAdapterTest.java
  app/src/test/java/com/kickstarter/viewmodels/ProjectSearchResultHolderViewModelTest.kt
Labels: refactor 🛠

#1874 MBL-911: Android 14
  .circleci/config.yml
  Gemfile.lock
  app/build.gradle
  app/internal_version_code.txt
  app/internal_version_name.txt
  app/src/internal/java/com/kickstarter/ui/activities/InternalToolsActivity.kt
  app/src/main/java/com/kickstarter/ApplicationModule.java
  app/src/main/java/com/kickstarter/libs/BaseActivity.java
  app/src/main/java/com/kickstarter/libs/preferences/BooleanDataStore.kt
  app/src/main/java/com/kickstarter/libs/preferences/BooleanDataStoreType.kt
  app/src/main/java/com/kickstarter/services/ConnectivityReceiver.kt
  app/src/main/java/com/kickstarter/ui/activities/AccountActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ChangeEmailActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/PaymentMethodsSettingsActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/SettingsActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/UpdateActivity.kt
  app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt
  app/src/test/java/com/kickstarter/libs/BooleanDataStoreTest.kt
  build.gradle
Labels: feature ✨

#1873 [MBL-741] Update Activitysampleviewholderviewmodel to RX2
  app/src/main/java/com/kickstarter/ui/viewholders/ActivitySampleProjectViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/ActivitySampleProjectViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ActivitySampleProjectViewHolderViewModelTest.kt
Labels: refactor 🛠

#1872 [MBL-802] Update ThanksShareHolderViewmodel to RX2
  app/src/main/java/com/kickstarter/ui/viewholders/ThanksShareViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/ThanksShareHolderViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ThanksShareHolderViewModelTest.kt
Labels: refactor 🛠

#1875 [MBL-768] Update HelpSettingsActivity and ViewModel to RX2
  app/src/main/java/com/kickstarter/ui/activities/HelpSettingsActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/HelpSettingsViewModel.kt
Labels: refactor 🛠

#1876 [MBL-769] Remove HelpViewModel
  app/src/main/java/com/kickstarter/ui/activities/HelpActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/HelpViewModel.kt
Labels: refactor 🛠

#1877 [MBL-1012] Update legal pages in login to load in Chrome tabs
  app/src/main/java/com/kickstarter/ui/activities/HelpSettingsActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/LoginActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/LoginToutActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ResetPasswordActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/SetPasswordActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/SignupActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/TwoFactorActivity.kt
  app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt
Labels: bug 🐛, refactor 🛠

#1878 [MBL-784] Convert Paymentmethodsviewholderviewmodel to rx2
  app/src/main/java/com/kickstarter/ui/viewholders/PaymentMethodsViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/PaymentMethodsViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/PaymentMethodsViewHolderViewModelTest.kt
Labels: refactor 🛠

#1879 MBL-817: Messages Screen
  app/src/main/java/com/kickstarter/services/apiresponses/MessageThreadEnvelope.kt
  app/src/main/java/com/kickstarter/ui/activities/MessagesActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/MessagesViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/MessagesViewModelTest.kt
Labels: refactor 🛠, maintenance 🗜

#1880 MBL-805: VideoPlayer Screen
  app/src/main/java/com/kickstarter/ui/activities/VideoActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/VideoViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/VideoViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/VideoViewModelTest.kt
Labels: refactor 🛠, maintenance 🗜

#1881 [No ticket] Changes to address top crash
  app/src/main/java/com/kickstarter/ui/adapters/CommentInitialErrorAdapter.kt
  app/src/main/java/com/kickstarter/ui/adapters/CommentPaginationErrorAdapter.kt
  app/src/main/java/com/kickstarter/ui/adapters/CommentsAdapter.kt
  app/src/main/java/com/kickstarter/ui/adapters/DiscoveryActivitySampleAdapter.kt
  app/src/main/java/com/kickstarter/ui/adapters/DiscoveryEditorialAdapter.kt
  app/src/main/java/com/kickstarter/ui/adapters/DiscoveryOnboardingAdapter.kt
  app/src/main/java/com/kickstarter/ui/adapters/DiscoveryProjectCardAdapter.kt
  app/src/main/java/com/kickstarter/ui/adapters/EnvironmentalCommitmentsAdapter.kt
  app/src/main/java/com/kickstarter/ui/adapters/FrequentlyAskedQuestionsAdapter.kt
  app/src/main/java/com/kickstarter/ui/adapters/KSListAdapter.kt
  app/src/main/java/com/kickstarter/ui/adapters/MessageThreadsAdapter.java
  app/src/main/java/com/kickstarter/ui/adapters/PaymentMethodsAdapter.kt
  app/src/main/java/com/kickstarter/ui/adapters/ProjectSocialAdapter.kt
  app/src/main/java/com/kickstarter/ui/adapters/RepliesAdapter.kt
  app/src/main/java/com/kickstarter/ui/adapters/RepliesStatusAdapter.kt
  app/src/main/java/com/kickstarter/ui/adapters/RootCommentAdapter.kt
  app/src/main/java/com/kickstarter/ui/adapters/projectcampaign/HeaderElementAdapter.kt
Labels: bug 🐛

#1882 [NoTicket] add uncaught UndeliverableException handler
  app/src/main/java/com/kickstarter/KSApplication.java
Labels: bug 🐛

#1885 [MBL-796] Update RewardViewHolderVIewmodel to RX2
  app/src/main/java/com/kickstarter/ui/viewholders/RewardViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardViewHolderViewModelTest.kt
Labels: refactor 🛠

#1886 MBL-816: MessageCreator Screen
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
  app/src/main/java/com/kickstarter/ui/activities/MessageCreatorActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/MessageCreatorViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/MessageCreatorViewModelTest.kt
Labels: refactor 🛠, migration

#1888 MBL-795: RewardsFragment Screen
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/ui/fragments/RewardsFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardsFragmentViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardsFragmentViewModelTest.kt
Labels: refactor 🛠, migration

#1887 [MBL-793/794] Update CardViewHolder ViewModels to RX2
  app/src/main/java/com/kickstarter/ui/viewholders/RewardCardSelectedViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/RewardCardUnselectedViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/BaseRewardCardViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardCardSelectedViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardCardUnselectedViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardCardSelectedViewHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardCardUnselectedViewHolderViewModelTest.kt
Labels: refactor 🛠
