Repository kickstarter/android-oss, pull requests merged in 2023-09, with the labels that each got.

#1850 [MBL-858] Remove creator dashboard
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
  app/src/main/java/com/kickstarter/libs/utils/EventContextValues.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/IntentExt.kt
  app/src/main/java/com/kickstarter/ui/activities/CreatorDashboardActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.kt
  app/src/main/java/com/kickstarter/ui/adapters/CreatorDashboardAdapter.java
  app/src/main/java/com/kickstarter/ui/adapters/CreatorDashboardBottomSheetAdapter.java
  app/src/main/java/com/kickstarter/ui/adapters/CreatorDashboardReferrerStatsAdapter.java
  app/src/main/java/com/kickstarter/ui/adapters/CreatorDashboardRewardStatsAdapter.java
  app/src/main/java/com/kickstarter/ui/adapters/DiscoveryDrawerAdapter.kt
  app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt
  app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectOverviewFragment.kt
  app/src/main/java/com/kickstarter/ui/viewholders/CreatorDashboardBottomSheetViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/CreatorDashboardHeaderViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/CreatorDashboardReferrerBreakdownViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/CreatorDashboardReferrerStatsRowViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/CreatorDashboardReferrerStatsViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/CreatorDashboardRewardStatsRowViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/CreatorDashboardRewardStatsViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/discoverydrawer/LoggedInViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/CreatorDashboardBottomSheetHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/CreatorDashboardHeaderHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/CreatorDashboardReferrerBreakdownHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/CreatorDashboardReferrerStatsHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/CreatorDashboardReferrerStatsRowHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/CreatorDashboardRewardStatsHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/CreatorDashboardViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/DashboardRewardStatsRowHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectOverviewViewModel.kt
  app/src/main/res/drawable/creator_dashboard_circle.xml
  app/src/main/res/layout/creator_dashboard_layout.xml
  app/src/main/res/layout/creator_dashboard_project_switcher_header.xml
  app/src/main/res/layout/creator_dashboard_project_switcher_view.xml
  app/src/main/res/layout/creator_dashboard_recycler_layout.xml
  app/src/main/res/layout/creator_dashboard_toolbar.xml
  app/src/main/res/layout/dashboard_funding_view.xml
  app/src/main/res/layout/dashboard_referrer_breakdown_layout.xml
  app/src/main/res/layout/dashboard_referrer_stats_row_view.xml
  app/src/main/res/layout/dashboard_referrer_stats_view.xml
  app/src/main/res/layout/dashboard_reward_stats_row_view.xml
  app/src/main/res/layout/dashboard_reward_stats_view.xml
  app/src/main/res/layout/discovery_drawer_logged_in_view.xml
  app/src/main/res/layout/project_creator_dashboard_header.xml
  app/src/main/res/values/styles.xml
  app/src/test/java/com/kickstarter/libs/SegmentTest.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/IntentExtTest.kt
  app/src/test/java/com/kickstarter/viewmodels/CreatorDashboardBottomSheetHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/CreatorDashboardHeaderHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/CreatorDashboardReferrerBreakdownHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/CreatorDashboardReferrerStatsHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/CreatorDashboardReferrerStatsRowHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/CreatorDashboardRewardStatsHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/CreatorDashboardViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/DashboardRewardStatsRowHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectOverviewViewModelTest.kt
Labels: refactor 🛠

#1851 MBL-950: Connectivity status check refactor
  app/src/main/java/com/kickstarter/libs/BaseActivity.java
  app/src/main/java/com/kickstarter/services/ConnectivityReceiver.kt
  app/src/main/java/com/kickstarter/ui/activities/AccountActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ChangeEmailActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/LoginActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/PaymentMethodsSettingsActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/SearchActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/SetPasswordActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/SettingsActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/SignupActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/TwoFactorActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/UpdateActivity.kt
  app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt
  build.gradle
Labels: feature ✨, maintenance 🗜

#1852 [MBL-907] Update Reset Password screen to use Compose
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/ui/activities/LoginToutActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ResetPasswordActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/login/KSLoginDropdownMenu.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/login/LoginToutScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/login/ResetPasswordScreen.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSTextInput.kt
  app/src/main/java/com/kickstarter/viewmodels/ResetPasswordViewModel.kt
  app/src/test/java/com/kickstarter/ui/activities/compose/LoginToutScreenTest.kt
  app/src/test/java/com/kickstarter/ui/activities/compose/ResetPasswordScreenTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ResetPasswordViewModelTest.kt
Labels: UI 🎨, refactor 🛠

#1854 Convert Login to Compose
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/ui/activities/LoginActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/LoginToutActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/login/LoginScreen.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSAlerts.kt
  app/src/main/java/com/kickstarter/viewmodels/LoginViewModel.kt
  app/src/test/java/com/kickstarter/ui/activities/compose/LoginScreenTest.kt
  app/src/test/java/com/kickstarter/viewmodels/LoginViewModelTest.kt
Labels: UI 🎨, refactor 🛠

#1855 [MBL-969] Convert Two Factor screen to Compose
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/ui/activities/TwoFactorActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/login/TwoFactorScreen.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSAlerts.kt
  app/src/main/java/com/kickstarter/viewmodels/TwoFactorViewModel.kt
  app/src/test/java/com/kickstarter/ui/activities/compose/TwoFactorScreenTest.kt
  app/src/test/java/com/kickstarter/viewmodels/TwoFactorViewModelTest.kt
Labels: UI 🎨, refactor 🛠

#1857 [No Ticket] fix issue with error or success messages constantly showing on LoginActivity
  app/src/main/java/com/kickstarter/ui/activities/LoginActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/LoginViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/LoginViewModelTest.kt
Labels: bug 🐛, UI 🎨

#1860 MBL-788: ProjectOverviewViewModel to JetpackViewModel and compose
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
  app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectOverviewFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectOverviewViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectOverviewViewModelTest.kt
Labels: maintenance 🗜, migration
