Repository kickstarter/android-oss, pull requests merged in 2023-12, with the labels that each got.

#1911 [Bigfix] Fix issue where messages to some creators dont get sent
  app/src/main/java/com/kickstarter/viewmodels/MessagesViewModel.kt
Labels: bug 🐛

#1913 [MBL-1087] update viewmodel with more null filtering and adjusting subscribing
  app/src/main/java/com/kickstarter/viewmodels/RewardViewHolderViewModel.kt
Labels: bug 🐛, refactor 🛠

#1914 MBL-1086: ThanksActivity.showGamesNewsletterDialog crash
  app/src/main/java/com/kickstarter/ui/activities/ThanksActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/ThanksViewModel.kt
Labels: bug 🐛

#1915 [MBL-1089] SettingsActivity crash fix, Observe on UI thread
  app/src/main/java/com/kickstarter/ui/activities/SettingsActivity.kt
Labels: bug 🐛

#1918 [MBL-797] Update root comment viewholder to rx2
  app/src/main/java/com/kickstarter/ui/viewholders/RootCommentViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/RootCommentViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/RootCommentViewHolderViewModelTest.kt
Labels: refactor 🛠

#1917 MBL-1053: Identify if https links in messages are KSR links
  app/src/main/java/com/kickstarter/ui/viewholders/MessageViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/MessageHolderViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/MessageHolderViewModelTest.kt
Labels: maintenance 🗜
