Repository kickstarter/android-oss, pull requests merged in 2023-11, with the labels that each got.

#1891 MBL-746: CancelPledge Screen
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
  app/src/main/java/com/kickstarter/ui/fragments/CancelPledgeFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/CancelPledgeViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/CancelPledgeViewModelTest.kt
Labels: migration

#1892 MBL-819: Newsleter Screen migrated to RXJava2 + ViewModel
  app/src/main/java/com/kickstarter/ui/activities/NewsletterActivity.kt
  app/src/main/java/com/kickstarter/ui/data/Newsletter.java
  app/src/main/java/com/kickstarter/viewmodels/NewsletterViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/NewsletterViewModelTest.kt
Labels: refactor 🛠, migration

#1893 [MBL-828] Update Thanksviewmodel and tests to RX2
  app/src/main/java/com/kickstarter/mock/services/MockApiClientV2.kt
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
  app/src/main/java/com/kickstarter/ui/activities/ThanksActivity.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ProjectCardViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ThanksCategoryViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ThanksViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ThanksViewModelTest.kt
Labels: refactor 🛠

#1894 MBL-744: BackingActivity to RXJava2 + ViewModel
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
  app/src/main/java/com/kickstarter/ui/activities/BackingActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/BackingViewModelTest.kt
Labels: migration

#1896 [MBL-762] Update EditorialViewModel and activity to rx2
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
  app/src/main/java/com/kickstarter/ui/activities/EditorialActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/EditorialViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/EditorialViewModelTest.kt
Labels: refactor 🛠

#1895 MBL-760: DownloadBeta dialog removed
  app/src/androidTest/java/com/kickstarter/screenshoot/testing/di/AndroidTestApplicationModule.kt
  app/src/androidTest/java/com/kickstarter/screenshoot/testing/di/NoopBuildCheck.kt
  app/src/external/java/com/kickstarter/ExternalApplicationModule.java
  app/src/external/java/com/kickstarter/libs/NoopBuildCheck.java
  app/src/internal/java/com/kickstarter/InternalApplicationModule.java
  app/src/main/java/com/kickstarter/ApplicationModule.java
  app/src/main/java/com/kickstarter/libs/BuildCheck.java
  app/src/main/java/com/kickstarter/libs/Environment.kt
  app/src/main/java/com/kickstarter/mock/factories/InternalBuildEnvelopeFactory.kt
  app/src/main/java/com/kickstarter/mock/services/MockWebClient.java
  app/src/main/java/com/kickstarter/services/WebClient.java
  app/src/main/java/com/kickstarter/services/WebClientType.java
  app/src/main/java/com/kickstarter/services/WebService.java
  app/src/main/java/com/kickstarter/services/apiresponses/InternalBuildEnvelope.kt
  app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/DownloadBetaActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/DownloadBetaViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/inputs/DownloadBetaViewModelInputs.java
  app/src/main/java/com/kickstarter/viewmodels/outputs/DownloadBetaViewModelOutputs.java
  app/src/test/java/com/kickstarter/KSRobolectricTestCase.kt
  app/src/test/java/com/kickstarter/models/EnvironmentTest.kt
  app/src/test/java/com/kickstarter/services/apiresponses/InternalBuildEnvelopeTest.kt
  app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/DownloadBetaViewModelTest.kt
Labels: unused

#1899 [MBL-740] Update ActivitySampleFriendFollowViewHolderVIewModel to rx2
  app/src/main/java/com/kickstarter/ui/viewholders/ActivitySampleFriendFollowViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/ActivitySampleFriendFollowViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ActivitySampleFriendFollowViewHolderViewModelTest.kt
Labels: refactor 🛠

#1898 [MBL-761] Update Editorialviewholder to rx2
  app/src/main/java/com/kickstarter/ui/viewholders/EditorialViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/EditorialViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/EditorialViewHolderViewModelTest.kt
Labels: refactor 🛠

#1897 [MBL-786] Adjust project card to use rx2
  app/src/main/java/com/kickstarter/libs/utils/extensions/ProjectExt.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ProjectCardViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectCardHolderViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectCardHolderViewModelTest.kt
Labels: refactor 🛠

#1903 MBL-750: CommentsScreen to RXJava2 + ViewModel
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
  app/src/main/java/com/kickstarter/ui/activities/CommentsActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectUpdatesViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectUpdatesViewModelTest.kt
Labels: refactor 🛠, migration

#1902 [MBL-1060] Add dark mode toggle in settings, make settings visible to non logged in users
  app/src/main/java/com/kickstarter/ui/SharedPreferenceKey.kt
  app/src/main/java/com/kickstarter/ui/activities/ChangePasswordActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/CreatePasswordActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/LoginActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/LoginToutActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ResetPasswordActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/SearchActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/SetPasswordActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/SettingsActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/SignupActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/TwoFactorActivity.kt
  app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectAIFragment.kt
  app/src/main/java/com/kickstarter/ui/viewholders/discoverydrawer/LoggedOutViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/SettingsViewModel.kt
  app/src/main/res/layout/discovery_drawer_logged_out_view.xml
  app/src/main/res/layout/settings_layout.xml
  app/src/main/res/values/strings.xml
Labels: UI 🎨, refactor 🛠

#1904 MBL-745: BaseRewardCardViewHolderViewModel.kt to Jetpack ViewModel and RxJava2.2
  app/src/main/java/com/kickstarter/viewmodels/BaseRewardCardViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/BaseRewardCardViewHolderViewModelTest.kt
Labels: refactor 🛠

#1905 [MBL-804] Update UpdateCardViewholder to RX2
  app/src/main/java/com/kickstarter/ui/viewholders/UpdateCardViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/UpdateCardViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/UpdateCardViewHolderViewModelTest.kt
Labels: refactor 🛠

#1907 MBL-1054: Marketing emails deeplinks
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/libs/utils/extensions/UriExt.kt
  app/src/main/java/com/kickstarter/ui/activities/DeepLinkActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/DeepLinkViewModel.kt
  app/src/test/java/com/kickstarter/services/UriExtTest.kt
  app/src/test/java/com/kickstarter/viewmodels/DeepLinkViewModelTest.kt
Labels: feature ✨, UI 🎨

#1906 [MBL-803] Update ThreadViewModel and files to RX2
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
  app/src/main/java/com/kickstarter/ui/activities/ThreadActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/ThreadViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ThreadViewModelTest.kt
Labels: refactor 🛠

#1908 Remove a couple potential nulls from mappers in the ProjectCardHolder ViewModel
  app/external_version_code.txt
  app/internal_version_code.txt
  app/src/main/java/com/kickstarter/viewmodels/ProjectCardHolderViewModel.kt
Labels: bug 🐛

#1910 MBL-749: CommentCardViewHolder to RXJava2
  app/internal_version_code.txt
  app/internal_version_name.txt
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
  app/src/main/java/com/kickstarter/ui/viewholders/CommentCardViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewHolderViewModelTest.kt
Labels: migration

#1909 MBL-765: ExpandableHeaderViewHolderViewModel.kt to Jetpack ViewModel and RxJava2.2
  app/src/main/java/com/kickstarter/ui/viewholders/ExpandableHeaderViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/ExpandableHeaderViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ExpandableHeaderViewHolderViewModelTest.kt
Labels: maintenance 🗜
