Repository kickstarter/android-oss, pull requests merged in 2023-01, with the labels that each got.

#1723 WEB-857: [Android] Build consent management dialog UI
  app/src/main/java/com/kickstarter/ui/fragments/ConsentManagementDialogFragment.kt
  app/src/main/res/values/strings.xml
Labels: feature ✨, UI 🎨

#1724 WEB-875: [Android] Show dialog on bootstrap when preference has not been set
  app/src/main/java/com/kickstarter/ui/SharedPreferenceKey.kt
  app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.kt
Labels: feature ✨

#1725 NTV-640: Report this project button on ProjectOverview
  app/src/main/java/com/kickstarter/libs/models/OptimizelyFeature.kt
  app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt
  app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectOverviewFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectOverviewViewModel.kt
  app/src/main/res/layout/project_creator_info.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/kickstarter/viewmodels/ProjectOverviewViewModelTest.kt
Labels: feature ✨

#1731 WEB-878: [Android] Save consent preference on user interaction with dialog
  app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.kt
  app/src/main/java/com/kickstarter/ui/fragments/ConsentManagementDialogFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/ConsentManagementDialogFragmentViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ConsentManagementDialogFragmentViewModelTest.kt
Labels: feature ✨

#1733 [no-jira] Add subscriptions in ConsentManagementViewModel to disposable
  app/src/main/java/com/kickstarter/viewmodels/ConsentManagementDialogFragmentViewModel.kt
Labels: bug 🐛

#1734 NTV-641: Informative Screen for UCG
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/ui/activities/ReportProjectCategoryActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/ReportProjectScreen.kt
  app/src/main/java/com/kickstarter/ui/compose/ToolBar.kt
  app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt
  app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectOverviewFragment.kt
  app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectRiskFragment.kt
  app/src/main/java/com/kickstarter/ui/fragments/projectpage/ui/RisksScreen.kt
  app/src/main/res/values/strings.xml
Labels: feature ✨

#1735 NTV-641: Formulary Screen, flag a project
  app/src/main/AndroidManifest.xml
  app/src/main/graphql/project.graphql
  app/src/main/java/com/kickstarter/libs/utils/extensions/IntentExt.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/StringExt.kt
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/models/User.kt
  app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
  app/src/main/java/com/kickstarter/ui/IntentKey.kt
  app/src/main/java/com/kickstarter/ui/activities/ReportProjectActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ReportProjectCategoryActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/FormularyScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/ReportProjectScreen.kt
  app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt
  app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectOverviewFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/ReportProjectViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectOverviewViewModel.kt
  app/src/main/res/layout/project_creator_info.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/kickstarter/libs/utils/extensions/StringExtKtTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectOverviewViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ReportProjectViewModelTest.kt
Labels: feature ✨
