Repository kickstarter/android-oss, pull requests merged in 2024-05, with the labels that each got.

#2028 MBL-1340: 3DS payment method UI removed on error
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/CheckoutScreen.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/LatePledgeCheckoutViewModel.kt
Labels: bug 🐛, Post Campaign Functionality

#2029 MBL-1306: Added tests
  app/src/test/java/com/kickstarter/viewmodels/LatePledgeCheckoutViewModelTest.kt
Labels: maintenance 🗜, Post Campaign Functionality

#2031 [no-jira]: updated wrapper
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: maintenance 🗜

#2036 MBL-1332: Thanks page string doesn't make sense for late pledges
  app/src/main/assets/json/server-config.json
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/ui/adapters/ThanksAdapter.java
  app/src/main/java/com/kickstarter/ui/adapters/data/ThanksData.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ThanksShareViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/ThanksShareHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/ThanksViewModel.kt
  app/src/main/res/values-de/strings_i18n.xml
  app/src/main/res/values-es/strings_i18n.xml
  app/src/main/res/values-fr/strings_i18n.xml
  app/src/main/res/values-ja/strings_i18n.xml
  app/src/main/res/values/strings_i18n.xml
  app/src/test/java/com/kickstarter/viewmodels/ThanksShareHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ThanksViewModelTest.kt
Labels: bug 🐛, copy 📝

#2039 MBL-1420: Webp format now supported for animated gifs
  app/build.gradle
  app/src/main/java/com/kickstarter/libs/utils/extensions/StringExt.kt
  app/src/main/java/com/kickstarter/ui/extensions/ImageViewExt.kt
  app/src/main/java/com/kickstarter/ui/views/ImageWithCaptionView.kt
  app/src/test/java/com/kickstarter/libs/htmlparser/HTMLParserTest.kt
Labels: bug 🐛, maintenance 🗜

#2040 MBL-1486: Create pledged projects overview feature flag
  app/src/main/java/com/kickstarter/libs/featureflag/FeatureFlagClient.kt
Labels: feature ✨

#2041 [No-jira]: Update versions after release
  app/external_version_code.txt
  app/external_version_name.txt
  app/internal_version_code.txt
  app/internal_version_name.txt
Labels: maintenance 🗜

#2043 MBL-1487: Add menu item to discovery overflow menu, launches pledged project overview, introduce new package structure
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.kt
  app/src/main/java/com/kickstarter/ui/viewholders/discoverydrawer/LoggedInViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/LoggedInViewHolderViewModel.kt
  app/src/main/res/drawable/ic_notification_bell.xml
  app/src/main/res/layout/discovery_drawer_logged_in_view.xml
  app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/LoggedInViewHolderViewModelTest.kt
Labels: feature ✨

#2046 MBL-1522: Blurry images on Campaign tab
  app/build.gradle
  app/src/androidTest/java/com/kickstarter/screenshoot/testing/ui/components/ImageWithCaptionViewTest.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/ui/views/ImageWithCaptionView.kt
  app/src/main/res/layout/view_image_with_caption.xml
Labels: bug 🐛

#2042 [MBL-1498] Fix updating payment method/fixing payment method for late pledge campaign
  app/src/main/graphql/fragments.graphql
  app/src/main/java/com/kickstarter/mock/factories/RewardFactory.kt
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/models/Backing.kt
  app/src/main/java/com/kickstarter/models/Reward.kt
  app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
  app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
  app/src/main/java/com/kickstarter/viewmodels/AddOnViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Labels: bug 🐛, Post Campaign Functionality
