Repository kickstarter/android-oss, pull requests merged in 2024-09, with the labels that each got.

#2119 [MBL-820] Update Privacy viewmodel to RX2
  app/src/main/java/com/kickstarter/ui/activities/PrivacyActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/PrivacyViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/PrivacyViewModelTest.kt
Labels: refactor 🛠

#2118 MBL-1679: not logged in user flow for crowdfund
  app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/AddOnsViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/AddOnsViewModelTest.kt
Labels: Pledge Redemption

#2120 MBL-1696: AddOns add button lost state
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AddOnsContainer.kt
Labels: Pledge Redemption

#2122 [MBL-1693] Fix add-ons not being flattened for update payment/reward flows
  app/src/main/java/com/kickstarter/libs/utils/extensions/PledgeDataExt.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/CrowdfundCheckoutViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/CrowdfundCheckoutViewModelTest.kt
Labels: bug 🐛

#2124 [MBL-1669][MBL-1715] Add delivery address object to the graph query for PPO/format result for PPO card
  app/src/main/graphql/fragments.graphql
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/data/DeliveryAddress.kt
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/data/PPOCard.kt
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/data/PPOCardFactory.kt
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PPOCardView.kt
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewScreen.kt
  app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
Labels: UI 🎨

#2125 [MBL-1725] Update PPO card to show formatted amount with currency symbol and code
  app/src/main/graphql/fragments.graphql
  app/src/main/graphql/schema.graphqls
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/data/PPOCardFactory.kt
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PPOCardView.kt
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewScreen.kt
  app/src/main/java/com/kickstarter/libs/utils/RewardViewUtils.kt
  app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
Labels: bug 🐛, UI 🎨

#2127 [No Ticket] UI tweaks for PPO
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PPOCardView.kt
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewActivity.kt
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewScreen.kt
Labels: UI 🎨

#2128 [MBL-1726] Make PPO webview use correct endpoint and logs user in automatically
  app/src/main/graphql/fragments.graphql
  app/src/main/java/com/kickstarter/services/interceptors/WebRequestInterceptor.kt
Labels: bug 🐛

#2130 MBL-1737: When user has no saved cards and stripe link fails or is canceled there is a crash
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/CheckoutScreen.kt
  app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
  app/src/main/java/com/kickstarter/ui/fragments/CrowdfundCheckoutFragment.kt
Labels: Pledge Redemption

#2135 SD-3241: Wrong shipping value for Shipping World Wide rewards
  app/src/main/java/com/kickstarter/libs/utils/extensions/PledgeDataExt.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/PledgeDataExtTest.kt
Labels: Pledge Redemption

#2133 MBL-586: Unify rewards selection viewModels
  app/src/main/java/com/kickstarter/ui/fragments/RewardsFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardsFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/RewardsSelectionViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardsFragmentViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardsSelectionViewModelTest.kt
Labels: Pledge Redemption
