Repository kickstarter/android-oss, pull requests merged in 2024-03, with the labels that each got.

#1965 [MBL-1164] Add post campaign fields to project queries/mutations
  app/src/main/graphql/fragments.graphql
  app/src/main/java/com/kickstarter/models/Project.kt
Labels: Post Campaign Functionality

#1966 [No Ticket] Adjust some colors to be closer to new design color schemes
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSBadges.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSButtons.kt
Labels: UI 🎨

#1962 [no-jira]: unify login screens, two viewModels. [PROPOSAL]
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/ui/activities/LoginToutActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/OAuthActivity.kt
  app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt
  app/src/main/java/com/kickstarter/viewmodels/OAuthViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/OAuthViewModelTest.kt
Labels: OAuth 2.0

#1964 [MBL-1229] Add Compose Views for Add-ons screen
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AddOnsContainer.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AddOnsScreen.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSDimensions.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSStepper.kt
Labels: UI 🎨, Post Campaign Functionality

#1967 [MBL-1227] Add post campaign messaging for project page
  app/src/main/java/com/kickstarter/models/Project.kt
  app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
  app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectOverviewFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectOverviewViewModel.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/kickstarter/viewmodels/ProjectOverviewViewModelTest.kt
Labels: UI 🎨, Post Campaign Functionality

#1968 [MBL-1254] Add the confirm pledge screen and views
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AddOnsScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/ConfirmPledgeDetailsScreen.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSStepper.kt
Labels: UI 🎨, Post Campaign Functionality

#1971 MBL-1262: QA party bug fixes
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/ui/activities/ChangePasswordActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/LoginToutActivity.kt
Labels: OAuth 2.0

#1973 [No-jira]: Analytic event added
  app/src/main/java/com/kickstarter/viewmodels/OAuthViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/OAuthViewModelTest.kt
Labels: OAuth 2.0

#1974 MBL-772: MessagesThreadViewModel to RXJava2
  app/src/main/java/com/kickstarter/ui/activities/HelpSettingsActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/MessageThreadsActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/MessageThreadsViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/MessageThreadsViewModelTest.kt
Labels: migration

#1977 [No Ticket] bump version codes/names
  app/external_version_code.txt
  app/external_version_name.txt
  app/internal_version_code.txt
  app/internal_version_name.txt
Labels: release 🚀

#1983 MBL-1269: Encrypt/decript token
  app/src/main/java/com/kickstarter/ApplicationModule.java
  app/src/main/java/com/kickstarter/libs/featureflag/FeatureFlagClient.kt
  app/src/main/java/com/kickstarter/libs/keystore/EncryptionEngine.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/StringExt.kt
  app/src/main/java/com/kickstarter/services/interceptors/GraphQLInterceptor.kt
  app/src/test/java/com/kickstarter/libs/preferences/EncryptionEngineTest.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/StringExtKtTest.kt
Labels: OAuth 2.0

#1987 [NoTicket] Fix add-ons shipping rule logic
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AddOnsScreen.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/AddOnsViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/CheckoutFlowViewModel.kt
Labels: bug 🐛, Post Campaign Functionality

#1986 MBL-1291: Feature Flag for latePledges
  app/src/main/java/com/kickstarter/libs/utils/extensions/ProjectExt.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectPageViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectPageViewModelTest.kt
Labels: Post Campaign Functionality

#1979 [MBL-1259] Add logic for confirm checkout page
  app/src/main/graphql/fragments.graphql
  app/src/main/graphql/payments.graphql
  app/src/main/java/com/kickstarter/models/StoredCard.kt
  app/src/main/java/com/kickstarter/models/extensions/StoredCardExt.kt
  app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
  app/src/main/java/com/kickstarter/services/mutations/CreateBackingData.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AddOnsScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/CheckoutScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/ConfirmPledgeDetailsScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/ProjectPledgeButtonAndFragmentContainer.kt
  app/src/main/java/com/kickstarter/ui/compose/KSRewardCard.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/AddOnsViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/CheckoutFlowViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ConfirmDetailsViewModel.kt
Labels: Post Campaign Functionality

#1988 [No ticket] - Merging Feature branch post campaign
  .circleci/config.yml
  app/src/main/AndroidManifest.xml
  app/src/main/graphql/fragments.graphql
  app/src/main/graphql/payments.graphql
  app/src/main/java/com/kickstarter/libs/utils/RewardUtils.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/ProjectExt.kt
  app/src/main/java/com/kickstarter/models/StoredCard.kt
  app/src/main/java/com/kickstarter/models/extensions/StoredCardExt.kt
  app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
  app/src/main/java/com/kickstarter/services/mutations/CreateBackingData.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AddOnsContainer.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AddOnsScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/CheckoutScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/ConfirmPledgeDetailsScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/ProjectPledgeButtonAndFragmentContainer.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/RewardCarouselScreen.kt
  app/src/main/java/com/kickstarter/ui/compose/KSRewardCard.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSAlerts.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSDimensions.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/AddOnsViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/CheckoutFlowViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ConfirmDetailsViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectPageViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/RewardsSelectionViewModel.kt
  app/src/main/res/layout/activity_project_page.xml
  app/src/test/java/com/kickstarter/viewmodels/ProjectPageViewModelTest.kt
Labels: Post Campaign Functionality

#1989 MBL-1292: Launch LogIn user when Continue button clicked
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/CheckoutFlowViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/usecases/CheckoutFlowViewModelTest.kt
Labels: Post Campaign Functionality

#1990 [MBL-1300] Make confirm details screen use same default location logic as add-ons
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AddOnsScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/ConfirmPledgeDetailsScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/ProjectPledgeButtonAndFragmentContainer.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/AddOnsViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/CheckoutFlowViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ConfirmDetailsViewModel.kt
Labels: bug 🐛, Post Campaign Functionality

#1992 MBL-1258: Analytics, changes on project properties for Late Pledges
  app/src/main/java/com/kickstarter/libs/utils/AnalyticEventsUtils.kt
  app/src/test/java/com/kickstarter/libs/SegmentTest.kt
Labels: Post Campaign Functionality

#1991 [MBL1260] Add Checkout Screen to Flow
  app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/CheckoutScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/ConfirmPledgeDetailsScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/ProjectPledgeButtonAndFragmentContainer.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ConfirmDetailsViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/LatePledgeCheckoutViewModel.kt
Labels: Post Campaign Functionality

#1993 [MBL-1294] Add unit tests for rewards selection viewmodel
  app/src/test/java/com/kickstarter/viewmodels/RewardsSelectionViewModelTest.kt
Labels: Post Campaign Functionality

#1994 [MBL-1299] Make it so late pledge flow is not shown if user has backed the project
  app/src/main/java/com/kickstarter/libs/utils/extensions/ProjectExt.kt
Labels: Post Campaign Functionality
