Repository kickstarter/android-oss, pull requests merged in 2024-07, with the labels that each got.

#2067 MBL-1543: Pledge Redemption payments prototype
  app/build.gradle
  app/src/internal/java/com/kickstarter/ui/activities/PlaygroundActivity.kt
  app/src/internal/java/com/kickstarter/viewmodels/PlaygroundViewModel.java
  app/src/internal/java/com/kickstarter/viewmodels/PlaygroundViewModel.kt
  app/src/internal/res/layout/playground_layout.xml
  app/src/main/graphql/checkout.graphql
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/models/CompleteOrder.kt
  app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
Labels: Pledge Redemption

#2068 MBL-1568: Rewards carousel has shipping selector
  app/src/main/java/com/kickstarter/libs/utils/RewardUtils.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/ConfigExtension.kt
  app/src/main/java/com/kickstarter/mock/factories/LocationFactory.kt
  app/src/main/java/com/kickstarter/mock/factories/RewardFactory.kt
  app/src/main/java/com/kickstarter/mock/factories/ShippingRuleFactory.kt
  app/src/main/java/com/kickstarter/mock/factories/ShippingRulesEnvelopeFactory.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AddOnsScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/ConfirmPledgeDetailsScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/ProjectPledgeButtonAndFragmentContainer.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/RewardCarouselScreen.kt
  app/src/main/java/com/kickstarter/ui/adapters/RewardsAdapter.kt
  app/src/main/java/com/kickstarter/ui/data/PledgeData.kt
  app/src/main/java/com/kickstarter/ui/fragments/RewardsFragment.kt
  app/src/main/java/com/kickstarter/ui/views/compose/ShippingSelector.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardsFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/usecases/GetShippingRulesUseCase.kt
  app/src/main/res/layout/fragment_rewards.xml
  app/src/test/java/com/kickstarter/libs/SegmentTest.kt
  app/src/test/java/com/kickstarter/libs/utils/RewardUtilsTest.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/ConfigExtensionTest.kt
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardsFragmentViewModelTest.kt
Labels: Pledge Redemption

#2069 MBL-1476: PPO Screen Loading, empty, and error states
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewActivity.kt
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewScreen.kt
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/viewmodel/PledgedProjectsOverviewViewModel.kt
  app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
  app/src/main/res/drawable/ic_refresh_arrow.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewScreenTest.kt
  app/src/test/java/com/kickstarter/features/pledgedprojectsoverview/viewmodel/PledgedProjectsOverviewViewModelTest.kt
Labels: feature ✨, UI 🎨

#2070 MBL-1569: Remove shipping selector from AddOns Screen Crowdfund checkout
  app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/usecases/GetShippingRulesUseCase.kt
  app/src/main/res/layout/fragment_backing_addons.xml
  app/src/test/java/com/kickstarter/viewmodels/BackingAddOnsFragmentViewModelTest.kt
Labels: Pledge Redemption

#2071 MBL-1578: rewards carousel late pledges contains shipping selector
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/ui/fragments/RewardsFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/RewardsSelectionViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/usecases/GetShippingRulesUseCase.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardsFragmentViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardsSelectionViewModelTest.kt
Labels: Pledge Redemption

#2073 MBL-1479: Fix payment card - fix pledge CTA flow
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/data/PPOCardFactory.kt
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewActivity.kt
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewScreen.kt
  app/src/main/java/com/kickstarter/ui/IntentKey.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/test/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewScreenTest.kt
  app/src/test/java/com/kickstarter/features/pledgedprojectsoverview/viewmodel/PledgedProjectsOverviewViewModelTest.kt
Labels: feature ✨

#2074 MBL-1570: Remove shipping selector from addOns late pledge
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AddOnsScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/ProjectPledgeButtonAndFragmentContainer.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/AddOnsViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/AddOnsViewModelTest.kt
Labels: Pledge Redemption

#2077 MBL-1596: Remove debug.keystore from source code
  app/build.gradle
  app/debug.keystore
Labels: bug 🐛

#2082 [MBL-801] Update survey response viewmodel to RX2
  app/src/main/java/com/kickstarter/ui/activities/SurveyResponseActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/SurveyResponseViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/SurveyResponseViewModelTest.kt
Labels: refactor 🛠

#2083 [MBL-800] Update survey viewholder viewmodel to RX2
  app/src/main/java/com/kickstarter/ui/viewholders/SurveyViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/SurveyHolderViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/SurveyHolderViewModelTest.kt
Labels: refactor 🛠

#2086 [No Ticket] Update review library from play:core to play:review-ktx library
  app/build.gradle
Labels: integrations
