Repository kickstarter/android-oss, pull requests merged in 2024-10, with the labels that each got.

#2139 [MBL-1758] Only send event for rewards carousel if the currentProjectData is available
  app/src/main/java/com/kickstarter/viewmodels/projectpage/RewardsSelectionViewModel.kt
Labels: bug 🐛

#2144 [MBL-811] Update Discovery Fragment to RX2
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
  app/src/main/java/com/kickstarter/ui/fragments/DiscoveryFragment.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ActivitySampleProjectViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/DiscoveryFragmentViewModelTest.kt
Labels: refactor 🛠

#2142 MBL-1744: Refactor Fix Pledge Flow
  app/src/main/java/com/kickstarter/libs/featureflag/FeatureFlagClient.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/FragmentExt.kt
  app/src/main/java/com/kickstarter/services/mutations/UpdateBackingData.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt
  app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
  app/src/main/java/com/kickstarter/ui/fragments/CrowdfundCheckoutFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/CrowdfundCheckoutViewModel.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/FragmentExtTest.kt
  app/src/test/java/com/kickstarter/viewmodels/CrowdfundCheckoutViewModelTest.kt
Labels: Pledge Redemption

#2146 MBL-1760: Update 3DS snackbar with new copy and duration when user fails authentication
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewActivity.kt
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/viewmodel/PledgedProjectsOverviewViewModel.kt
  app/src/test/java/com/kickstarter/features/pledgedprojectsoverview/viewmodel/PledgedProjectsOverviewViewModelTest.kt
Labels: UI 🎨, copy 📝

#2149 [NoTicket] various RXjava cleanup
  app/src/main/java/com/kickstarter/ui/adapters/MessagesAdapter.java
  app/src/main/java/com/kickstarter/ui/adapters/MessagesAdapter.kt
  app/src/main/java/com/kickstarter/ui/intentmappers/ProjectIntentMapper.kt
  app/src/main/java/com/kickstarter/viewmodels/outputs/DiscoveryFragmentViewModelOutputs.java
  app/src/test/java/com/kickstarter/ui/intents/ProjectIntentMapperTest.kt
Labels: refactor 🛠

#2152 [MBL-812] Update DiscoveryViewModel to RX2
  app/src/internal/java/com/kickstarter/libs/InternalTools.java
  app/src/internal/java/com/kickstarter/libs/InternalTools.kt
  app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
  app/src/main/java/com/kickstarter/libs/InternalToolsType.java
  app/src/main/java/com/kickstarter/libs/InternalToolsType.kt
  app/src/main/java/com/kickstarter/libs/NoopInternalTools.java
  app/src/main/java/com/kickstarter/libs/NoopInternalTools.kt
  app/src/main/java/com/kickstarter/libs/utils/AnalyticEventsUtils.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/DiscoveryParamsExt.kt
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/services/DiscoveryParams.kt
  app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.kt
  app/src/main/java/com/kickstarter/ui/adapters/DiscoveryDrawerAdapter.kt
  app/src/main/java/com/kickstarter/ui/intentmappers/DiscoveryIntentMapper.kt
  app/src/main/java/com/kickstarter/ui/viewholders/discoverydrawer/ParentFilterViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.kt
  app/src/test/java/com/kickstarter/libs/SegmentTest.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/DiscoveryParamsExtKtTest.kt
  app/src/test/java/com/kickstarter/ui/intents/DiscoveryIntentMapperTest.java
  app/src/test/java/com/kickstarter/ui/intents/DiscoveryIntentMapperTest.kt
  app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.kt
Labels: refactor 🛠

#2153 [NoTicket] Delete BaseActivity and ActivityViewModel
  app/src/internal/java/com/kickstarter/ui/activities/InternalToolsActivity.kt
  app/src/internal/java/com/kickstarter/viewmodels/InternalToolsViewModel.java
  app/src/main/java/com/kickstarter/libs/ActivityViewModel.java
  app/src/main/java/com/kickstarter/libs/ActivityViewModelManager.java
  app/src/main/java/com/kickstarter/libs/ApiPaginator.java
  app/src/main/java/com/kickstarter/libs/BaseActivity.java
  app/src/main/java/com/kickstarter/libs/CurrentConfig.java
  app/src/main/java/com/kickstarter/libs/CurrentConfig.kt
  app/src/main/java/com/kickstarter/libs/CurrentConfigType.java
  app/src/main/java/com/kickstarter/libs/CurrentConfigType.kt
  app/src/main/java/com/kickstarter/libs/SwipeRefresher.java
  app/src/main/java/com/kickstarter/libs/loadmore/ApolloPaginate.kt
  app/src/main/java/com/kickstarter/libs/qualifiers/RequiresActivityViewModel.java
  app/src/main/java/com/kickstarter/libs/rx/transformers/Transformers.java
  app/src/main/java/com/kickstarter/libs/utils/ApplicationUtils.java
  app/src/main/java/com/kickstarter/libs/utils/ApplicationUtils.kt
  app/src/main/java/com/kickstarter/mock/MockCurrentConfig.java
  app/src/main/java/com/kickstarter/mock/factories/ApiExceptionFactory.java
  app/src/main/java/com/kickstarter/services/ConnectivityReceiver.kt
  app/src/main/java/com/kickstarter/ui/activities/FacebookConfirmationActivity.kt
  app/src/main/java/com/kickstarter/ui/toolbars/KSToolbar.kt
  app/src/main/java/com/kickstarter/ui/toolbars/ProjectToolbar.kt
  app/src/main/java/com/kickstarter/ui/viewholders/AddCardViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/ui/viewholders/AddOnViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/RewardAddCardViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ThanksCategoryHolderViewModel.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ThanksCategoryViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/AddOnViewHolderViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/FacebookConfirmationViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/FacebookConfirmationViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/MessageHolderViewModel.kt
  app/src/test/java/com/kickstarter/libs/rx/transformers/TakeWhenTransformerTest.java
  app/src/test/java/com/kickstarter/libs/rx/transformers/TakeWhenTransformerTest.kt
  app/src/test/java/com/kickstarter/viewmodels/AddCardViewHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/AddOnViewHolderViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/FacebookConfimationViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/FacebookConfimationViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ThanksCategoryHolderViewModelTest.java
  app/src/test/java/com/kickstarter/viewmodels/ThanksCategoryHolderViewModelTest.kt
Labels: refactor 🛠

#2154 [no-jira] hotfix for 3.26.0 release - crashes in discovery fragment when context is null
  app/external_version_code.txt
  app/external_version_name.txt
  app/internal_version_code.txt
  app/internal_version_name.txt
  app/src/main/java/com/kickstarter/ui/fragments/DiscoveryFragment.kt
Labels: bug 🐛

#2157 MBL-1822: Compose UI tests for ChangePasswordScreen
  app/src/main/java/com/kickstarter/ui/activities/compose/ChangePasswordScreen.kt
  app/src/test/java/com/kickstarter/ui/activities/compose/ChangePasswordScreenTest.kt
Labels: UI 🎨, maintenance 🗜

#2158 MBL-1823: Compose UI tests for RisksScreen
  app/src/main/java/com/kickstarter/ui/fragments/projectpage/ui/RisksScreen.kt
  app/src/test/java/com/kickstarter/ui/activities/compose/RisksScreenTest.kt
Labels: UI 🎨, maintenance 🗜

#2159 MBL-1825 Fix 'Back this project' component on Project activity (UI)
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/res/layout/activity_project_page.xml
  app/src/main/res/layout/pledge_container.xml
Labels: bug 🐛

#2161 MBL-1833: Compose UI tests for PledgeItemizedDetails composable
  app/src/main/java/com/kickstarter/ui/views/compose/checkout/PledgeItemizedDetails.kt
  app/src/test/java/com/kickstarter/ui/activities/compose/PledgeItemizedDetailsTest.kt
Labels: UI 🎨, maintenance 🗜
