Repository kickstarter/android-oss, pull requests merged in 2024-08, with the labels that each got.

#2085 [MBL-1650] Fix crashes with large WEBP images
  app/src/main/java/com/kickstarter/ui/extensions/ImageViewExt.kt
  app/src/main/java/com/kickstarter/ui/views/ImageWithCaptionView.kt
Labels: bug 🐛

#2087 [BugFix] Add ui thread call and some null safety to avoid profile crash
  app/src/main/java/com/kickstarter/ui/activities/ProfileActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/ProfileViewModel.kt
Labels: bug 🐛

#2088 MBL-1556: Add network calls to confirm address and requery the PPO card list
  app/src/main/graphql/checkout.graphql
  app/src/main/graphql/fragments.graphql
  app/src/main/graphql/pledgeProjectsOverview.graphql
  app/src/main/graphql/schema.graphqls
  app/src/main/graphql/schema.json
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/data/Category.kt
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/data/PPOCard.kt
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/data/PPOCardFactory.kt
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/data/PledgeTierType.kt
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/data/PledgedProjectsOverviewEnvelope.kt
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PPOCardView.kt
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewActivity.kt
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewScreen.kt
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/viewmodel/PledgedProjectsOverviewViewModel.kt
  app/src/main/java/com/kickstarter/mock/factories/ProjectFactory.kt
  app/src/main/java/com/kickstarter/models/StoredCard.kt
  app/src/main/java/com/kickstarter/models/extensions/StoredCardExt.kt
  app/src/main/java/com/kickstarter/services/mutations/CreateOrUpdateBackingAddressData.kt
  app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
  app/src/main/java/com/kickstarter/ui/IntentKey.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/test/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewScreenTest.kt
  app/src/test/java/com/kickstarter/features/pledgedprojectsoverview/viewmodel/PledgedProjectsOverviewViewModelTest.kt
  app/src/test/java/com/kickstarter/models/StoredCardTest.kt
  app/src/test/java/com/kickstarter/ui/activities/compose/PPOCardViewKtTest.kt
Labels: feature ✨

#2089 MBL-1571: Bonus support in add ons screen
  app/src/main/java/com/kickstarter/libs/KSCurrency.kt
  app/src/main/java/com/kickstarter/libs/utils/RewardUtils.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/PledgeDataExt.kt
  app/src/main/java/com/kickstarter/mock/factories/RewardFactory.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AddOnsScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/CheckoutScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/ConfirmPledgeDetailsScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/ProjectPledgeButtonAndFragmentContainer.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/RewardCarouselScreen.kt
  app/src/main/java/com/kickstarter/ui/data/PledgeData.kt
  app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
  app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
  app/src/main/java/com/kickstarter/ui/fragments/RewardsFragment.kt
  app/src/main/java/com/kickstarter/ui/views/compose/checkout/BonusSupport.kt
  app/src/main/java/com/kickstarter/ui/views/compose/checkout/PledgeItemizedDetails.kt
  app/src/main/java/com/kickstarter/ui/views/compose/checkout/ShippingSelector.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/AddOnsViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/CheckoutFlowViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ConfirmDetailsViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/LatePledgeCheckoutViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/RewardsSelectionViewModel.kt
  app/src/main/res/layout/fragment_pledge.xml
  app/src/test/java/com/kickstarter/libs/utils/extensions/PledgeDataExtTest.kt
  app/src/test/java/com/kickstarter/viewmodels/AddOnsViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/CheckoutFlowViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ConfirmDetailsViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/LatePledgeCheckoutViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/LatePledgeCheckoutViewModelTests.kt
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardsSelectionViewModelTest.kt
Labels: Pledge Redemption

#2090 [MBL-1575] Add estimated shipping costs for rewards and add-ons
  app/src/main/graphql/fragments.graphql
  app/src/main/java/com/kickstarter/libs/utils/RewardViewUtils.kt
  app/src/main/java/com/kickstarter/models/ShippingRule.kt
  app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AddOnsContainer.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AddOnsScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/RewardCarouselScreen.kt
  app/src/main/java/com/kickstarter/ui/compose/KSRewardCard.kt
  app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/AddOnsViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/AddOnsViewModelTest.kt
Labels: Pledge Redemption

#2093 [MBL-1577] Mgriego/mbl 1577
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectPageViewModel.kt
  app/src/main/res/menu/manage_pledge_live.xml
Labels: Pledge Redemption

#2094 MBL-1576: Filter rewards by location
  app/src/main/graphql/fragments.graphql
  app/src/main/java/com/kickstarter/libs/utils/extensions/ConfigExtension.kt
  app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/RewardCarouselScreen.kt
  app/src/main/java/com/kickstarter/ui/fragments/RewardsFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardsFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/AddOnsViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/LatePledgeCheckoutViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/RewardsSelectionViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/usecases/GetShippingRulesUseCase.kt
  app/src/test/java/com/kickstarter/viewmodels/AddOnsViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/LatePledgeCheckoutViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardsSelectionViewModelTest.kt
Labels: Pledge Redemption

#2095 MBL[1583/1584] Add bonus support visual treatments based on selected reward
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AddOnsScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/ProjectPledgeButtonAndFragmentContainer.kt
  app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
  app/src/main/java/com/kickstarter/ui/views/compose/checkout/BonusSupport.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/AddOnsViewModel.kt
Labels: Pledge Redemption

#2099 MBL-1635: Mock data to real data, and cleanup
  app/src/main/graphql/fragments.graphql
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PPOCardView.kt
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewActivity.kt
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewScreen.kt
  app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
Labels: bug 🐛, feature ✨, UI 🎨

#2100 MBL-1664: Update copy on 3DS validation success and failure snackbars
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewActivity.kt
  app/src/main/res/values/strings.xml
Labels: feature ✨, copy 📝

#2102 MBL-1573: Add new payment method using stripe
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/ProjectPledgeButtonAndFragmentContainer.kt
  app/src/main/java/com/kickstarter/ui/fragments/CrowdfundCheckoutFragment.kt
  app/src/main/java/com/kickstarter/ui/views/compose/checkout/BonusSupport.kt
  app/src/main/java/com/kickstarter/ui/views/compose/checkout/PledgeItemizedDetails.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/CrowdfundCheckoutViewModel.kt
Labels: Pledge Redemption

#2103 MBL-1573: Checkout Screen (Change Reward flow for crowdfund)
  app/src/main/graphql/fragments.graphql
  app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
  app/src/main/java/com/kickstarter/ui/fragments/RewardsFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardsFragmentViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/AddOnsViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/RewardsSelectionViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/usecases/GetShippingRulesUseCase.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardsFragmentViewModelTest.kt
Labels: Pledge Redemption

#2105 [MBL-1574] Add estimated shipping visuals to checkout screens
  app/src/main/java/com/kickstarter/libs/utils/RewardViewUtils.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AddOnsScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/CheckoutScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/ProjectPledgeButtonAndFragmentContainer.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/RewardCarouselScreen.kt
  app/src/main/java/com/kickstarter/ui/fragments/CrowdfundCheckoutFragment.kt
  app/src/main/java/com/kickstarter/ui/views/compose/checkout/PledgeItemizedDetails.kt
Labels: Pledge Redemption

#2107 MBL-1573: Testing + small UI details
  app/src/main/java/com/kickstarter/ui/ArgumentsKey.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/CheckoutScreen.kt
  app/src/main/java/com/kickstarter/ui/views/compose/checkout/PledgeItemizedDetails.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/CrowdfundCheckoutViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/usecases/SendThirdPartyEventUseCaseV2.kt
  app/src/test/java/com/kickstarter/viewmodels/CrowdfundCheckoutViewModelTest.kt
Labels: Pledge Redemption

#2109 MBL-1659: Update card tags/pills to match backend schema and other small changes
  app/src/main/graphql/pledgeProjectsOverview.graphql
  app/src/main/graphql/schema.graphqls
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/data/Flag.kt
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/data/PPOCard.kt
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PPOCardView.kt
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewScreen.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/StringExt.kt
  app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSBadges.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSColors.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/kickstarter/ui/activities/compose/PPOCardViewKtTest.kt
Labels: feature ✨, UI 🎨, copy 📝

#2110 MBL-1585: small touch ups
  app/src/main/java/com/kickstarter/libs/utils/RewardViewUtils.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AddOnsContainer.kt
Labels: Pledge Redemption

#2111 [MBL-818] Remove RX1 from message thread holder view/viewmodel
  app/src/main/java/com/kickstarter/ui/viewholders/MessageThreadViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/MessageThreadHolderViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/MessageThreadHolderViewModelTest.kt
Labels: refactor 🛠

#2114 [MBL-823] Update ProjectNotificationViewmodel to RX2
  app/src/main/java/com/kickstarter/ui/viewholders/ProjectNotificationViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectNotificationViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectNotificationsViewModelTest.kt
Labels: refactor 🛠

#2116 MBL-1676: When a project is no longer allowed to collect, view rewards menu should not filter rewards nor show the select button
  app/src/main/java/com/kickstarter/libs/utils/extensions/ProjectExt.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/RewardCarouselScreen.kt
  app/src/main/java/com/kickstarter/viewmodels/usecases/GetShippingRulesUseCase.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/ProjectExtTest.kt
  app/src/test/java/com/kickstarter/viewmodels/usecases/GetShippingRulesUseCaseTest.kt
Labels: Pledge Redemption

#2117 [no-jira]:Translation strings ready
  app/src/main/assets/json/server-config.json
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AddOnsContainer.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/CheckoutScreen.kt
  app/src/main/java/com/kickstarter/ui/compose/KSRewardCard.kt
  app/src/main/java/com/kickstarter/ui/views/compose/checkout/BonusSupport.kt
  app/src/main/res/values-de/strings_i18n.xml
  app/src/main/res/values-es/strings_i18n.xml
  app/src/main/res/values-fr/strings_i18n.xml
  app/src/main/res/values-ja/strings_i18n.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/strings_i18n.xml
Labels: Pledge Redemption

#2115 [MBL-822] Update Project Notifications Settings to RX2
  app/src/main/java/com/kickstarter/ui/activities/ProjectNotificationSettingsActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/ProjectNotificationSettingsViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectNotificationSettingsViewModelTest.kt
Labels: refactor 🛠
