Repository kickstarter/android-oss, pull requests merged in 2024-01, with the labels that each got.

#1925 [MBL-806] Update (Remove) WebViewViewModel
  app/src/main/java/com/kickstarter/ui/activities/WebViewActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/WebViewViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/WebViewViewModelTest.kt
Labels: refactor 🛠

#1923 MBL-1077: Coroutines in ChangePasswordViewModel + Tests
  app/build.gradle
  app/src/main/java/com/kickstarter/ui/activities/ChangePasswordActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/ChangePasswordViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ChangePasswordViewModelTest.kt
Labels: UI 🎨

#1926 [MBL-764] Update ErroredBackingViewModel to RX2
  app/src/main/java/com/kickstarter/ui/viewholders/ErroredBackingViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/ErroredBackingViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ErroredBackingViewHolderViewModelTest.kt
Labels: refactor 🛠

#1924 MBL-810: DeeplinkViewModel.kt to Jetpack ViewModel and RxJava2.2
  app/src/main/java/com/kickstarter/ui/activities/DeepLinkActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/DeepLinkViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/DeepLinkViewModelTest.kt
Labels: refactor 🛠, maintenance 🗜

#1922 [MBL-1127] Dark mode
  app/src/main/java/com/kickstarter/libs/featureflag/FeatureFlagClient.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/ContextExt.kt
  app/src/main/java/com/kickstarter/ui/activities/ChangePasswordActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/CreatePasswordActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/LoginActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/LoginToutActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/PreLaunchProjectPageActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ReportProjectActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ResetPasswordActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/SearchActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/SetPasswordActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/SignupActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/TwoFactorActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/FormularyScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/PreLaunchProjectPageScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/ReportProjectScreen.kt
  app/src/main/java/com/kickstarter/ui/compose/KSImageCompose.kt
  app/src/main/java/com/kickstarter/ui/compose/KSTextCompose.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSButtonCompose.kt
  app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectAIFragment.kt
  app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectRiskFragment.kt
  app/src/main/java/com/kickstarter/ui/fragments/projectpage/ui/RisksScreen.kt
  app/src/main/java/com/kickstarter/ui/toolbars/compose/ToolBar.kt
  app/src/main/java/com/kickstarter/ui/views/compose/KsCreatorLayout.kt
  app/src/main/java/com/kickstarter/viewmodels/DiscoveryViewModel.kt
  app/src/main/res/drawable/ic_menu_dark.xml
  app/src/main/res/drawable/ic_menu_error_indicator_dark.xml
  app/src/main/res/drawable/ic_menu_indicator_dark.xml
  app/src/main/res/layout/messages_backing_info_view.xml
  app/src/main/res/layout/project_tags.xml
  app/src/main/res/values-v29/styles.xml
  app/src/test/java/com/kickstarter/viewmodels/DiscoveryViewModelTest.kt
Labels: WIP 🔨, UI 🎨

#1929 MBL-807: ActivityFeed migrated to RXJava2
  app/src/main/java/com/kickstarter/libs/rx/transformers/IncrementalCountTransformerV2.kt
  app/src/main/java/com/kickstarter/libs/rx/transformers/Transformers.java
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
  app/src/main/java/com/kickstarter/ui/activities/ActivityFeedActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/ActivityFeedViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/ActivityFeedViewModelTest.kt
Labels: refactor 🛠

#1928 Update RepliesStatusCellViewHolderViewmodel to RX2
  app/src/main/java/com/kickstarter/ui/viewholders/RepliesStatusCellViewHolder.kt
  app/src/main/java/com/kickstarter/viewmodels/RepliesStatusCellViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/RepliesStatusCellViewHolderViewModelTest.kt
Labels: refactor 🛠

#1930 [MBL-1135] Add analytics value for session_force_dark_mode
  app/src/main/java/com/kickstarter/libs/TrackingClient.kt
  app/src/main/java/com/kickstarter/libs/TrackingClientType.kt
  app/src/test/java/com/kickstarter/libs/MockTrackingClient.kt
  app/src/test/java/com/kickstarter/libs/SegmentTest.kt
Labels: events 🛤

#1933 [MBL-782] Update NotificationActivity to RX2
  app/src/main/java/com/kickstarter/ui/activities/NotificationsActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/NotificationsViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/NotificationsViewModelTest.kt
Labels: refactor 🛠

#1932 MBL-905: Remove Use of IA tab feature flag
  app/src/main/java/com/kickstarter/libs/featureflag/FeatureFlagClient.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/AiDisclosureExt.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ProjectPageViewModel.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/AiDisclosureExtTest.kt
  app/src/test/java/com/kickstarter/viewmodels/ProjectPageViewModelTest.kt
Labels: feature ✨

#1931 MBL-808: BackingFragmentViewModel.kt to Jetpack ViewModel and RxJava2.2
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/ui/fragments/BackingFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/BackingFragmentViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/BackingFragmentViewModelTest.kt
Labels: maintenance 🗜, integrations

#1935 [No-jira]: Updated graphql schema
  app/src/main/graphql/schema.json
Labels: maintenance 🗜

#1938 MBL-1171: Feature flag for OAuth
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/libs/featureflag/FeatureFlagClient.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/IntentExt.kt
  app/src/main/java/com/kickstarter/ui/activities/LoginToutActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/OAuthActivity.kt
  app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt
  app/src/main/java/com/kickstarter/viewmodels/LoginToutViewModel.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/IntentExtTest.kt
  app/src/test/java/com/kickstarter/viewmodels/LoginToutViewModelTest.kt
Labels: feature ✨
