Repository kickstarter/android-oss, pull requests merged in 2024-06, with the labels that each got.

#2053 MBL-1466: Create graphQL confirm address mutation
  app/src/main/graphql/createOrUpdateBackingAddress.graphql
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
  app/src/main/java/com/kickstarter/services/mutations/CreateOrUpdateBackingAddressData.kt
  app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
Labels: feature ✨

#2054 [MBL-1530] Add trigger for 3ds flow for post campaign payments
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/LatePledgeCheckoutViewModel.kt
  app/src/test/java/com/kickstarter/ui/activities/compose/LoginToutScreenTest.kt
Labels: bug 🐛, Post Campaign Functionality

#2058 [MBL-1535] Fix bug when adding existing payment method it unselects a card
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/CheckoutScreen.kt
Labels: bug 🐛
