Repository kickstarter/android-oss, pull requests merged in 2024-02, with the labels that each got.

#1941 MBL-1167: New Login/Sign up Screen with Chrome Tabs (Phase 2)
  app/build.gradle
  app/src/main/java/com/kickstarter/models/chrome/ChromeTabsHelperActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/OAuthActivity.kt
  app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt
  build.gradle
Labels: feature ✨

#1943 MBL-1168: PKCE class
  app/src/main/java/com/kickstarter/libs/utils/CodeVerifier.kt
  app/src/main/java/com/kickstarter/ui/activities/OAuthActivity.kt
  app/src/test/java/com/kickstarter/libs/utils/CodeVerifierTest.kt
Labels: feature ✨

#1947 MBL-1169: Redirection step
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/libs/utils/CodeVerifier.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/IntentExt.kt
  app/src/main/java/com/kickstarter/models/chrome/ChromeTabsHelperActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/OAuthActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/OAuthViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/OAuthActivityViewModelTest.kt
Labels: OAuth 2.0

#1948 MBL-1202: Crash on CommentsViewHolderViewModel
  app/src/main/java/com/kickstarter/ui/extensions/ImageViewExt.kt
  app/src/main/java/com/kickstarter/viewmodels/CommentsViewHolderViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/CommentsViewHolderViewModelTest.kt
Labels: bug 🐛

#1952 [no-jira]: Updated schema.json
  app/src/main/graphql/checkout.graphql
  app/src/main/graphql/schema.json
Labels: maintenance 🗜

#1954 MBL-1170: Get token and User, Log in flow completed.
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/ApplicationModule.java
  app/src/main/java/com/kickstarter/mock/services/MockApiClientV2.kt
  app/src/main/java/com/kickstarter/services/ApiClientTypeV2.java
  app/src/main/java/com/kickstarter/services/ApiClientV2.java
  app/src/main/java/com/kickstarter/services/ApiServiceV2.java
  app/src/main/java/com/kickstarter/services/apirequests/PKCEBody.kt
  app/src/main/java/com/kickstarter/services/apirequests/UserTokenBody.kt
  app/src/main/java/com/kickstarter/services/apiresponses/OAuthTokenEnvelope.kt
  app/src/main/java/com/kickstarter/services/interceptors/ApiRequestInterceptor.kt
  app/src/main/java/com/kickstarter/ui/activities/LoginToutActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/OAuthActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/LoginToutViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/OAuthViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/usecases/LoginUseCase.kt
  app/src/test/java/com/kickstarter/viewmodels/LoginToutViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/OAuthActivityViewModelTest.kt
Labels: OAuth 2.0

#1956 MBL-1198: Reorder rewards so that unavailable ones show last
  app/src/main/java/com/kickstarter/ui/adapters/RewardsAdapter.kt
  app/src/main/java/com/kickstarter/viewmodels/RewardsFragmentViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardsFragmentViewModelTest.kt
Labels: UI 🎨

#1957 MBL-1183: Crash caused by index out of bounds in SearchViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/SearchViewModel.kt
Labels: bug 🐛

#1958 MBL-1213: Stop sending token as query param for V1, send the token as basic auth header
  app/src/main/java/com/kickstarter/libs/CurrentUser.java
  app/src/main/java/com/kickstarter/libs/CurrentUserType.java
  app/src/main/java/com/kickstarter/libs/CurrentUserV2.kt
  app/src/main/java/com/kickstarter/libs/utils/ApplicationLifecycleUtil.java
  app/src/main/java/com/kickstarter/libs/utils/ApplicationLifecycleUtil.kt
  app/src/main/java/com/kickstarter/mock/services/MockApiClientV2.kt
  app/src/main/java/com/kickstarter/services/ApiClientTypeV2.java
  app/src/main/java/com/kickstarter/services/ApiClientV2.java
  app/src/main/java/com/kickstarter/services/interceptors/ApiRequestInterceptor.kt
  app/src/main/java/com/kickstarter/viewmodels/FacebookConfirmationViewModel.java
  app/src/main/java/com/kickstarter/viewmodels/LoginToutViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/LoginViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/OAuthViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/SetPasswordViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/SignupViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/TwoFactorViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/usecases/LoginUseCase.kt
  app/src/test/java/com/kickstarter/libs/MockCurrentUser.java
  app/src/test/java/com/kickstarter/libs/MockCurrentUserV2.kt
  app/src/test/java/com/kickstarter/viewmodels/ActivityFeedViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/LoginToutViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/MessageThreadsViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/OAuthActivityViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/SetPasswordViewModelTest.kt
Labels: OAuth 2.0

#1961 MBL-1232: Unify and verify sign up/log in buttons
  app/src/main/java/com/kickstarter/libs/utils/extensions/IntentExt.kt
  app/src/main/java/com/kickstarter/ui/activities/LoginToutActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/login/LoginToutScreen.kt
  app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt
  app/src/main/java/com/kickstarter/viewmodels/LoginToutViewModel.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/IntentExtTest.kt
  app/src/test/java/com/kickstarter/ui/activities/compose/LoginToutScreenTest.kt
  app/src/test/java/com/kickstarter/viewmodels/LoginToutViewModelTest.kt
Labels: OAuth 2.0
