Repository kickstarter/android-oss, pull requests merged in 2024-04, with the labels that each got.

#1995 [MBL-1303] Add adding payment method to the checkout screen
  app/src/main/graphql/checkout.graphql
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/CheckoutScreen.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/LatePledgeCheckoutViewModel.kt
Labels: Post Campaign Functionality

#1996 Do some cleanup on the late pledge flow
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AddOnsScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/CheckoutScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/ConfirmPledgeDetailsScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/ProjectPledgeButtonAndFragmentContainer.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/RewardCarouselScreen.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/AddOnsViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ConfirmDetailsViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/LatePledgeCheckoutViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/RewardsSelectionViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardsSelectionViewModelTest.kt
Labels: UI 🎨, Post Campaign Functionality

#1998 MBL-1278: Analytic events for rewards
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/RewardsSelectionViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardsSelectionViewModelTest.kt
Labels: Post Campaign Functionality

#1999 [Late Pledge Bugs] Add saving payment method to late pledge flow
  app/src/main/graphql/checkout.graphql
  app/src/main/java/com/kickstarter/mock/services/MockApolloClient.kt
  app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/LatePledgeCheckoutViewModel.kt
Labels: bug 🐛, Post Campaign Functionality

#2001 MBL-1278: Analytics on late pledge checkout screen
  app/src/main/java/com/kickstarter/libs/AnalyticEvents.kt
  app/src/main/java/com/kickstarter/libs/utils/EventContextValues.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/LatePledgeCheckoutViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/LatePledgeCheckoutViewModelTest.kt
Labels: Post Campaign Functionality

#2003 [MBL-1321/1322] Fix payment sheet being presented multiple times
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
Labels: bug 🐛, Post Campaign Functionality

#2005 [MBL-1320/1323] Fix bonus amount issues
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/ConfirmPledgeDetailsScreen.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/ConfirmDetailsViewModel.kt
Labels: bug 🐛, Post Campaign Functionality

#2006 [MBL-1319] Add links functionality for checkout page
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/CheckoutScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/ProjectPledgeButtonAndFragmentContainer.kt
Labels: bug 🐛, Post Campaign Functionality

#2004 MBL-1286: Avoided lateinit error for after OAuth redirection step.
  app/src/main/java/com/kickstarter/viewmodels/OAuthViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/OAuthViewModelTest.kt
Labels: bug 🐛, OAuth 2.0

#2007 MBL-1336: Remove OAuth feature flag
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/libs/utils/extensions/IntentExt.kt
  app/src/main/java/com/kickstarter/ui/activities/ChangePasswordActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/CreatePasswordActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/FacebookConfirmationActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/LoginActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/LoginToutActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/SignupActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/TwoFactorActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/login/LoginScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/login/LoginToutScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/login/SignupScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/login/TwoFactorScreen.kt
  app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt
  app/src/main/java/com/kickstarter/viewmodels/LoginToutViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/LoginViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/SignupViewModel.kt
  app/src/main/java/com/kickstarter/viewmodels/TwoFactorViewModel.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/IntentExtTest.kt
  app/src/test/java/com/kickstarter/ui/activities/compose/LoginScreenTest.kt
  app/src/test/java/com/kickstarter/ui/activities/compose/LoginToutScreenTest.kt
  app/src/test/java/com/kickstarter/ui/activities/compose/TwoFactorScreenTest.kt
  app/src/test/java/com/kickstarter/ui/activities/compose/login/SignupScreenKtTest.kt
  app/src/test/java/com/kickstarter/viewmodels/LoginToutViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/LoginViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/SignupViewModelTest.kt
  app/src/test/java/com/kickstarter/viewmodels/TwoFactorViewModelTest.kt
Labels: OAuth 2.0

#2010 [MBL-1342] Fix non-shippable rewards being able to select shippable add-ons
  app/src/main/java/com/kickstarter/viewmodels/projectpage/AddOnsViewModel.kt
Labels: bug 🐛, Post Campaign Functionality

#2011 [MBL-1353] Update copy to be blank for late pledges
  app/src/main/java/com/kickstarter/ui/viewholders/ThanksShareViewHolder.kt
Labels: bug 🐛, Post Campaign Functionality

#2012 MBL-1286: OAuth when default browser not chrome
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/libs/utils/extensions/ContextExt.kt
  app/src/main/java/com/kickstarter/ui/IntentKey.kt
  app/src/main/java/com/kickstarter/ui/activities/LoginToutActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/OAuthWebViewActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/WebViewActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/OAuthViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/OAuthViewModelTest.kt
Labels: OAuth 2.0

#2013 [No Ticket] Update reward summary to use the cost for the full quantity
  app/src/main/java/com/kickstarter/viewmodels/ExpandableHeaderViewHolderViewModel.kt
Labels: UI 🎨

#2015 MBL-1318: Spiking crash PicassoDrawable.draw trying to draw too large bitmap mitigation
  app/src/main/java/com/kickstarter/ui/activities/EditProfileActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/ProfileActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/SettingsActivity.kt
  app/src/main/java/com/kickstarter/ui/extensions/ImageViewExt.kt
  app/src/main/java/com/kickstarter/ui/fragments/projectpage/ProjectOverviewFragment.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ActivitySampleFriendFollowViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ActivitySampleProjectViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/FriendBackingViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/FriendFollowViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/MessageThreadViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/MessageViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ProfileCardViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ProjectCardViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ProjectStateChangedPositiveViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ProjectStateChangedViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/ProjectUpdateViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/SurveyViewHolder.kt
  app/src/main/java/com/kickstarter/ui/viewholders/discoverydrawer/LoggedInViewHolder.kt
  app/src/main/java/com/kickstarter/ui/views/MediaHeader.kt
Labels: bug 🐛

#2014 MBL-1327: Currency conversion shows regardless of if necessary
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/AddOnsScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/CheckoutScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/ConfirmPledgeDetailsScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/RewardCarouselScreen.kt
Labels: bug 🐛, UI 🎨, Post Campaign Functionality

#2018 MBL-1318: Removed Picasso dependency
  app/build.gradle
  app/src/main/java/com/kickstarter/libs/PushNotifications.java
  app/src/main/java/com/kickstarter/libs/transformations/CircleTransformation.java
  app/src/main/java/com/kickstarter/libs/transformations/CropSquareTransformation.java
  app/src/main/java/com/kickstarter/ui/extensions/ImageViewExt.kt
Labels: bug 🐛

#2019 [HOTFIX] Fix issue where add-ons were not displayed if non of the rewards were shippable
  app/src/main/java/com/kickstarter/viewmodels/projectpage/AddOnsViewModel.kt
Labels: bug 🐛, Post Campaign Functionality

#2020 [BUGFIX] Fix add-ons for master branch
  app/src/main/java/com/kickstarter/viewmodels/projectpage/AddOnsViewModel.kt
Labels: bug 🐛, Post Campaign Functionality

#2022 MBL-1348: Firebase BOM version updated
  app/build.gradle
  app/src/internal/AndroidManifest.xml
Labels: maintenance 🗜

#2024 No-jira: Gradle wrapper version upgrade
  build.gradle
  gradle/wrapper/gradle-wrapper.properties
Labels: maintenance 🗜

#2026 [MBL-1383] Update adding new payment method flow in late pledge flow
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/LatePledgeCheckoutViewModel.kt
Labels: bug 🐛, release 🚀, Post Campaign Functionality

#2027 MBL-1380: Reward is showing as available for late pledges despite not being available
  app/src/main/java/com/kickstarter/viewmodels/projectpage/RewardsSelectionViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/RewardsSelectionViewModelTest.kt
Labels: bug 🐛, Post Campaign Functionality
