Repository kickstarter/android-oss, pull requests merged in 2025-02, with the labels that each got.

#2218 MBL-2041: Clean up feature flag for refactor fix payment
  app/src/main/java/com/kickstarter/libs/featureflag/FeatureFlagClient.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/FragmentExt.kt
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt
  app/src/main/java/com/kickstarter/ui/fragments/BackingAddOnsFragment.kt
  app/src/main/java/com/kickstarter/ui/fragments/CrowdfundCheckoutFragment.kt
  app/src/main/java/com/kickstarter/ui/fragments/PledgeFragment.kt
  app/src/main/java/com/kickstarter/viewmodels/PledgeFragmentViewModel.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/FragmentExtTest.kt
  app/src/test/java/com/kickstarter/viewmodels/PledgeFragmentViewModelTest.kt
Labels: maintenance 🗜

#2221 MBL-2039: Bare minimum Statsig integration
  app/build.gradle
  app/src/androidTest/java/com/kickstarter/screenshoot/testing/InstrumentedApp.kt
  app/src/androidTest/java/com/kickstarter/screenshoot/testing/ui/components/AddOnTagShotTest.kt
  app/src/androidTest/java/com/kickstarter/screenshoot/testing/ui/components/AddonCardShotTest.kt
  app/src/androidTest/java/com/kickstarter/screenshoot/testing/ui/components/CommentCardShotTest.kt
  app/src/androidTest/java/com/kickstarter/screenshoot/testing/ui/components/CommentComposerShotTest.kt
  app/src/androidTest/java/com/kickstarter/screenshoot/testing/ui/components/EnvironmentalCommitmentsCardSnapShotTest.kt
  app/src/androidTest/java/com/kickstarter/screenshoot/testing/ui/components/FrequentlyAskedQuestionCardSnapShotTesting.kt
  app/src/androidTest/java/com/kickstarter/screenshoot/testing/ui/components/MediaHeaderShotTest.kt
  app/src/androidTest/java/com/kickstarter/screenshoot/testing/ui/components/RiskMessageShotTest.kt
  app/src/androidTest/java/com/kickstarter/screenshoot/testing/ui/components/StepperShotTest.kt
  app/src/internal/java/com/kickstarter/ui/activities/InternalToolsActivity.kt
  app/src/internal/java/com/kickstarter/ui/views/DebugPushNotificationsView.kt
  app/src/main/java/com/kickstarter/ApplicationModule.java
  app/src/main/java/com/kickstarter/KSApplication.java
  app/src/main/java/com/kickstarter/KSApplication.kt
  app/src/main/java/com/kickstarter/libs/Environment.kt
  app/src/main/java/com/kickstarter/libs/featureflag/StatsigClient.kt
  app/src/main/java/com/kickstarter/libs/utils/ApplicationLifecycleUtil.kt
  app/src/main/java/com/kickstarter/libs/utils/Secrets.java.example
  app/src/main/java/com/kickstarter/libs/utils/extensions/ContextExt.kt
  app/src/main/java/com/kickstarter/services/firebase/MessageService.kt
  app/src/main/java/com/kickstarter/services/firebase/RegisterTokenWorker.kt
  app/src/main/java/com/kickstarter/services/firebase/ResetDeviceIdWorker.kt
  app/src/main/java/com/kickstarter/services/firebase/UnregisterTokenWorker.kt
  app/src/main/java/com/kickstarter/ui/activities/DeepLinkActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/DiscoveryActivity.kt
  app/src/main/java/com/kickstarter/ui/toolbars/KSToolbar.kt
  app/src/main/java/com/kickstarter/ui/viewholders/KSArrayViewHolder.kt
  app/src/main/java/com/kickstarter/ui/views/KSWebView.kt
  app/src/test/java/com/kickstarter/libs/StatsigClientTest.kt
  build.gradle
Labels: feature ✨

#2226 MBL-2036: [Phase 1] UI Updates: Chevron for backing details
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PPOCardView.kt
  app/src/main/res/drawable/ic_chevron_rounded_right.xml
Labels: feature ✨, UI 🎨

#2227 MBL-2038: [Phase 1] UI Updates: Mail icon for message creator
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PPOCardView.kt
  app/src/main/res/drawable/ic_envelope.xml
Labels: feature ✨, UI 🎨

#2230 MBL-2030: [Phase 1] UI Updates: Copy changes on ppo screen title and empty state copy
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewActivity.kt
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewScreen.kt
  app/src/main/res/values/strings.xml
Labels: feature ✨, UI 🎨, copy 📝

#2237 MBL-2031: [Phase 1] UI Updates: Bottom sheet for beta messaging
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/BetaMessagingBottomSheet.kt
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewScreen.kt
  app/src/main/java/com/kickstarter/ui/compose/KSTextCompose.kt
  app/src/main/res/drawable/drag_handle.xml
  app/src/main/res/drawable/ic_check_rounded.xml
  app/src/main/res/drawable/ic_info_new.xml
  app/src/main/res/drawable/ic_task_to_do.xml
  app/src/main/res/values/strings.xml
  app/src/test/java/com/kickstarter/features/pledgedprojectsoverview/ui/BetaMessagingBottomSheetKtTest.kt
  app/src/test/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewScreenTest.kt
Labels: feature ✨, UI 🎨

#2239 MBL-2134: New feature flag and SearchAndFilterActivity
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/libs/featureflag/FeatureFlagClient.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/IntentExt.kt
  app/src/main/java/com/kickstarter/ui/activities/SearchAndFilterActivity.kt
  app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt
  app/src/main/java/com/kickstarter/ui/toolbars/DiscoveryToolbar.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/IntentExtTest.kt
Labels: feature ✨
