Repository kickstarter/android-oss, pull requests merged in 2025-01, with the labels that each got.

#2198 MBL-1945: Android 15 adaptation for PPO Screen
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PledgedProjectsOverviewScreen.kt
Labels: bug 🐛

#2203 MBL-1992: Currency format for PaymentIncrement
  app/src/main/java/com/kickstarter/libs/utils/ProjectViewUtils.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/StringExt.kt
  app/src/main/java/com/kickstarter/ui/views/compose/checkout/PaymentSchedule.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/StringExtKtTest.kt
  app/src/test/java/com/kickstarter/ui/activities/compose/PaymentScheduleTest.kt
Labels: feature ✨

#2206 MBL-1982: Additional PLOT strings internationalization
  app/src/main/assets/json/server-config.json
  app/src/main/java/com/kickstarter/ui/views/compose/checkout/PaymentSchedule.kt
  app/src/main/res/values-de/strings_i18n.xml
  app/src/main/res/values-es/strings_i18n.xml
  app/src/main/res/values-fr/strings_i18n.xml
  app/src/main/res/values-ja/strings_i18n.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/strings_i18n.xml
  app/src/test/java/com/kickstarter/ui/activities/compose/PaymentScheduleTest.kt
Labels: feature ✨, copy 📝

#2205 MBL-1950: Double charge late pledge
  app/src/main/java/com/kickstarter/ui/activities/ProjectPageActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/CheckoutScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/projectpage/ProjectPledgeButtonAndFragmentContainer.kt
  app/src/main/java/com/kickstarter/viewmodels/projectpage/LatePledgeCheckoutViewModel.kt
  app/src/test/java/com/kickstarter/viewmodels/LatePledgeCheckoutViewModelTest.kt
Labels: bug 🐛

#2211 [NO JIRA]: Release versions
  app/external_version_code.txt
  app/external_version_name.txt
  app/internal_version_code.txt
Labels: release 🚀

#2217 MBL-2055: Avoid adding the Authorization header if the token is empty
  app/src/main/java/com/kickstarter/services/interceptors/GraphQLInterceptor.kt
Labels: bug 🐛
