Repository kickstarter/android-oss, pull requests merged in 2025-03, with the labels that each got.

#2244 MBL-2132 FilterMenuBottomSheet For category UI
  app/src/internal/java/com/kickstarter/ui/activities/DesignSystemActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/search/CategorySelectionSheet.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/search/SearchScreen.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSButtonsV2.kt
  app/src/main/java/com/kickstarter/ui/views/compose/search/SearchTopBar.kt
  app/src/test/java/com/kickstarter/ui/activities/compose/search/CategorySelectionSheetTest.kt
Labels: feature ✨

#2247 MBL-2135: SearchAndFilter viewmodel
  app/src/main/java/com/kickstarter/features/search/ui/SearchAndFilterActivity.kt
  app/src/main/java/com/kickstarter/features/search/viewmodel/SearchAndFilterViewModel.kt
  app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/search/SearchScreen.kt
  app/src/test/java/com/kickstarter/features/search/viewmodel/SearchAndFilterViewModelTest.kt
  app/src/test/java/com/kickstarter/libs/StatsigClientTest.kt
Labels: feature ✨

#2252 MBL-2061: [Phase 2] New card states: Add new backend card states to PledgeTierType enum, hook up to new PPOCardViewTypes
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/data/PledgeTierType.kt
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PPOCardView.kt
  app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
Labels: feature ✨

#2251 MBL-2138: SearchVM now is able to query options for Category and Sorting
  app/src/main/java/com/kickstarter/features/search/ui/SearchAndFilterActivity.kt
  app/src/main/java/com/kickstarter/features/search/viewmodel/SearchAndFilterViewModel.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/DiscoveryParamsExt.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/ProjectExt.kt
  app/src/main/java/com/kickstarter/services/DiscoveryParams.kt
  app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/search/SearchScreen.kt
  app/src/test/java/com/kickstarter/features/search/viewmodel/SearchAndFilterViewModelTest.kt
Labels: feature ✨

#2253 MBL-2057: [Phase 2] New card states: New info flag type
  app/src/main/java/com/kickstarter/features/pledgedprojectsoverview/ui/PPOCardView.kt
  app/src/test/java/com/kickstarter/ui/activities/compose/PPOCardViewKtTest.kt
Labels: feature ✨, UI 🎨

#2260 MBL-2131: SortMenuBottomSheet UI component
  app/src/main/java/com/kickstarter/features/search/ui/SearchAndFilterActivity.kt
  app/src/main/java/com/kickstarter/features/search/viewmodel/SearchAndFilterViewModel.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/ProjectExt.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/search/CategorySelectionSheet.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/search/SearchScreen.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/search/SortSelectionBottomSheet.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/kickstarter/features/search/viewmodel/SearchAndFilterViewModelTest.kt
  app/src/test/java/com/kickstarter/ui/activities/compose/search/SortSelectionBottomSheetKtTest.kt
Labels: feature ✨, UI 🎨

#2275 MBL-2238 && MBL-2213: Pagination polish
  app/src/main/java/com/kickstarter/features/search/data/SearchEnvelope.kt
  app/src/main/java/com/kickstarter/features/search/ui/SearchAndFilterActivity.kt
  app/src/main/java/com/kickstarter/features/search/viewmodel/SearchAndFilterViewModel.kt
  app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
  app/src/test/java/com/kickstarter/features/search/viewmodel/SearchAndFilterViewModelTest.kt
Labels: bug 🐛, feature ✨, UI 🎨

#2283 MBL-2217: New pill bar buttons
  app/src/main/java/com/kickstarter/ui/activities/compose/search/SearchScreen.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSButtons.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSDimensions.kt
  app/src/main/java/com/kickstarter/ui/views/compose/search/SearchTopBar.kt
  app/src/main/res/drawable/ic_filter.xml
  app/src/main/res/values/strings.xml
Labels: UI 🎨
