Repository kickstarter/android-oss, pull requests merged in 2025-04, with the labels that each got.

#2288 MBL-2284: UI updates to view your pledge screen - move reward delivery date and reminder to top of screen
  app/src/main/res/layout/fragment_backing.xml
Labels: feature ✨, UI 🎨

#2289 MBL-2219: FilterMenu UI
  app/src/internal/java/com/kickstarter/ui/activities/DesignSystemActivity.kt
  app/src/main/graphql/project.graphql
  app/src/main/graphql/schema.graphqls
  app/src/main/java/com/kickstarter/libs/utils/extensions/DiscoveryParamsExt.kt
  app/src/main/java/com/kickstarter/services/DiscoveryParams.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/search/CategorySelectionSheet.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/search/FilterMenuBottomSheet.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/search/SearchScreen.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSButtons.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSDimensions.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSFooters.kt
  app/src/main/java/com/kickstarter/ui/views/compose/search/SearchTopBar.kt
  app/src/main/res/values/strings.xml
  app/src/test/java/com/kickstarter/ui/activities/compose/search/FilterMenuBottomSheetTest.kt
Labels: UI 🎨

#2291 MBL-2219:Changing order, "Successful" Pill needs to go the last option
  app/src/main/java/com/kickstarter/ui/activities/compose/search/FilterMenuBottomSheet.kt
Labels: UI 🎨

#2293 MBL-2221: User is able to execute a search filtering by project status
  app/src/main/java/com/kickstarter/features/search/ui/SearchAndFilterActivity.kt
  app/src/main/java/com/kickstarter/features/search/viewmodel/SearchAndFilterViewModel.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/DiscoveryParamsExt.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/ProjectExt.kt
  app/src/main/java/com/kickstarter/services/DiscoveryParams.kt
  app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
  app/src/main/java/com/kickstarter/services/transformers/GraphQLTransformers.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/search/FilterMenuBottomSheet.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/search/SearchScreen.kt
  app/src/test/java/com/kickstarter/features/search/viewmodel/SearchAndFilterViewModelTest.kt
  app/src/test/java/com/kickstarter/ui/activities/compose/search/FilterMenuBottomSheetTest.kt
Labels: feature ✨

#2294 MBL-2221: small UI tweeks
  app/src/main/java/com/kickstarter/ui/activities/compose/search/SearchScreen.kt
Labels: bug 🐛

#2295 MBL-2287: Create UI for tracking number modal in view your pledge screen
  app/src/main/java/com/kickstarter/features/rewardtracking/RewardTrackingViews.kt
  app/src/main/java/com/kickstarter/ui/compose/KSImageCompose.kt
Labels: feature ✨, UI 🎨

#2298 MBL-2225 && MBL-2223: Navigation between Main Filter menu screen (includes project state filter), and the Category Selection screen
  app/src/main/java/com/kickstarter/ui/activities/compose/search/CategorySelectionSheet.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/search/FilterMenuBottomSheet.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/search/SearchScreen.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSDimensions.kt
  app/src/test/java/com/kickstarter/ui/activities/compose/search/CategorySelectionSheetTest.kt
  app/src/test/java/com/kickstarter/ui/activities/compose/search/FilterMenuBottomSheetTest.kt
  app/src/test/java/com/kickstarter/ui/activities/compose/search/SearchScreenTest.kt
Labels: feature ✨

#2301 MBL-2258: Feature flag for phase 2
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/kickstarter/features/search/ui/SearchAndFilterActivity.kt
  app/src/main/java/com/kickstarter/libs/utils/extensions/IntentExt.kt
  app/src/main/java/com/kickstarter/ui/activities/SearchActivity.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/search/CategorySelectionSheet.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/search/SearchScreen.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSButtons.kt
  app/src/main/java/com/kickstarter/ui/extensions/ActivityExt.kt
  app/src/main/java/com/kickstarter/ui/toolbars/DiscoveryToolbar.kt
  app/src/main/java/com/kickstarter/ui/views/compose/search/SearchTopBar.kt
  app/src/main/java/com/kickstarter/viewmodels/SearchViewModel.kt
  app/src/test/java/com/kickstarter/libs/utils/extensions/IntentExtTest.kt
  app/src/test/java/com/kickstarter/ui/activities/compose/search/CategorySelectionSheetTest.kt
  app/src/test/java/com/kickstarter/ui/activities/compose/search/SearchScreenTest.kt
  app/src/test/java/com/kickstarter/ui/activities/compose/search/SearchTopBarTest.kt
  app/src/test/java/com/kickstarter/viewmodels/SearchViewModelTest.kt
Labels: feature ✨

#2308 [no-jira]: Keep current user selection while navigating back-forth
  app/src/main/java/com/kickstarter/ui/activities/compose/search/SearchScreen.kt
Labels: bug 🐛

#2312 MBL-2304: Search&Filter with subcategories
  app/src/main/java/com/kickstarter/features/search/viewmodel/FilterMenuViewModel.kt
  app/src/main/java/com/kickstarter/mock/factories/CategoryFactory.kt
  app/src/main/java/com/kickstarter/mock/services/MockApolloClientV2.kt
  app/src/main/java/com/kickstarter/models/Category.kt
  app/src/main/java/com/kickstarter/services/KSApolloClientV2.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/search/CategorySelectionSheet.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/search/FilterMenuBottomSheet.kt
  app/src/test/java/com/kickstarter/features/search/viewmodel/FilterMenuViewModelTest.kt
  app/src/test/java/com/kickstarter/ui/activities/compose/search/CategorySelectionSheetTest.kt
Labels: feature ✨

#2315 MBL-2389: Reset button functionality changes
  app/src/main/assets/json/server-config.json
  app/src/main/java/com/kickstarter/ui/activities/compose/search/CategorySelectionSheet.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/search/FilterMenuBottomSheet.kt
  app/src/main/java/com/kickstarter/ui/activities/compose/search/SearchScreen.kt
  app/src/main/java/com/kickstarter/ui/compose/designsystem/KSFooters.kt
  app/src/main/java/com/kickstarter/ui/views/compose/search/SearchTopBar.kt
  app/src/main/res/values-de/strings_i18n.xml
  app/src/main/res/values-es/strings_i18n.xml
  app/src/main/res/values-fr/strings_i18n.xml
  app/src/main/res/values-ja/strings_i18n.xml
  app/src/main/res/values/strings_i18n.xml
  app/src/test/java/com/kickstarter/ui/activities/compose/search/CategorySelectionSheetTest.kt
  app/src/test/java/com/kickstarter/ui/activities/compose/search/SearchScreenTest.kt
Labels: feature ✨
